smithy-lang/smithy-kotlin

smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinWriter.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/RuntimeTypes.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpProtocolClientGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/ProtocolMiddleware.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpProtocolClientGeneratorTest.kt

closes #287
support for https://github.com/awslabs/aws-sdk-kotlin/pull/301
* Allow middleware to register interceptors inline without defining a `Feature`. 
* Allow middleware to define an order

refactor: allow non feature middleware; give middleware explicit order

---

runtime/protocol/http/common/src/aws/smithy/kotlin/runtime/http/request/HttpRequest.kt
runtime/protocol/http/common/test/aws/smithy/kotlin/runtime/http/HttpRequestBuilderTest.kt

N/A
* add convenience `HttpRequest` -> `HttpRequestBuilder` conversion

feat(rt): add conversion from HttpRequest -> builder

---

runtime/build.gradle.kts
runtime/io/common/src/aws/smithy/kotlin/runtime/io/Closeable.kt
runtime/io/jvm/src/aws/smithy/kotlin/runtime/io/CloseableJVM.kt
runtime/runtime-core/build.gradle.kts
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/SdkClient.kt

closes #248 
closes https://github.com/awslabs/aws-sdk-kotlin/issues/102
Have `SdkClient` (which all generated clients implement already) implement `Closeable` rather than defining a separate `close()` method
This will mean that generated clients can now make use of [use](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/use.html) where a client is closed automatically
e.g.
```kotlin
S3Client{ region = "us-east-1" }.use { client -> 
client.putObject { ... }
}
```

refactor(rt): make SdkClient implement Closeable

---

runtime/smithy-test/common/src/aws/smithy/kotlin/runtime/smithy/test/HttpResponseTest.kt

sibling PR: https://github.com/awslabs/aws-sdk-kotlin/pull/358
Use a streaming single use `HttpBody` variant for protocol tests which will more closely reflect reality.

fix(rt): emulate a real response body more closely to help catch subtle codegen bugs

---

smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinDependency.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinDependencyTest.kt

N/A
* Fixes build errors in https://github.com/awslabs/smithy-kotlin/pull/515 and https://github.com/awslabs/aws-sdk-kotlin/pull/383

Update regex to handle version segments greater than 9

---

gradle.properties
runtime/serde/serde-xml/common/test/aws/smithy/kotlin/runtime/serde/xml/XmlStreamReaderTest.kt
smithy-kotlin-codegen/build.gradle.kts
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/CodegenVisitor.kt

* Upgrade to latest version of smithy
* Add error flattening transform related to https://github.com/awslabs/smithy/pull/919

chore: upgrade smithy to 1.13

---

runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/client/SdkClientOption.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/RuntimeTypes.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/model/ShapeExt.kt

Addresses awslabs/aws-sdk-kotlin#245
Adds a convenience extension method for detecting the Streaming trait on shapes, which helps slightly with the integration for Glacier request body checksums.
**Also**: Expose `Sha256` type in `RuntimeTypes` for codegen in **aws-sdk-kotlin**.

feat: add convenience extension method for detecting if a Shape has the Streaming trait

---

gradle.properties
runtime/smithy-test/common/src/aws/smithy/kotlin/runtime/smithy/test/HttpRequestTest.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpBindingProtocolGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpBindingResolver.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/IdempotentTokenGeneratorTest.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpBindingProtocolGeneratorTest.kt

aws-sdk-kotlin#390
sibling to https://github.com/awslabs/aws-sdk-kotlin/pull/402
Fixes related to protocol tests added in smithy 1.13 for restJson1 protocol
* Only set `Content-Length` in mock engine for protocol tests when non-null and positive. `HttpBody.Empty` has a content-length of 0 and we were sending `Content-Length: 0`
* We were not properly using the http binding index to compute content types. We should not have fallen back to a default content type—instead we need to use exactly what is given. 
* upgrade smithy to latest bug fix release `1.13.1`

fix: delegate when to set content-type to binding resolver; fix content-length for empty bodies

---

runtime/protocol/http/common/src/aws/smithy/kotlin/runtime/http/operation/SdkHttpOperation.kt
runtime/serde/common/src/aws/smithy/kotlin/runtime/serde/Deserializer.kt
runtime/serde/common/src/aws/smithy/kotlin/runtime/serde/SdkObjectDescriptor.kt
runtime/serde/common/src/aws/smithy/kotlin/runtime/serde/SdkSerializable.kt
runtime/serde/serde-json/common/src/aws/smithy/kotlin/runtime/serde/json/JsonDeserializer.kt
runtime/serde/serde-json/common/src/aws/smithy/kotlin/runtime/serde/json/JsonLexer.kt
runtime/serde/serde-json/common/src/aws/smithy/kotlin/runtime/serde/json/JsonStreamReader.kt
runtime/serde/serde-json/common/test/aws/smithy/kotlin/runtime/serde/json/JsonDeserializerTest.kt
runtime/serde/serde-json/common/test/aws/smithy/kotlin/runtime/serde/json/JsonStreamReaderTest.kt
runtime/serde/serde-xml/common/src/aws/smithy/kotlin/runtime/serde/xml/XmlDeserializer.kt
runtime/serde/serde-xml/common/src/aws/smithy/kotlin/runtime/serde/xml/XmlPrimitiveDeserializer.kt
runtime/serde/serde-xml/common/src/aws/smithy/kotlin/runtime/serde/xml/XmlStreamReader.kt
runtime/serde/serde-xml/common/src/aws/smithy/kotlin/runtime/serde/xml/dom/XmlNode.kt
runtime/serde/serde-xml/common/test/aws/smithy/kotlin/runtime/serde/xml/SharedTestData.kt
runtime/serde/serde-xml/common/test/aws/smithy/kotlin/runtime/serde/xml/XmlDeserializerAWSTest.kt
runtime/serde/serde-xml/common/test/aws/smithy/kotlin/runtime/serde/xml/XmlDeserializerListTest.kt
runtime/serde/serde-xml/common/test/aws/smithy/kotlin/runtime/serde/xml/XmlDeserializerMapTest.kt
runtime/serde/serde-xml/common/test/aws/smithy/kotlin/runtime/serde/xml/XmlDeserializerNamespaceTest.kt
runtime/serde/serde-xml/common/test/aws/smithy/kotlin/runtime/serde/xml/XmlDeserializerPrimitiveTest.kt
runtime/serde/serde-xml/common/test/aws/smithy/kotlin/runtime/serde/xml/XmlDeserializerStructTest.kt
runtime/serde/serde-xml/common/test/aws/smithy/kotlin/runtime/serde/xml/XmlStreamReaderTest.kt
runtime/serde/serde-xml/common/test/aws/smithy/kotlin/runtime/serde/xml/dom/XmlDomTest.kt
runtime/serde/serde-xml/jvm/src/aws/smithy/kotlin/runtime/serde/xml/XmlStreamReaderXmlPull.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpBindingProtocolGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpProtocolClientGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/ProtocolMiddleware.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpProtocolClientGeneratorTest.kt

https://github.com/awslabs/aws-sdk-kotlin/issues/411
* remove `suspend` from deserialization (we aren't using it anyway and the benchmarks show that it is too slow so we aren't likely to ever use it)
* NOTE: The errors deserialization is still implemented with suspend because exception deserializers implement `HttpDeserialize`
* added `inline` to several places where it was missing
* inspection of generated code revealed that we were often capturing variables in a lambda and thus a backing class was being generated by the compiler
* inlined the middleware registration which removes a lot of unnecessary extra classes being generated
* this still suffers from the lambda closures being generated all over the place, e.g. `op.install(Feature) { <lambda capture> }`
* there will be some follow …

chore: optimize codegen for size round1

---

smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/ProtocolMiddleware.kt

N/A
Sibling to https://github.com/awslabs/aws-sdk-kotlin/pull/424
Fix rendering of feature middleware that doesn't require configuration. This was broken in #533 where the context of the renderer changed, we didn't notice because we apparently didn't have any middleware until now that triggered this path. 

fix(codegen); fix rendering of middleware without configure

---

runtime/serde/serde-xml/build.gradle.kts
runtime/serde/serde-xml/common/src/aws/smithy/kotlin/runtime/serde/xml/XmlDeserializer.kt
runtime/serde/serde-xml/jvm/src/aws/smithy/kotlin/runtime/serde/xml/XmlStreamReaderXmlPull.kt

(none)
While auditing our logging posture, I noticed that our XML deserializer logged response data (including potentially-sensitive data) at `TRACE` level. That's unnecessary given that it can be enabled by `SdkLogMode.LogResponseWithBody`. Thus, removing it.

fix: remove leaky trace logging from XML serde

---

smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/StructureGenerator.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/StructureGeneratorTest.kt

Fix collision in elastibeanstalk with nested struct dsl builder functions
https://github.com/awslabs/smithy-kotlin/issues/532
* Issue found when doing service build testing against https://github.com/awslabs/smithy-kotlin/pull/534
* Build and test all services locally after change, verify no name collisions

Fully qualify nested struct dsl builder type

---

runtime/protocol/http/common/src/aws/smithy/kotlin/runtime/http/middleware/ResolveEndpoint.kt
runtime/protocol/http/common/src/aws/smithy/kotlin/runtime/http/operation/Endpoint.kt
runtime/protocol/http/common/test/aws/smithy/kotlin/runtime/http/UrlTest.kt
runtime/protocol/http/common/test/aws/smithy/kotlin/runtime/http/middleware/ResolveEndpointTest.kt

support for aws-sdk-kotlin#475
* Allow resolved endpoints to add query parameters. This allows the ECS credentials provider `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` or `AWS_CONTAINER_CREDENTIALS_FULL_URI` to specify query parameters.
* Also fixes the formatting of combining endpoint paths and operation paths when the operation path is empty or `/`. Previously this would result in `/endpoint-path/` and now it will be just `/endpoint-path` without the trailing slash. 

feat(rt): allow query params to be set from resolved endpoints

---

smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/KotlinSettings.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinSymbolProvider.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinWriter.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/lang/KotlinTypes.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/model/SymbolBuilder.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/model/SymbolExt.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/lang/KotlinTypesTest.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/model/SymbolBuilderTest.kt

…and nicer codegen blocks
https://github.com/awslabs/smithy-kotlin/issues/124
* Changes to symbol resolution to pull out nested generics to handle Pagination codegen use cases.  As-is codegen of paginators with nested items fails because expressions such as `Map<String, List<SomeType>>` will not pull out the reference to `SomeType` and so we miss the import in codegen.
* Tweaks to `KotlinWriter` functions to return the instance for better readability
* Make `KotlinSettings` a data class so easier inspection at debug time

Refactor writer and symbols to handle pagination 

---

runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/retries/impl/StandardRetryPolicy.kt
runtime/runtime-core/common/test/aws/smithy/kotlin/runtime/retries/impl/StandardRetryPolicyTest.kt

fixes #555 
Do not retry `ClientException` unless metadata explicitly allows it. In general client exceptions are a class of exception that aren't retryable (serialization/deserialization errors, state errors, configuration errors, etc)

fix(rt): only retry client errors if metadata allows

---

smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/PaginatorGenerator.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/PaginatorGeneratorTest.kt

https://github.com/awslabs/smithy-kotlin/issues/565
* Revert change in feature PR to hardcode member as string, use modeled type.
* Ran ad-hoc test with dynamodb table with a large amount of data.  Verified affected operations compile and return same number of results paginated as rows contained in table.

Fix paginator generation for models that specify non-string cursor

---

tests/benchmarks/serde-benchmarks/build.gradle.kts
tests/codegen/paginator-tests/build.gradle.kts

N/A
Update the paginator-tests build script to ensure `smithy-kotlin-codegen` is built before smithy projection needs it AND that it ends up on the classpath. I think before it was only ending up on the classpath but for whatever reason not being built when needed. 

chore: change buildscript cp for ci

---

runtime/utils/common/src/aws/smithy/kotlin/runtime/util/Convenience.kt
smithy-kotlin-codegen/build.gradle.kts
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/RuntimeTypes.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/waiters/AcceptorGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/waiters/KotlinJmespathExpressionVisitor.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/waiters/AcceptorGeneratorTest.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/waiters/KotlinJmespathExpressionVisitorTest.kt

Addresses #572 
This change implements handling for the remaining types of Jmespath expressions that are currently used in AWS service models. It explicitly does not implement expression types which are today unused (e.g., boolean and expressions, index/slice expressions, multiselect hash expressions, certain types of literals, etc.).
This change overhauls the existing skeleton of `KotlinJmespathExpressionVisitor` and removes all usage of the model. This greatly simplifies the implementation but, since code generator is now unaware of the exact types of shapes it's operating on, there are two main downsides:
* Use of null checks and null-safe operators (e.g., `?.`, `?:`) in places that are technically unnecessary. The compiler issues warnings when building the generated code but it runs …

feat: implement Jmespath expression parsing for all modeled AWS services

---

smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/waiters/KotlinJmespathExpressionVisitor.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/waiters/KotlinJmespathExpressionVisitorTest.kt

Related to #572 
This was missed somehow in service codegen testing. Because Smithy's JMESPath parser always interprets literals (e.g., `` `42` ``) as doubles (e.g., `42.0`), these numbers aren't suitable for direct operator comparison with non-double values. Updating to use `compareTo` which allows comparison across types.

fix: make waiter comparison codegen type-safe

---

smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/waiters/KotlinJmespathExpressionVisitor.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/waiters/KotlinJmespathExpressionVisitorTest.kt
tests/codegen/waiter-tests/model/waiter-operations.smithy
tests/codegen/waiter-tests/src/test/kotlin/com/test/WaiterTest.kt

Addresses #572 
Fixes a previous PR (#583) regressing some of the null-safety in comparison codegen.

fix: make waiter comparison codegen null-safe

---

gradle.properties
runtime/protocol/http/common/src/aws/smithy/kotlin/runtime/http/util/HeaderLists.kt
runtime/protocol/http/common/test/aws/smithy/kotlin/runtime/http/util/HeaderListsTest.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/RuntimeTypes.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpBindingProtocolGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpStringValuesMapSerializer.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/JsonParserGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/JsonSerdeDescriptorGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/JsonSerializerGenerator.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpStringValuesMapSerializerTest.kt
smithy-kotlin-codegen/src/test/resources/software/amazon/smithy/kotlin/codegen/http-binding-protocol-generator-test.smithy

closes #586 
* upgrades smithy dependency to 1.17
* allow JSON serde generation to ignore the `@jsonName` trait (protocol tests were updated, awsJson protocols MUST not interpret these traits)
* fixes quoting of header list values (string and enums) when the value contains a quotation mark or comma
* fixes the header list split function to handle quoted values and escapes

chore: upgrade smithy to 1.17.0

---

smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinWriter.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/PaginatorGenerator.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ClientConfigGeneratorTest.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/PaginatorGeneratorTest.kt

(none)
This change adds DSL overloads to paginator methods. Previously, the only way to call paginators was with explicit request objects:
```kotlin
val client = SomeClient(…)
val initialRequest = ListItemsRequest {
foo = …
bar = …
}
val result = client.listItemsPaginated(initialRequest)
```
With this new change, paginators can now be called using DSL overloads that create request objects internally:
```kotlin
val client = SomeClient(…)
val result = client.listItemsPaginated {
foo = …
bar = …
}
```
This brings parity with the invocation options available for regular service operations, waiters, config, etc.
A minor change alongside this is an update to the KDoc formatting done in codegen. Previously, all blank lines were removed. Now, only leading, trailing, and consecutive blank lines …

feat: add DSL overloads to paginator methods

---

smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/KotlinSettings.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/model/ShapeExt.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/JsonParserGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/JsonSerializerGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/StructuredDataParserGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/StructuredDataSerializerGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/XmlParserGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/XmlSerializerGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/test/CodegenTestUtils.kt

N/A
Remove restriction that a payload serializer or deserializer can only be used for `MemberShape`

refactor(codegen): allow payload serializer and deserializer for any shape

---

docs/design/event-streams.md
runtime/io/common/src/aws/smithy/kotlin/runtime/io/SdkByteBuffer.kt
runtime/protocol/http/common/src/aws/smithy/kotlin/runtime/http/HttpBody.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinDelegator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinSymbolProvider.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinWriter.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/Naming.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/RuntimeTypes.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/model/ShapeExt.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/model/SymbolBuilder.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/UnionGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpBindingProtocolGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpBindingResolver.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/JsonParserGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/JsonSerializerGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/SerdeExt.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/StructuredDataParserGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/StructuredDataSerializerGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/XmlParserGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/XmlSerializerGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/test/CodegenTestUtils.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinDelegatorTest.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/core/NamingTest.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/core/SymbolProviderTest.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/StructureGeneratorTest.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/UnionGeneratorTest.kt
tests/benchmarks/serde-benchmarks-codegen/src/main/kotlin/SerdeBenchmarkJsonProtocolGenerator.kt
tests/compile/src/test/kotlin/software/amazon/smithy/kotlin/codegen/util/CodegenTestIntegration.kt

Support for https://github.com/awslabs/aws-sdk-kotlin/pull/545

feat: bootstrap event streams

---

docs/design/paginators.md

N/A
Nicki noticed our docs were inconsistent and that the naming went back and forth from `paginateListFunctions` and `listFunctionsPaginated`. The former was an alternative we considered but dropped for the latter. Additionally moved the naming decisions around to where we actually talk about the API instead of in the examples section.
There are no codegen changes, this is all just fixing errata.

chore: fix pagination design docs

---

runtime/build.gradle.kts
runtime/protocol/http-client-engines/http-client-engine-ktor/jvm/src/aws/smithy/kotlin/runtime/http/engine/ktor/KtorEngine.kt
runtime/protocol/http-client-engines/http-client-engine-ktor/jvm/src/aws/smithy/kotlin/runtime/http/engine/ktor/KtorUtils.kt
runtime/protocol/http-client-engines/http-client-engine-ktor/jvm/test/aws/smithy/kotlin/runtime/http/engine/ktor/KtorRequestAdapterTest.kt
runtime/protocol/http-client-engines/http-client-engine-ktor/jvm/test/aws/smithy/kotlin/runtime/http/engine/ktor/KtorUtilsTest.kt
runtime/protocol/http-client-engines/test-suite/build.gradle.kts
runtime/protocol/http-client-engines/test-suite/common/src/aws/smithy/kotlin/runtime/http/test/util/AbstractEngineTest.kt
runtime/protocol/http-client-engines/test-suite/common/test/aws/smithy/kotlin/runtime/http/test/AsyncStressTest.kt
runtime/protocol/http-client-engines/test-suite/common/test/aws/smithy/kotlin/runtime/http/test/DownloadTest.kt
runtime/protocol/http-client-engines/test-suite/common/test/aws/smithy/kotlin/runtime/http/test/RedirectTest.kt
runtime/protocol/http-client-engines/test-suite/common/test/aws/smithy/kotlin/runtime/http/test/UploadTest.kt
runtime/protocol/http-client-engines/test-suite/jvm/src/aws/smithy/kotlin/runtime/http/test/suite/Concurrency.kt
runtime/protocol/http-client-engines/test-suite/jvm/src/aws/smithy/kotlin/runtime/http/test/suite/Downloads.kt
runtime/protocol/http-client-engines/test-suite/jvm/src/aws/smithy/kotlin/runtime/http/test/suite/Redirects.kt
runtime/protocol/http-client-engines/test-suite/jvm/src/aws/smithy/kotlin/runtime/http/test/suite/Uploads.kt
runtime/protocol/http-client-engines/test-suite/jvm/src/aws/smithy/kotlin/runtime/http/test/util/AbstractEngineTestJVM.kt
runtime/protocol/http-client-engines/test-suite/jvm/src/aws/smithy/kotlin/runtime/http/test/util/TestServer.kt
runtime/protocol/http/common/src/aws/smithy/kotlin/runtime/http/SdkHttpClient.kt
settings.gradle.kts

closes #552 
Provide a common HTTP client engine test suite that all supported engines can test against. These tests run against a real local server that is spun up (from Gradle) before the tests run. Each KMP target will have to provide an instance of `AbstractEngineTest` that iterates over supported engines for that target. 
This initial set of tests is based on adapting tests we already have spread out over the Ktor and CRT engine tests. I expect that over time we will expand this test suite as we find more behaviors that we want to ensure are upheld across different engines. 
Possible future expansions:
* TLS / H2 tests
* Proxy tests
Both require quite a bit more thought/work to provide the necessary local test server instances. We may be better off writing TLS tests against e.g. …

test: bootstrap common http engine test suite

---

runtime/utils/common/src/aws/smithy/kotlin/runtime/util/text/Text.kt
runtime/utils/common/test/aws/smithy/kotlin/runtime/util/text/TextTest.kt

(none)
Adds a convenience function for decoding strings as URL components, necessary for a new unit test in [aws-sdk-kotlin#556](https://github.com/awslabs/aws-sdk-kotlin/pull/556).

chore: add convenience function for decoding URL components

---

smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpProtocolClientGenerator.kt

(none)
Temporarily adds support for handling `httpChecksum` the same as `httpChecksumRequired`. This enables consuming the latest model changes from S3 without fully implementing flexible checksums. Full support will come in [aws-sdk-kotlin#557](https://github.com/awslabs/aws-sdk-kotlin/issues/557).
Companion PR: [aws-sdk-kotlin#558](https://github.com/awslabs/aws-sdk-kotlin/pull/558)

fix: temporarily handle httpchecksum trait the same as httpchecksumrequired

---

runtime/protocol/http/common/src/aws/smithy/kotlin/runtime/http/middleware/ResolveEndpoint.kt
runtime/protocol/http/common/test/aws/smithy/kotlin/runtime/http/middleware/ResolveEndpointTest.kt

Closes #609 
[`Endpoint`](https://github.com/awslabs/smithy-kotlin/blob/58d464299e33e7e3c44e0ae563ce033c4e85ca01/runtime/protocol/http/common/src/aws/smithy/kotlin/runtime/http/operation/Endpoint.kt#L32) has an `isHostnameImmutable` flag but its value is never used anywhere. This PR updates endpoint resolution to skip hostname prefixing if this flag is set.

fix: respect hostname immutability in endpoints to disable host prefixing

---

runtime/serde/serde-xml/common/test/aws/smithy/kotlin/runtime/serde/xml/XmlStreamWriterTest.kt

Closes [aws-sdk-kotlin#547](https://github.com/awslabs/aws-sdk-kotlin/issues/547).
This change adds an explicit test to verify the handling of non-ASCII characters. This was previously a problem when using XmlPull for serialization but has since been fixed by the completely rewritten parser.

chore: add additional XML escaping test to verify correct serialization of non-ASCII characters

---

runtime/io/common/src/aws/smithy/kotlin/runtime/io/SdkByteReadChannel.kt
runtime/io/common/test/aws/smithy/kotlin/runtime/io/SdkByteChannelOpsTest.kt
runtime/protocol/http-client-engines/test-suite/common/test/aws/smithy/kotlin/runtime/http/test/UploadTest.kt

fixes #613
* Fill in missing behavior with unit test for `readAvailableFallback`
* Add test to HTTP engine test suite for a wrapped stream

fix: readAvailable fallback behavior

---

runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/retries/StandardRetryStrategy.kt
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/retries/delay/ExponentialBackoffWithJitter.kt
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/retries/delay/StandardRetryTokenBucket.kt
runtime/runtime-core/common/test/aws/smithy/kotlin/runtime/retries/StandardRetryStrategyTest.kt
runtime/runtime-core/jvm/test/aws/smithy/kotlin/runtime/retries/impl/StandardRetryIntegrationTest.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ClientConfigProperty.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/waiters/WaiterGenerator.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ClientConfigGeneratorTest.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/waiters/ServiceWaitersGeneratorTest.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/waiters/WaiterGeneratorTest.kt

fixes: https://github.com/awslabs/aws-sdk-kotlin/issues/572
Removes a maximum per/operation timeout from the StandardRetryStrategy. There is no sensible default for this timeout since an operation could involve a large request stream. It also subjected operations to timeout in highly concurrent environments with lots of coroutines if the coroutine was starved and just didn't get a chance to run.
Users can still impose timeouts for any given operation with the built-in `withTimeout` functionality, e.g.
```kotlin
// timeout for the whole operation to complete (including all retries)
withTimeout(myTimeout) {
client.fooOperation(...)
}
// timeout for a waiter to complete
withTimeout(myTimeout) {
client.waitForFooExist(...)
}
```
Waiters were previously hard coded to 5 min as an absolute …

fix: remove maxTime from StandardRetryStrategy

---

runtime/protocol/http-client-engines/http-client-engine-ktor/common/src/aws/smithy/kotlin/runtime/http/engine/ktor/KtorEngine.kt
runtime/protocol/http-client-engines/test-suite/common/test/aws/smithy/kotlin/runtime/http/test/AsyncStressTest.kt

fixes: https://github.com/awslabs/aws-sdk-kotlin/issues/587
Fixes a coroutine leak in the ktor engine due to invalid parent-child
relationship. The ktor engine was launching a coroutine as a child of
the request job (`calLContext()`). The issue was that this child
coroutine was relying on the parent job completion notification
to exit. Parent jobs can't complete though until all their children
do so the child coroutine never completed.
The ktor engine now uses the engine scope to launch this child
coroutine and establishes no parent-child relationship to the
request job explicitly.
```kotlin
fun main(): Unit = runBlocking {
val executor = newFixedThreadPoolContext(1, "poll-thread")
SqsClient { region = "us-east-1" }.use { sqs ->
withContext(executor) {
while(true) {
pollQueue(sqs) …
```

fix(rt): coroutine leak in ktor engine

---

runtime/protocol/http-client-engines/http-client-engine-ktor/common/src/aws/smithy/kotlin/runtime/http/engine/ktor/KtorRequestAdapter.kt
runtime/protocol/http-client-engines/http-client-engine-ktor/common/test/aws/smithy/kotlin/runtime/http/engine/ktor/KtorRequestAdapterTest.kt
runtime/protocol/http-client-engines/test-suite/common/test/aws/smithy/kotlin/runtime/http/test/UploadTest.kt
runtime/protocol/http-client-engines/test-suite/jvm/src/aws/smithy/kotlin/runtime/http/test/suite/Uploads.kt

Closes [aws-sdk-kotlin#588](https://github.com/awslabs/aws-sdk-kotlin/issues/588)
This change fixes a bug that omitted `Content-Type` (when set) from empty-body requests for the Ktor engine.

fix: set Content-Type header on empty bodies with Ktor if canonical request includes it

---

CHANGELOG.md
gradle.properties

Why 0.8.5? Glad you asked...0.8.4 was accidentally released without a refresh from `main` so 0.8.4 and 0.8.3 are the same.

chore: bump 0.8.6-SNAPSHOT 

---

.changes/74cc4273-d134-4b61-9f78-2ed740f3bd9a.json
gradle.properties
smithy-kotlin-codegen/build.gradle.kts
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinWriter.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/lang/DocumentationPreprocessor.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/PaginatorGenerator.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinWriterTest.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/lang/DocumentationPreprocessorTest.kt

#136 
Convert commonmark/html to kdoc/markdown such that formatting of original model docs aren't destroyed in the Kotlin output.

feat: convert html to markdown for improved dokka readability

---

settings.gradle.kts
tests/benchmarks/aws-signing-benchmarks/README.md
tests/benchmarks/aws-signing-benchmarks/build.gradle.kts
tests/benchmarks/aws-signing-benchmarks/jvm/src/aws/smithy/kotlin/benchmarks/auth/signing/AwsSignerBenchmark.kt

Addresses #617 
This change adds benchmarks to compare the new default implementation with the classic CRT implementation.

chore: add new AWS signer benchmarks

---

.changes/53fe3bd1-84b5-47b2-8d75-460ab8437dcc.json
runtime/runtime-core/build.gradle.kts
runtime/runtime-core/jvm/src/aws/smithy/kotlin/runtime/content/ByteStreamJVM.kt
runtime/runtime-core/jvm/src/aws/smithy/kotlin/runtime/content/FileContent.kt
runtime/runtime-core/jvm/test/aws/smithy/kotlin/runtime/content/ByteStreamJVMTest.kt

https://github.com/awslabs/aws-sdk-kotlin/issues/530
Add bytestream support for partial file content eg.
```kotlin
val File = // ...
val part0 = file.asByteStream(endInclusive = 255) // implicit start index 0
val part1 = file.asByteStream(256, 511)
val part2 = file.asByteStream(512) // implicit endInclusive index file.length()-1
```

feat: bytestream support for partial file content

---

gradle.properties

N/A
There is a [CVE](https://ossindex.sonatype.org/vulnerability/5dbdb043-212c-4971-9653-d04e1cfc5080?component-type=maven&component-name=org.jsoup.jsoup&utm_source=ossindex-client&utm_medium=integration&utm_content=1.7.0) for `jsoup<=1.14.1`.

chore: upgrade jsoup version to 1.14.3

---

.changes/f7cf3370-ccb2-4e68-91e9-a4e61a06731b.json
runtime/auth/aws-signing-tests/common/src/aws/smithy/kotlin/runtime/auth/awssigning/tests/MiddlewareSigningTestBase.kt
runtime/auth/aws-signing-tests/jvm/src/aws/smithy/kotlin/runtime/auth/awssigning/tests/SigningSuiteTestBaseJVM.kt
runtime/protocol/http-client-engines/http-client-engine-crt/common/src/aws/smithy/kotlin/runtime/http/engine/crt/CrtHttpEngine.kt
runtime/protocol/http-client-engines/http-client-engine-default/build.gradle.kts
runtime/protocol/http-client-engines/http-client-engine-default/jvm/src/aws/smithy/kotlin/runtime/http/engine/DefaultHttpEngineJVM.kt
runtime/protocol/http-client-engines/http-client-engine-default/jvm/src/aws/smithy/kotlin/runtime/http/engine/HttpEngineEventListener.kt
runtime/protocol/http-client-engines/http-client-engine-ktor/common/src/aws/smithy/kotlin/runtime/http/engine/ktor/KtorEngine.kt
runtime/protocol/http-test/common/src/aws/smithy/kotlin/runtime/httptest/RecordingConnection.kt
runtime/protocol/http-test/common/src/aws/smithy/kotlin/runtime/httptest/TestConnection.kt
runtime/protocol/http/common/src/aws/smithy/kotlin/runtime/http/SdkHttpClient.kt
runtime/protocol/http/common/src/aws/smithy/kotlin/runtime/http/engine/HttpClientEngine.kt
runtime/protocol/http/common/src/aws/smithy/kotlin/runtime/http/middleware/Retry.kt
runtime/protocol/http/common/src/aws/smithy/kotlin/runtime/http/operation/HttpOperationContext.kt
runtime/protocol/http/common/src/aws/smithy/kotlin/runtime/http/operation/OperationRequest.kt
runtime/protocol/http/common/src/aws/smithy/kotlin/runtime/http/operation/SdkOperationExecution.kt
runtime/protocol/http/common/test/aws/smithy/kotlin/runtime/http/engine/HttpClientEngineTest.kt
runtime/protocol/http/common/test/aws/smithy/kotlin/runtime/http/middleware/DefaultValidateResponseTest.kt
runtime/protocol/http/common/test/aws/smithy/kotlin/runtime/http/middleware/Md5ChecksumTest.kt
runtime/protocol/http/common/test/aws/smithy/kotlin/runtime/http/middleware/MutateHeadersTest.kt
runtime/protocol/http/common/test/aws/smithy/kotlin/runtime/http/middleware/ResolveEndpointTest.kt
runtime/protocol/http/common/test/aws/smithy/kotlin/runtime/http/middleware/RetryTest.kt
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/retries/RetryStrategy.kt
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/retries/StandardRetryStrategy.kt
runtime/smithy-test/common/src/aws/smithy/kotlin/runtime/smithy/test/HttpRequestTest.kt
runtime/smithy-test/common/src/aws/smithy/kotlin/runtime/smithy/test/HttpResponseTest.kt
runtime/smithy-test/common/test/aws/smithy/kotlin/runtime/smithy/test/HttpRequestTestBuilderTest.kt
runtime/smithy-test/common/test/aws/smithy/kotlin/runtime/smithy/test/HttpResponseTestBuilderTest.kt

N/A
* Implement retry header SEP which propagates `amz-sdk-invocation-id` header with our existing client side SdkRequestId value.
* Implement `okhttp::EventListener` interface and register it with the engine. This logs every event from the engine at trace level. Currently this pulls out the (new) invocation ID header to propagate sdk request ID into the logs for correlation with the rest of the logging messages related to that operation. When we implement #629 we can use the `tags` functionality of an okhttp request to propagate whatever context we want.
* Refactor `HttpClientEngine` interface to take `ExecutionContext`. 

feat(rt): add additional telemetry for HTTP requests

---

.changes/922b32ef-f194-4e5f-9ff2-9eca98246755.json
runtime/utils/common/src/aws/smithy/kotlin/runtime/util/text/Text.kt
runtime/utils/common/test/aws/smithy/kotlin/runtime/util/text/TextTest.kt

Closes aws-sdk-kotlin#619
Two issues with our signer's canonicalization of query string parameters:
* During canonicalization, we decode and reencode query params but don't handle `+` and `%` the way services expect. Namely, we _decode_ `+` to `' '` and then _reencode_ to `%20`. The `+` character shouldn't be handled specially in this case and should not be altered when decoding so that it's (correctly) encoded to `%2B`.
* We also throw an error on query string parameters that contain `%` followed by invalid escape sequences. This is consistent with the RFC detailing URI format but is too inflexible for our E2E test case. We should percent-decode what we can and pass through the rest unmodified.
By submitting this pull request, I confirm that my contribution is made under the terms of the …

fix: correct signing for query parameters containing '+' and '%'

---

build.gradle.kts
gradle.properties
runtime/protocol/http-client-engines/http-client-engine-default/common/src/aws/smithy/kotlin/runtime/http/engine/DefaultHttpEngine.kt
runtime/protocol/http-client-engines/http-client-engine-default/jvm/src/aws/smithy/kotlin/runtime/http/engine/DefaultHttpEngineJVM.kt
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/HttpEngineEventListener.kt
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/OkHttpEngine.kt
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/OkHttpEngineConfig.kt
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/OkHttpUtils.kt
runtime/protocol/http/common/src/aws/smithy/kotlin/runtime/http/HttpBody.kt
runtime/utils/common/src/aws/smithy/kotlin/runtime/util/Annotations.kt
settings.gradle.kts
tests/benchmarks/aws-signing-benchmarks/jvm/src/aws/smithy/kotlin/benchmarks/auth/signing/AwsSignerBenchmark.kt
tests/benchmarks/http-benchmarks/README.md
tests/benchmarks/http-benchmarks/build.gradle.kts
tests/benchmarks/http-benchmarks/jvm/src/aws/smithy/kotlin/benchmarks/http/HttpEngineBenchmarks.kt
tests/benchmarks/http-benchmarks/jvm/src/aws/smithy/kotlin/benchmarks/http/KtorOkHttpEngine.kt

N/A
* Bootstrap a benchmark suite for HTTP client engines. This is a very rough test suite that we can build from.
I'm currently seeing the following two errors when running the benchmarks:
1. 
```
failed to consume body: failed to read all HttpBody bytes from stream: isClosedForRead: false/true; isClosedForWrite: true/true; availableForRead: 0/0: hello    
```
This only happens on the `KtorEngine` and `OkHttpEngine` which both use the same `SdkByteReadChannel` implementation (backed by ktor) whereas the `CRT` engine uses the custom implementation.
2.
```
stopping server                                                                                                                                                         Jun 15, 2022 11:07:11 AM …
```

HTTP Engine Benchmarks

---

.changes/04cb3052-4479-4b00-a08c-f7b5fbe1d59a.json
runtime/protocol/http-client-engines/http-client-engine-ktor/common/src/aws/smithy/kotlin/runtime/http/engine/ktor/KtorEngine.kt
runtime/protocol/http-client-engines/test-suite/common/test/aws/smithy/kotlin/runtime/http/test/DownloadTest.kt
runtime/protocol/http-client-engines/test-suite/jvm/src/aws/smithy/kotlin/runtime/http/test/suite/Downloads.kt

https://github.com/awslabs/aws-sdk-kotlin/issues/638
Fix ktor engine representation of empty http body. Expand test suite to cover this.

fix: expand test coverage of engine implementations to include empty body repr

---

gradle.properties
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/waiters/AcceptorGenerator.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/waiters/AcceptorGeneratorTest.kt

N/A
Upgrade to latest `aws-crt-kotlin` compiled against Kotlin 1.7

chore: upgrade crt-kotlin to 0.6.2

---

.changes/fc4060e3-a826-46dd-a1f7-8fb041c77fd2.json
runtime/serde/common/src/aws/smithy/kotlin/runtime/serde/Serializer.kt
runtime/serde/serde-form-url/common/src/aws/smithy/kotlin/runtime/serde/formurl/FormUrlSerializer.kt
runtime/serde/serde-json/common/src/aws/smithy/kotlin/runtime/serde/json/JsonSerializer.kt
runtime/serde/serde-xml/common/src/aws/smithy/kotlin/runtime/serde/xml/XmlSerializer.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/CodeWriterExt.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/RuntimeTypes.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ShapeValueGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpBindingProtocolGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/DeserializeStructGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/DeserializeUnionGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/JsonParserGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/JsonSerializerGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/SerializeStructGenerator.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpBindingProtocolGeneratorTest.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/SerializeStructGeneratorTest.kt
smithy-kotlin-codegen/src/test/resources/software/amazon/smithy/kotlin/codegen/http-binding-protocol-generator-test.smithy

(https://github.com/awslabs/smithy-kotlin/issues/123)
Wire in codegen for `Document` serde.

feat: add support for smithy document type

---

.changes/5bdddd68-7b25-4785-9a20-03790e330f27.json
.changes/ba998d36-ef93-4b63-8830-18e0f38c3b9a.json
gradle.properties
runtime/utils/common/src/aws/smithy/kotlin/runtime/util/Convenience.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/AbstractCodeWriterExt.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinSymbolProvider.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinWriter.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/RuntimeTypes.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/model/SetRefactorPreprocessor.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/model/knowledge/SerdeIndex.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/GradleGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/UnionGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpBindingProtocolGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/DeserializeUnionGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/waiters/KotlinJmespathExpressionVisitor.kt
smithy-kotlin-codegen/src/main/resources/META-INF/services/software.amazon.smithy.kotlin.codegen.integration.KotlinIntegration
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/core/AbstractCodeWriterTest.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/core/SymbolProviderTest.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/model/SetRefactorPreprocessorTest.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/DeserializeStructGeneratorTest.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/SerializeStructGeneratorTest.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/waiters/KotlinJmespathExpressionVisitorTest.kt

Closes #599 
This change upgrades from Smithy 1.17 to 1.22:
* The biggest change between the versions is the deprecation of `set` shapes and their replacement with `list` shapes annotated with the `@uniqueItems` trait. Accordingly, this PR updates several uses of set-based classes from Smithy and adds an automatic translator to replace legacy `set` shapes in model files with new lists.
* Additionally, `CodeWriter` is deprecated and replaced with `AbstractCodeWriter` and a default `SimpleCodeWriter` implementation.
**Companion PR**: [aws-sdk-kotlin#647](https://github.com/awslabs/aws-sdk-kotlin/pull/647)

chore: upgrade Smithy to 1.22

---

.changes/e1fa257d-73b3-4616-8c39-f32956008124.json
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ServiceGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/StructureGenerator.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ServiceGeneratorTest.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/StructureGeneratorTest.kt

(none)
Move DSL overloads for builder-style invocation of generated operations out of the client interface and into extension methods. This is generally correct since the behavior is a convenience and not a separate function that inheritors need to implement. It has the additional benefit of simplifying unit testing and mocking.
This is a **breaking change** since now these extension methods require a different import than before.
**Companion PR**: [aws-sdk-kotlin#653](https://github.com/awslabs/aws-sdk-kotlin/pull/653)

Feat dsl overloads as ext methods

---

.changes/4d59fd7e-dde7-4816-8485-cc3140a41512.json
smithy-kotlin-codegen/build.gradle.kts
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ClientConfigGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/EnumGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ExceptionBaseClassGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/GradleGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/PaginatorGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ServiceGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/StructureGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/UnionGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/waiters/WaiterGenerator.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ClientConfigGeneratorTest.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/EnumGeneratorTest.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ExceptionGeneratorTest.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/GradleGeneratorTest.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/PaginatorGeneratorTest.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ServiceGeneratorTest.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ShapeValueGeneratorTest.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/StructureGeneratorTest.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/UnionGeneratorTest.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/waiters/ServiceWaitersGeneratorTest.kt
tests/compile/build.gradle.kts
tests/compile/src/test/kotlin/software/amazon/smithy/kotlin/codegen/ApiEvolutionTest.kt
tests/compile/src/test/kotlin/software/amazon/smithy/kotlin/codegen/util/TestUtils.kt

#216 
This change enables [Explicit API mode](https://github.com/Kotlin/KEEP/blob/master/proposals/explicit-api-mode.md) for **smithy-kotlin** codegen. PRing this separately from runtime changes since **a)** there are fewer changes here and **b)** the risk of getting it wrong is slightly higher in codegen so it deserves higher scrutiny.
Companion PR: [aws-sdk-kotlin#657](https://github.com/awslabs/aws-sdk-kotlin/pull/657)

chore: enable explicit API mode for codegen

---

.changes/dc281a10-9a1a-4121-b699-1d0ad8271b58.json
gradle.properties

chore: bump package version to 0.12.4 after broken 0.12.3 release

---

.changes/633e3063-4089-41fe-a7a2-bb742910478c.json
gradle.properties
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/CodegenVisitor.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinSymbolProvider.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/model/ShapeExt.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/EnumGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ShapeValueGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpStringValuesMapSerializer.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/DeserializeStructGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/SerializeStructGenerator.kt

Upgrade to Smithy IDL 2.0:
- Upgrade Smithy dependency to 1.23.0
- Upgrade Smithy Gradle dependency to 0.6.0
- Add `@Suppress("DEPRECATION")` to deprecated classes `EnumTrait` and `BoxTrait`
N/A
To prep for upgrading aws-sdk-kotlin to Smithy 2.0, upgrading Smithy and Smithy Gradle is needed.
Ran `./gradlew clean build check assemble --parallel --no-build-cache --no-daemon` with `local.properties` file:
```text
kotlinWarningsAsErrors=true
```

chore: upgrade Smithy to 1.23.0, upgrade Smithy Gradle to 0.6.0

---

runtime/serde/common/src/aws/smithy/kotlin/runtime/serde/SdkFieldDescriptor.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/model/ShapeExt.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ShapeValueGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpBindingProtocolGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/DeserializeStructGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/SerdeExt.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/SerializeStructGenerator.kt

(none)
Downstream CI is broken in **main** right now due to [an incomplete Smithy 1.23 upgrade](https://github.com/awslabs/smithy-kotlin/commit/fa24af948f356b52e3d42a62b386cf0e18aa86da). This change adds support for the new `enum` and `intEnum` shapes that appear in updated Smithy protocol tests.
**Companion PR**: [aws-sdk-kotlin#684](https://github.com/awslabs/aws-sdk-kotlin/pull/684)

fix: add missing codegen support for Smithy 1.23 upgrade

---

.changes/48905e3f-f57e-4265-ad34-98c65ec4bb46.json
gradle.properties

Closes [aws-crt-kotlin#55](https://github.com/awslabs/aws-crt-kotlin/issues/55)
Upgrades the **aws-crt-kotlin** dependency get the latest version of CRT and the fix for the Mac dlopen issue.
**Companion PRs**: [aws-crt-kotlin#56](https://github.com/awslabs/aws-crt-kotlin/pull/56), [aws-sdk-kotlin#682](https://github.com/awslabs/aws-sdk-kotlin/pull/682)

fix: upgrade aws-crt-kotlin dependency to fix Mac dlopen issue

---

gradle.properties

(none)
Sync with latest version of **aws-crt-kotlin**, 0.6.4.

chore: upgrade aws-crt-kotlin to version 0.6.4

---

.changes/63e845b0-937d-4952-b416-b9ab6d9de17f.json
gradle.properties
runtime/protocol/http-client-engines/http-client-engine-crt/common/src/aws/smithy/kotlin/runtime/http/engine/crt/RequestUtil.kt
runtime/protocol/http-client-engines/http-client-engine-ktor/common/src/aws/smithy/kotlin/runtime/http/engine/ktor/KtorRequestAdapter.kt
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/ByteChannelRequestBody.kt
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/test/aws/smithy/kotlin/runtime/http/engine/okhttp/ByteChannelRequestBodyTest.kt
runtime/protocol/http/common/src/aws/smithy/kotlin/runtime/http/HttpBody.kt

https://github.com/awslabs/aws-sdk-kotlin/issues/543
* Expose a flag to mark an HTTP request body as full duplex. This signals the underlying engine that the exchange is expected to be fully asynchronous with request and response bodies interleaved. This was chosen because at least two of our engines (CRT and okhttp) require different handling of the request body when streaming this way. This capability is only needed by event stream operations right now and should not be `true` for any other request body
* This PR only adds support for the okhttp engine and will fail at runtime if you try to use a full duplex request for any other engine. I believe the CRT has added support and exposed knobs for this but we have more work to got figure out what that looks like, thread it through …

feat(rt): add full duplex request body support for okhttp engine

---

.changes/2706bf03-43a0-4f21-93a9-4d7be027d554.json
runtime/protocol/http/common/src/aws/smithy/kotlin/runtime/http/operation/SdkHttpOperation.kt
runtime/protocol/http/common/src/aws/smithy/kotlin/runtime/http/response/HttpCall.kt
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/client/ExecutionContext.kt

https://github.com/awslabs/aws-sdk-kotlin/issues/543
Most background work is related to HTTP engine but there are cases where clients need a way to launch background work related to request processing (e.g. event streams). This change makes ExecutionContext
implement CoroutineScope for background work to be launched into. This scope is cancelled and joined when an `SdkHttpOperation` is done executing. 
The `HttpCall` context has also been updated and is joined explicitly now. This should expose coroutine leaks much faster if they ever happen again since the operation will fail to complete with a response and we'll hear about it from customers much quicker (not to mention it will be more obvious what is happening). 
By submitting this pull request, I confirm that my contribution is made …

refactor(rt): make ExecutionContext implement CoroutineScope

---

.changes/2310b190-0074-4d42-89c4-8229b0197609.json
runtime/runtime-core/jvm/src/aws/smithy/kotlin/runtime/content/ByteStreamJVM.kt
runtime/runtime-core/jvm/test/aws/smithy/kotlin/runtime/content/ByteStreamJVMTest.kt

Closes #678 
We were calculating `endInclusive` incorrectly downstream of `Path.asByteStream` when no explicit value was passed. This change explicitly calculates file length if none is provided and prohibits `endInclusive == -1` in `File.asByteStream`.

fix: correctly calculate file lengths on byte streams from paths

---

.changes/69672ec4-a822-465c-80ac-2656dd3ff334.json
gradle.properties
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinSymbolProvider.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/StructureGenerator.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/core/SymbolProviderTest.kt

Change the way we compute the nullability of members. Before we were only looking at the box trait in the target type and ignoring the trait on the member itself. See for instance the test `can read box trait from member` which has the following model:
```
namespace com.test
structure MyStruct {
@box
foo: MyFoo
}
long MyFoo
```
The code was incorrectly assuming that the foo member was not nullable. This change accounts for this by using the `NullableIndex` which correctly computes whether or not the member or the target type are nullable. 
**NOTE** This is a draft pull request as it depends on the pending release of smithy 1.25.0 scheduled for tomorrow, but sending along to get a head start on the review of the changes.
By submitting this pull request, I confirm that my contribution is …

fix: properly check if a member can be nullable

---

.changes/0c737e4d-adb6-45f4-95d3-7123f3455171.json
runtime/crt-util/common/src/aws/smithy/kotlin/runtime/crt/ReadChannelBodyStream.kt
runtime/protocol/http-client-engines/test-suite/common/test/aws/smithy/kotlin/runtime/http/test/UploadTest.kt

(none)
Fix the CRT streaming delay bug by adding a poller.
Mutually exclusive with #701 and #703.

Fix crt stream leak via watchdog

---

.changes/0d2cc7ea-39dc-11ed-a261-0242ac120002.json
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ClientConfigProperty.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ClientConfigGeneratorTest.kt

https://github.com/awslabs/aws-sdk-kotlin/issues/486
This change is being submitted alongside another in [aws-kotlin-sdk](https://github.com/awslabs/aws-sdk-kotlin/pull/702). A mutable RetryStrategy is required for user configurability.

feat(codegen): change property type of RetryStrategy to allow mutability

---

CODEOWNERS

(none)
Update the code owners of this repository to [**aws-sdk-kotlin-sde**](https://github.com/orgs/awslabs/teams/aws-sdk-kotlin-sde/members) instead of [**aws-sdk-kotlin-admins**](https://github.com/orgs/awslabs/teams/aws-sdk-kotlin-admins/members).

chore: update CODEOWNERS to SDE group instead of admins

---

.changes/3952237f-4d07-4e81-ac73-73fb935bfd43.json
runtime/protocol/http/common/src/aws/smithy/kotlin/runtime/http/HttpBody.kt
runtime/protocol/http/common/test/aws/smithy/kotlin/runtime/http/HttpBodyTest.kt
runtime/protocol/http/common/test/aws/smithy/kotlin/runtime/http/testutils/MockByteReadChannel.kt
runtime/protocol/http/jvm/test/aws/smithy/kotlin/runtime/http/testutils/MockByteReadChannelJVM.kt

Closes [aws-sdk-kotlin#681](https://github.com/awslabs/aws-sdk-kotlin/issues/681)
This PR updates the check used to determine if an HTTP body has been fully read. Previously, we only checked `isClosedForRead` which is sometimes inaccurate based on timing. To be safer, we'll check both `isClosedForRead` and `isClosedForWrite`/`availableForRead` since either condition effectively indicates that the entire body has been read.

fix: correct check for channel closure when reading all bytes of an HttpBody

---

.changes/2ae86281-8a85-4470-bb85-618d857cb21b.json
build.gradle.kts
gradle.properties

[aws-sdk-kotlin#715](https://github.com/awslabs/aws-sdk-kotlin/issues/715)
* Temporarily works around [dokka#2679](https://github.com/Kotlin/dokka/issues/2679) by enabling non-hierarchical project compatibility mode
* Bumps **aws-crt-kotlin** version to pick up similar fix in dependent project
* Configures flatter submodule directory tree in generated documentation
**Companion PRs**: [aws-crt-kotlin#59](https://github.com/awslabs/aws-crt-kotlin/pull/59) & [aws-sdk-kotlin#716](https://github.com/awslabs/aws-sdk-kotlin/pull/716)

fix: enable intra-repo links in API ref docs

---

.changes/cccb2f1d-b607-4b8d-9f26-5ff172fffa1d.json
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/DeserializeStructGenerator.kt

#714 
Check both member shape and target shape for `timestampFormat` override. This is tested by new protocol tests proposed in [smithy#1440](https://github.com/awslabs/smithy/pull/1440).

Fix timestamp format codegen

---

.changes/3c662a11-98c2-48cc-8cf5-ca0b293db1f9.json
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/time/Instant.kt
runtime/runtime-core/jvm/src/aws/smithy/kotlin/runtime/time/InstantJVM.kt

Add `Instant.MIN` and `Instant.MAX` which represent the minimum and maximum possible values of an Instant.
N/A
This is going to be used by a twin PR in aws-sdk-kotlin to set the expiration time of Credentials when no expiration data is received. When no expiration data is received, we should treat the Credentials as non-expiring. `Instant.MAX` will be used to ensure these Credentials are not refreshed at any point in their use.

feat(rt): add `MIN`/`MAX` values to `Instant`

---

.changes/490f40f2-97e1-47f9-b53c-d0740e394814.json
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ClientConfigGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ClientConfigProperty.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ClientConfigGeneratorTest.kt

Adds an `order` Integer parameter to ClientConfigProperty which is used to order configuration dependencies.
[awslabs/aws-sdk-kotlin/711](https://github.com/awslabs/aws-sdk-kotlin/issues/711)
This was added in order to support passing of certain client configuration properties into other client configuration properties. For example, client configurations can specify an HttpEngine to be used for all requests, which must be passed into the DefaultChainCredentialsProvider which is also a client configuration. This introduces a dependency between client configuration properties which I addressed with the `order` parameter.
When rendering the client configuration properties, we will sort them by `order` (new behavior) and then alphabetically by property name (as it's done today).  This will …

feat(codegen): add `order` parameter to ClientConfigProperty to be used for ordering configuration dependencies

---

.changes/841987e7-c68c-4ff6-8426-f7bf51373d79.json
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/ByteChannelRequestBody.kt
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/test/aws/smithy/kotlin/runtime/http/engine/okhttp/ByteChannelRequestBodyTest.kt
runtime/protocol/http-client-engines/test-suite/common/test/aws/smithy/kotlin/runtime/http/test/UploadTest.kt

fixes https://github.com/awslabs/aws-sdk-kotlin/issues/733
Wrap all exceptions from our implementation of `okhttp3.RequestBody#writeTo(...)` as an `IOException`.
See https://github.com/awslabs/aws-sdk-kotlin/issues/733#issuecomment-1290925795 for more detailed description.

fix(rt): okhttp engine crashing on Android when coroutine is cancelled while uploading request body

---

.changes/8b692602-06c4-4c97-b554-a08cac97e1ea.json
gradle.properties
runtime/serde/serde-form-url/common/src/aws/smithy/kotlin/runtime/serde/formurl/FormUrlSerializer.kt
runtime/serde/serde-form-url/common/test/aws/smithy/kotlin/runtime/serde/formurl/FormUrlSerializerTest.kt

Correct `FormUrl` serialization for empty lists.
An empty list should be serialized as
`<ListSerialName>=`
rather than being omitted.

fix: upgrade smithy and correct formurl serialization of empty lists

---

.changes/3146b641-ffcb-4043-9fdf-1f8b3b324113.json
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/ByteChannelRequestBody.kt

https://github.com/awslabs/aws-sdk-kotlin/issues/733
The previous fix applied in https://github.com/awslabs/smithy-kotlin/pull/723 was not insufficient. This change wraps the entire `writeTo` method in a `try/catch` block and surfaces everything as `IOException` from there. This change was tested locally by Amplify to verify the behavior.

fix(rt): second fix for okhttp engine crashing on Android when coroutine is cancelled uploading request body

---

.changes/156447f6-0f80-4fde-a38d-6b92260432b8.json
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/OkHttpUtils.kt
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/test/aws/smithy/kotlin/runtime/http/engine/okhttp/OkHttpResponseTest.kt

fixes https://github.com/awslabs/aws-sdk-kotlin/issues/753
Wrap response body handling with `runCatching` to prevent the exception from reaching the default [CoroutineExceptionHandler](https://kotlinlang.org/docs/exception-handling.html#coroutineexceptionhandler) (which on JVM will print a stacktrace but on Android it will crash the app). Exception is propagated through the channel which was the original intent.

fix(rt): handle exceptions in background okhttp response body coroutine

---

.changes/a59196ef-583c-45b2-9f7f-3d8329902be0.json
settings.gradle.kts

Add the local maven to the list of repositories that allows to test changes to Smithy libraries, without this the build fails with something like:
```
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':tests:benchmarks:serde-benchmarks'.
> Could not resolve all files for configuration ':tests:benchmarks:serde-benchmarks:classpath'.
> Could not find software.amazon.smithy:smithy-cli:1.27.0-SNAPSHOT.
Searched in the following locations:
- https://repo.maven.apache.org/maven2/software/amazon/smithy/smithy-cli/1.27.0-SNAPSHOT/maven-metadata.xml
- https://repo.maven.apache.org/maven2/software/amazon/smithy/smithy-cli/1.27.0-SNAPSHOT/smithy-cli-1.27.0-SNAPSHOT.pom
- https://plugins.gradle.org/m2/software/amazon/smithy/smithy-cli/1.27.0-SNAPSHOT/m …
```

chore(codegen): allow using maven local for to test Smithy changes

---

docs/design/endpoints.md
runtime/protocol/http/common/src/aws/smithy/kotlin/runtime/http/endpoints/Endpoint.kt
runtime/protocol/http/common/src/aws/smithy/kotlin/runtime/http/endpoints/EndpointProvider.kt
runtime/protocol/http/common/src/aws/smithy/kotlin/runtime/http/endpoints/EndpointResolver.kt
runtime/protocol/http/common/src/aws/smithy/kotlin/runtime/http/middleware/ResolveEndpoint.kt
runtime/protocol/http/common/test/aws/smithy/kotlin/runtime/http/middleware/ResolveEndpointTest.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/CodegenVisitor.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/RuntimeTypes.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/model/RulesEngineExt.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/model/ShapeExt.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/model/SymbolExt.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ClientConfigGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ClientConfigProperty.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/endpoints/DefaultEndpointProviderGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/endpoints/EndpointParametersGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/endpoints/EndpointProviderGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/endpoints/ResolveEndpointMiddlewareGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpBindingProtocolGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpProtocolTestGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpProtocolUnitTestGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/ProtocolGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/ResolveEndpointMiddleware.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ClientConfigGeneratorTest.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ExceptionGeneratorTest.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/endpoints/EndpointParametersGeneratorTest.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpBindingProtocolGeneratorTest.kt
tests/codegen/paginator-tests/build.gradle.kts
tests/codegen/paginator-tests/src/main/kotlin/com/test/endpoints/EndpointProvider.kt
tests/codegen/waiter-tests/build.gradle.kts
tests/codegen/waiter-tests/src/main/kotlin/com/test/endpoints/EndpointProvider.kt

Implement middleware and endpoint parameter binding generators to call endpoint providers per-operation at runtime.

feat: endpoints2: endpoint provider middleware and final integration

---

.changes/5529014d-3b3e-49de-b32f-3d65d0662555.json
runtime/protocol/http-client-engines/http-client-engine-crt/common/src/aws/smithy/kotlin/runtime/http/engine/crt/CrtHttpEngineConfig.kt

Found while reproducing [aws-sdk-kotlin#758](https://github.com/awslabs/aws-sdk-kotlin/issues/758)
The `CrtHttpEngineConfig` class has the `@InternalApi` marker applied to it, meaning users have no way to reference or build a CRT engine configuration without opting in.

fix: remove erroneous @InternalApi marker on CRT HTTP engine config class

---

.changes/2032f172-904d-474b-b554-4d7fa04e160c.json
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/lang/KotlinTypes.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/DeserializeStructGenerator.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/DeserializeStructGeneratorTest.kt

(none)
After syncing AWS models, a new structure was found containing a list of `Document` shapes. Our deserialization code didn't properly handle this, leading to a build failure.

fix: correctly deserialize lists of documents

---

.changes/0b232d1e-06b5-4557-a5f5-90245238f2ab.json
runtime/tracing/tracing-core/build.gradle.kts
runtime/tracing/tracing-core/common/src/aws/smithy/kotlin/runtime/tracing/CoroutineContextUtils.kt
runtime/tracing/tracing-core/common/test/aws/smithy/kotlin/runtime/tracing/TraceSpanCoroutineUtilsTest.kt
runtime/tracing/tracing-core/common/test/aws/smithy/kotlin/runtime/tracing/TraceSpanTest.kt

fixes https://github.com/awslabs/aws-sdk-kotlin/issues/789
Allow a root span to be created when an existing span is present in the current coroutine context as long as the root span has no parent. An existing span and a root span with a parent is still not allowed because it would represent an illegal state (two different span lineages). 

fix(rt): allow root spans to inherit their parent from the context when not already set

---

docs/design/interceptors.md

https://github.com/awslabs/smithy-kotlin/issues/122
Adds design doc for interceptors

docs: add design for operation interceptors

---

.changes/f0ec11be-3875-498a-8e33-74c49416f3b8.json
gradle.properties
runtime/protocol/http-client-engines/http-client-engine-crt/common/src/aws/smithy/kotlin/runtime/http/engine/crt/CrtHttpEngine.kt
runtime/protocol/http-client-engines/http-client-engine-crt/common/src/aws/smithy/kotlin/runtime/http/engine/crt/RequestUtil.kt
runtime/protocol/http-client-engines/http-client-engine-crt/common/test/aws/smithy/kotlin/runtime/http/engine/crt/RequestConversionTest.kt
runtime/protocol/http-client-engines/http-client-engine-crt/common/test/aws/smithy/kotlin/runtime/http/engine/crt/SdkStreamResponseHandlerTest.kt
runtime/protocol/http-client-engines/http-client-engine-crt/jvm/test/aws/smithy/kotlin/runtime/http/engine/crt/SendChunkedBodyTest.kt

CRT requires `aws-chunked` requests to use a specific API instead of a normal streaming request body. This PR adds a special-case to the CRT engine, which will use this new API instead of sending an `aws-chunked` body.
https://github.com/awslabs/smithy-kotlin/issues/759
Currently `aws-chunked` requests do not work when using the CrtHttpEngine.

fix(rt): add special-casing for CrtHttpEngine `aws-chunked` requests

---

.changes/4c3348fe-3e51-411b-98e6-6ac2e6a2bba0.json
runtime/hashing/common/src/aws/smithy/kotlin/runtime/hashing/Crc32c.kt
runtime/hashing/common/test/aws/smithy/kotlin/runtime/hashing/Crc32cTest.kt

During flexible checksums testing, a bug was discovered in the CRC32c hash function when trying to hash more than 7 bytes at a time. The elements were being cast `toByte()`, truncating information and leading to incorrect output. 
N/A
This change ensures that CRC32C outputs the correct value when `update()` is called with a `length` greater than 7.

fix(rt): CRC32C incorrect result on inputs longer than 7 bytes

---

runtime/hashing/common/src/aws/smithy/kotlin/runtime/hashing/Crc32c.kt
runtime/hashing/common/test/aws/smithy/kotlin/runtime/hashing/Crc32cTest.kt

N/A
A [previous PR](https://github.com/awslabs/smithy-kotlin/pull/766) was merged to fix a bug in the CRC32C implementation. When inputs longer than 7 bytes were used, the algorithm produced incorrect results due to incorrectly casting elements to `Byte`. 
This was fixed in the previous PR, but some `toByte` casts were overlooked. These are causing an IndexOutOfBoundsException only when negative bytes are provided as input. Example:
```kotlin
val byte: Byte = -1 
byte and 0xff.toByte() // -1
byte.toInt() and 0xff // 255, the expected output
```
This PR fixes the issue by removing all `.toByte()` casts. It also removes an unused function `update(b: Int)` from the implementation.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …

fix(rt): Crc32C incorrect results on negative inputs longer than 7 bytes

---

.changes/9ab15fa5-76b7-4bf0-9931-eaa50fd57a19.json
settings.gradle.kts
smithy-kotlin-codegen-testutils/build.gradle.kts
smithy-kotlin-codegen-testutils/src/main/kotlin/software/amazon/smithy/kotlin/codegen/test/CodegenTestUtils.kt
smithy-kotlin-codegen-testutils/src/main/kotlin/software/amazon/smithy/kotlin/codegen/test/LangTestUtils.kt
smithy-kotlin-codegen-testutils/src/main/kotlin/software/amazon/smithy/kotlin/codegen/test/MiscTestUtils.kt
smithy-kotlin-codegen-testutils/src/main/kotlin/software/amazon/smithy/kotlin/codegen/test/ModelTestUtils.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/KotlinSettings.kt

(none)
It was recently observed that our **smithy-kotlin-codegen** package takes runtime dependencies on JUnit and other test packages because it provides test utilities for consuming code generators. That's not ideal so this PR creates a new **smithy-kotlin-codegen-testutils** package and moves the test utilities there.
**Companion PR**: [aws-sdk-kotlin#794](https://github.com/awslabs/aws-sdk-kotlin/pull/794)

chore: move codegen test utilities to new smithy-kotlin-codegen-testutils package

---

.changes/af027b16-c6f7-4885-9835-1a75315860cf.json
runtime/auth/aws-signing-common/common/src/aws/smithy/kotlin/runtime/auth/awssigning/HashSpecification.kt
runtime/auth/aws-signing-common/common/src/aws/smithy/kotlin/runtime/auth/awssigning/internal/AwsChunkedReader.kt
runtime/auth/aws-signing-common/common/src/aws/smithy/kotlin/runtime/auth/awssigning/internal/AwsChunkedUtil.kt
runtime/auth/aws-signing-common/common/src/aws/smithy/kotlin/runtime/auth/awssigning/middleware/AwsSigningMiddleware.kt
runtime/auth/aws-signing-tests/common/src/aws/smithy/kotlin/runtime/auth/awssigning/tests/AwsChunkedTestBase.kt

Adds support for making unsigned requests using `aws-chunked`.
Users can specify an unsigned request by setting the `isUnsignedPayload` field when configuring `AwsSigningMiddleware`.
N/A
This change is required to enable sending unsigned requests using aws-chunked. This is particularly useful for flexible checksums because users may want to make unsigned requests but still provide a checksum as a trailing header. 

feat(rt): unsigned `aws-chunked`

---

docs/design/interceptors.md
runtime/protocol/http/common/src/aws/smithy/kotlin/runtime/http/interceptors/InterceptorExecutor.kt
runtime/protocol/http/common/src/aws/smithy/kotlin/runtime/http/operation/SdkHttpOperation.kt
runtime/protocol/http/common/test/aws/smithy/kotlin/runtime/http/operation/HttpInterceptorTest.kt
runtime/protocol/http/common/test/aws/smithy/kotlin/runtime/http/operation/HttpInterceptorTypeValidationTest.kt
runtime/protocol/http/common/test/aws/smithy/kotlin/runtime/http/operation/TracingTestInterceptor.kt
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/client/Interceptor.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/RuntimeTypes.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/lang/KotlinTypes.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ClientConfigGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ClientConfigProperty.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/endpoints/ResolveEndpointMiddlewareGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpProtocolClientGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/ProtocolMiddleware.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/ResolveEndpointMiddleware.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ClientConfigGeneratorTest.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpProtocolClientGeneratorTest.kt

https://github.com/awslabs/smithy-kotlin/issues/122
* Refactor modify hooks to be `suspend`
* Add interceptors to client config
* Refactor endpoint resolver middleware to implement `HttpInterceptor`.
* This is our first use case of "internal" interceptors. Everything other customization/default feature is implemented as a middleware. This refactor came about because the endpoint resolver needs the _final_ version of the operation input. The way interceptors are structured the `initialize` middleware phase comes _before_ `Interceptor.modifyBeforeSerialization`. They are effectively the same phase but the ordering means that `initialize` middleware cannot ever depend on the input type during this phase since it won't necessarily be the final value. Refactoring to make use of …

feat: interceptor config

---

.changes/0cc34a91-f764-49d8-b24e-b170973e1f9d.json
runtime/io/jvm/src/aws/smithy/kotlin/runtime/io/RandomAccessFileSource.kt
runtime/io/jvm/test/aws/smithy/kotlin/runtime/io/FileSourceTest.kt

Closes #781 
This change makes file opening in `RandomAccessFileSource` lazy to prevent file handle exhaustion in highly-concurrent scenarios. It also defers all verification of file "correctness" (e.g., file exists, range is valid, etc.) until the file is opened. This is desirable because a long time may elapse between the instantiation of a `RandomAccessFileSource` and the time it's actually used, during which the file may have changed or been deleted/created.

fix: lazily open random access files

---

.changes/6ef995dd-8bce-411f-84df-7790179d5ffa.json
runtime/tracing/tracing-core/common/src/aws/smithy/kotlin/runtime/tracing/LoggingTraceProbe.kt

Closes #784 
This change adds correct handling of exceptions in message events in the `LoggingTraceProbe`.

fix: include exceptions in logging from trace probes

---

.changes/1e1425f8-c911-4d42-a54f-f2330e5cbfff.json
gradle.properties
runtime/tracing/tracing-core/common/src/aws/smithy/kotlin/runtime/tracing/LoggingTraceProbe.kt

(none)
#785 mistakenly started logging `null` on all trace events where no exception was present. This change fixes that by specifically detecting whether an exception is present and dispatching to the correct logger method (i.e., the overload with or without an exception).

fix: stop logging "null" when exceptions are not present in trace events

---

.changes/f20a2e6c-7e63-4fa5-9be4-311e7b56869f.json
gradle.properties
runtime/protocol/http-client-engines/http-client-engine-crt/common/src/aws/smithy/kotlin/runtime/http/engine/crt/CrtHttpEngine.kt
runtime/protocol/http-client-engines/http-client-engine-crt/common/src/aws/smithy/kotlin/runtime/http/engine/crt/SdkStreamResponseHandler.kt
runtime/protocol/http-client-engines/http-client-engine-crt/common/test/aws/smithy/kotlin/runtime/http/engine/crt/SdkStreamResponseHandlerTest.kt

(none)
Adds additional tracing to CRT engine for tracking connections.
**Companion PR**: [aws-crt-kotlin#63](https://github.com/awslabs/aws-crt-kotlin/pull/63)

feat: add additional connection tracing for CRT engine

---

tests/codegen/paginator-tests/build.gradle.kts
tests/codegen/waiter-tests/build.gradle.kts

(none)
Adding a new **smithy-client** package interfered with **smithy-cli** classpath detection [because of string similarity](https://github.com/awslabs/smithy-gradle-plugin/blob/91845e8e0ae7c033e088197e6e15e176c458551b/src/main/java/software/amazon/smithy/gradle/SmithyUtils.java#L244). Developers attempting to build the **paginator-tests** project may see the following error:
```
> Task :tests:codegen:paginator-tests:smithyValidate FAILED
Running smithy validate
software.amazon.smithy.cli.Cli
```
<details>
<summary>Additional details</summary>
Running Gradle with additional logging (e.g., `./gradlew :tests:codegen:paginator-tests:build --info`) produces a more verbose and helpful error
```
> Task :tests:codegen:paginator-tests:smithyValidate FAILED
Caching disabled for task …
```

fix: correct codegen tests' build config to correctly pull in smithy-cli

---

.changes/73e8719a-3ed4-4316-a1a6-d673f1c85282.json
.changes/f71de744-44c0-4404-8d93-04ecda57650b.json
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/OkHttpEngine.kt
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/OkHttpEngineConfig.kt

(none)
A few connections config-related changes for OkHttp:
* Make `maxConnections` actually do something by setting up a custom `Dispatcher` instead of using it for the connection pool's idle count
* Add a new `maxConnectionsPerHost` parameter to allow greater throughput to a single endpoint

feat: rework max connections for OkHttp engine

---

.changes/55bff483-d8ae-4872-9d64-6187c28ba923.json
gradle.properties
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/io/SdkSource.kt
runtime/runtime-core/common/test/aws/smithy/kotlin/runtime/io/SdkBufferedSourceTest.kt
runtime/runtime-core/jvm/src/aws/smithy/kotlin/runtime/io/SdkSourceJVM.kt

This PR adds a `readFully` extension method to `SdkSource`, which is used to read an exact amount of bytes
Helps solve https://github.com/awslabs/aws-sdk-kotlin/issues/836
This change is required because `SdkSource` has no method to read an exact amount of bytes. Before this PR, users of `SdkSource` must use `read` in a loop to ensure they read the number of bytes they expected. When this loop is not used it could result in reading fewer bytes than expected and this unchecked behavior could cause issues.

feat: Add `readFully` extension method to `SdkSource` which reads an exact amount of bytes

---

.changes/fbd99a2c-dd01-4b42-8c9a-55d2bf8e42fe.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/RuntimeTypes.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ServiceClientConfigGenerator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/util/ConfigProperty.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/util/RuntimeConfigProperty.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ServiceClientConfigGeneratorTest.kt
runtime/smithy-client/common/src/aws/smithy/kotlin/runtime/client/SdkClientConfig.kt

(none)
This change adds:
* Retry policy configuration to service clients, enabling users to customize their own exception handling in existing retry logic.
* Merging of config properties by name during service client codegen. This enables _replacing_ an existing config property (like retry policy) with a new property that changes some values (e.g., the default).
**Companion PR**: [aws-sdk-kotlin#838](https://github.com/awslabs/aws-sdk-kotlin/pull/838)

feat: add configurable retry policy to clients

---

.changes/8f1ff251-7fed-4543-a077-51b2fe0aa684.json
codegen/smithy-kotlin-codegen-testutils/src/main/kotlin/software/amazon/smithy/kotlin/codegen/test/ModelTestUtils.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/RuntimeTypes.kt
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/OkHttpEngine.kt
runtime/protocol/http-client/common/src/aws/smithy/kotlin/runtime/http/interceptors/ContinueInterceptor.kt
runtime/protocol/http-client/common/test/aws/smithy/kotlin/runtime/http/interceptors/ContinueInterceptorTest.kt

Prerequisite of [aws-sdk-kotlin#839](https://github.com/awslabs/aws-sdk-kotlin/issues/839)
This change creates a new interceptor which will add `Expect: 100-continue` headers to HTTP requests at a specified length threshold.
Also makes a few changes in **ModelTestUtils.kt** to support testing of companion PR.
**Companion PR**: [aws-sdk-kotlin#845](https://github.com/awslabs/aws-sdk-kotlin/pull/845)

feat: continue header

---

.changes/9e04fd2c-136d-490b-9ecf-d6072a6f34c1.json
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/retries/delay/StandardRetryTokenBucket.kt
runtime/runtime-core/common/test/aws/smithy/kotlin/runtime/retries/delay/StandardRetryTokenBucketTest.kt

Closes #805 
As noted in #805 the retry token bucket calculation is susceptible to changes in system time. Replace the `Clock` implementation with a Kotlin `TimeSource.Monotonic`, which offers intra-moment comparison capable of withstanding system time changes.

fix: correct token bucket delays when experiencing system time jumps

---

runtime/runtime-core/api/runtime-core.api

(none)
#810 changed the API signature for the public constructor `StandardRetryTokenBucket`. It was introduced on a separate branch from the change that added API compatibility verification, #808, and so did not fail compatibility checks in PR. The push to **main** occurred after API compatibility verification was enabled and wasn't blocked on merging because no overlapping files were touched.

fix: update runtime-core API manifest after API-incompatible change that wasn't caught by CI

---

.changes/d4ba7f85-24f3-4925-8bb4-25020f294b9a.json
runtime/auth/aws-signing-default/common/src/aws/smithy/kotlin/runtime/auth/awssigning/Canonicalizer.kt
runtime/auth/aws-signing-default/common/test/aws/smithy/kotlin/runtime/auth/awssigning/DefaultCanonicalizerTest.kt

Closes [aws-sdk-kotlin#862](https://github.com/awslabs/aws-sdk-kotlin/issues/862)
Recent changes #802 and [aws-sdk-kotlin#845](https://github.com/awslabs/aws-sdk-kotlin/pull/845) enabled sending the `Expect: 100-continue` header on S3 PUT requests over 2MB (by default). The `Expect` header is not meant to be signed and causes a problem when using S3 with Transfer Acceleration enabled. (It is unknown why this doesn't also cause a problem when using the default S3 configuration.)
This change exempts the `Expect` header from signature calculation.

fix: don't sign Expect header in SigV4

---

.changes/2d4548fd-a1ed-4a4e-8798-18d5726aee0c.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ServiceClientConfigGenerator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ServiceClientGenerator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpProtocolClientGenerator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/util/RuntimeConfigProperty.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ServiceClientConfigGeneratorTest.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ServiceClientGeneratorTest.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpProtocolClientGeneratorTest.kt
runtime/auth/aws-signing-tests/common/src/aws/smithy/kotlin/runtime/auth/awssigning/tests/MiddlewareSigningTestBase.kt
runtime/auth/aws-signing-tests/jvm/src/aws/smithy/kotlin/runtime/auth/awssigning/tests/SigningSuiteTestBaseJVM.kt
runtime/protocol/aws-json-protocols/common/test/aws/smithy/kotlin/runtime/awsprotocol/json/AwsJsonProtocolTest.kt
runtime/protocol/http-client/api/http-client.api
runtime/protocol/http-client/common/src/aws/smithy/kotlin/runtime/http/operation/HttpOperationContext.kt
runtime/protocol/http-client/common/test/aws/smithy/kotlin/runtime/http/interceptors/FlexibleChecksumsResponseInterceptorTest.kt
runtime/protocol/http-client/common/test/aws/smithy/kotlin/runtime/http/operation/HttpOperationContextTest.kt
runtime/protocol/http-client/common/test/aws/smithy/kotlin/runtime/http/operation/TestOperation.kt
runtime/smithy-client/api/smithy-client.api
runtime/smithy-client/common/src/aws/smithy/kotlin/runtime/client/SdkClient.kt
runtime/smithy-client/common/src/aws/smithy/kotlin/runtime/client/SdkClientConfig.kt
runtime/smithy-client/common/src/aws/smithy/kotlin/runtime/client/SdkClientOption.kt

Add configurable client name that is passed to the tracer by default.
Supports https://github.com/awslabs/aws-sdk-kotlin/pull/854

feat: add reader-friendly client name to SDK config

---

.changes/f3d93638-bc80-4e52-88fa-4c73a093f9bc.json
runtime/auth/aws-signing-common/common/src/aws/smithy/kotlin/runtime/auth/awssigning/Presigner.kt

Presigned URLs are being incorrectly signed with `serviceId` instead of `signingName` 
https://github.com/awslabs/aws-sdk-kotlin/issues/868
We are currently using the service's `serviceId` for the signing context, but this should actually be the `signingName`. For example, S3's `serviceId` is "S3" but the `signingName` is "s3". 
This leads to a signature mismatch / other errors depending on how signature mismatch is handled on the service-side.
Currently the issue only affects presigned URLs generated from a [presigned config object](https://github.com/awslabs/aws-sdk-kotlin/blob/main/codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/PresignerGenerator.kt#L360), not [a client config](https://github.com/awslabs/aws-sdk-kotlin/blob/main/codegen/smithy-aws-kotlin-codege …

fix: use service's `signingName` instead of `serviceId` for presigning

---

.changes/2d229b1e-7d3c-4d89-8e5c-030d3baf5dae.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/RuntimeTypes.kt
runtime/protocol/aws-protocol-core/api/aws-protocol-core.api
runtime/protocol/aws-protocol-core/common/src/aws/smithy/kotlin/runtime/awsprotocol/AwsQueryCompatibleErrorDetails.kt
runtime/protocol/aws-protocol-core/common/test/AwsQueryCompatibleErrorDetailsTest.kt

Add `aws-protocol-core` support for parsing aws-Query compatible errors.
Consumed by https://github.com/awslabs/aws-sdk-kotlin/pull/880.

feat: add code support for awsQuery-compatible error responses

---

.changes/ef39e9b0-b8e5-4885-93c9-15ddca89343e.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/CodegenVisitor.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinSymbolProvider.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/Naming.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/RuntimeTypes.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/model/ShapeExt.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/EnumGenerator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ShapeValueGenerator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpBindingProtocolGenerator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpStringValuesMapSerializer.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/DeserializeStructGenerator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/SerializeStructGenerator.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinWriterTest.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/core/NamingTest.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/core/SymbolProviderTest.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/EnumGeneratorTest.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/endpoints/DefaultEndpointProviderGeneratorTest.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/DeserializeStructGeneratorTest.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/SerializeStructGeneratorTest.kt
gradle.properties

Closes #752
* Add smithy `intEnum` support (codegen + all serde/binding points)
* Modernize `EnumGenerator` codegen
* Upgrade smithy to pull in new protocol tests, which triggered a few incidental changes:
* update test endpoint ruleset to pass new, more-strict validation
* `ShapeValueGenerator` (protocol tests)
* handle fractional values in timestamps
* ensure list member symbols are imported

feat: add intEnum support

---

.changes/85c91e25-fbc9-4416-a8bc-54991580a802.json
runtime/protocol/http-client-engines/http-client-engine-crt/common/src/aws/smithy/kotlin/runtime/http/engine/crt/RequestUtil.kt
runtime/protocol/http-client-engines/http-client-engine-crt/common/test/aws/smithy/kotlin/runtime/http/engine/crt/RequestConversionTest.kt
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/OkHttpUtils.kt
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/test/aws/smithy/kotlin/runtime/http/engine/okhttp/OkHttpRequestTest.kt

Reverts [a previous commit](https://github.com/awslabs/smithy-kotlin/commit/ed4324590d37f19ffebab06eade776ea2ab61c72) which disallowed sending requests with zero `Content-Length` in the CRT HTTP engine. 
#818 
This change is required to allow sending `Content-Length=0` headers in the CRT engine, as it's done in the OkHttp engine.

fix: allow `Content-Length=0` headers in the CRT HTTP engine

---

.changes/01529a42-f6f9-49b7-8ee8-3888f319b332.json
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/OkHttpEngine.kt
runtime/protocol/http-client/api/http-client.api
runtime/protocol/http-client/common/src/aws/smithy/kotlin/runtime/http/engine/HttpClientEngineConfig.kt

To be able to test a smithy client using a local server, it makes a lot of sense to support an option without TLS.
The change is required to be able to test a locally generated smithy client with a locally generated smithy server.

Added support for H2_PRIOR_KNOWLEDGE (HTTP2 without TLS)

---

.changes/389efd23-6868-4e0d-b392-fca03d358270.json
runtime/protocol/http-client-engines/http-client-engine-crt/common/src/aws/smithy/kotlin/runtime/http/engine/crt/CrtHttpEngine.kt
runtime/protocol/http-client-engines/http-client-engine-crt/common/src/aws/smithy/kotlin/runtime/http/engine/crt/RequestUtil.kt
runtime/protocol/http-client-engines/http-client-engine-crt/common/src/aws/smithy/kotlin/runtime/http/engine/crt/SdkStreamResponseHandler.kt
runtime/protocol/http-client-engines/http-client-engine-crt/common/test/aws/smithy/kotlin/runtime/http/engine/crt/SdkStreamResponseHandlerTest.kt
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/OkHttpEngine.kt
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/OkHttpUtils.kt
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/test/aws/smithy/kotlin/runtime/http/engine/okhttp/OkHttpExceptionTest.kt
runtime/protocol/http-client/api/http-client.api
runtime/protocol/http/api/http.api
runtime/protocol/http/common/src/aws/smithy/kotlin/runtime/http/HttpException.kt
runtime/runtime-core/api/runtime-core.api
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/Exceptions.kt
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/retries/delay/StandardRetryTokenBucket.kt
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/retries/policy/RetryErrorType.kt
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/retries/policy/StandardRetryPolicy.kt
runtime/runtime-core/common/test/aws/smithy/kotlin/runtime/retries/StandardRetryStrategyTest.kt
runtime/runtime-core/common/test/aws/smithy/kotlin/runtime/retries/delay/StandardRetryTokenBucketTest.kt

N/A
* Adds a new `HttpException` and associated error code
* Updates retry policy to evaluate retry metadata from `SdkBaseException` and moves base exception evaluation after more specific exception types
* Removes `retryOnConnect` failures from OkHttp configuration. This avoids an inner retry loop that could exasperate connect storms. 
* The downside is that OkHttp internally can be smarter about retrying because they know more about the state of the request (e.g. has body been sent) and can likely retry under a few additional scenarios that we can't detect or do safely.
* Map OkHttp and CRT engine exceptions to `HttpException` and attempt to map the underlying cause to a specific `HttpErrorCode`
* Rename `RetryErrorType.Timeout` to `RetryErrorType.Transient` which maps directly to SRA …

feat(rt): retry HTTP exceptions (SRA)

---

.changes/2c77890c-7867-41d2-b0c4-6e28525989d3.json
runtime/protocol/http-client/common/src/aws/smithy/kotlin/runtime/http/engine/EnvironmentProxySelector.kt
runtime/protocol/http-client/common/test/aws/smithy/kotlin/runtime/http/engine/EnvironmentProxySelectorTest.kt
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/net/Url.kt

(none)
This change enhances the exceptions thrown while parsing proxy configurations. Previously, specifying an invalid port via a system property (e.g., `https.proxyPort="0"`) would result in a generic exception thrown:
```
java.lang.IllegalArgumentException: port must be in range [1, 65535]
```
This change indicates which properties/variables were parsed and what their values were to aid in debugging proxy configuration:
```
aws.smithy.kotlin.runtime.ClientException: Could not parse http.proxyHost="test.proxy.aws", http.proxyPort="0" into a valid proxy URL
```

feat: enhance proxy exceptions

---

.changes/c0bae93d-f508-4b1e-a810-a528285f599f.json
runtime/runtime-core/api/runtime-core.api
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/config/EnvironmentSetting.kt
runtime/runtime-core/common/test/aws/smithy/kotlin/runtime/config/EnvironmentSettingTest.kt
runtime/smithy-client/common/src/aws/smithy/kotlin/runtime/client/config/ClientSettings.kt
runtime/smithy-client/common/src/aws/smithy/kotlin/runtime/client/config/RetryMode.kt

Pre-requisite for #661 
This change refactors environmental settings and moves the core logic from **aws-sdk-kotlin**'s `AwsSdkSetting` into a new **smithy-kotlin** `EnvironmentSetting`. It also moves retry configuration settings down to **smithy-kotlin** in a new `ClientSettings` namespace.
**Companion PR**: [aws-sdk-kotlin#904](https://github.com/awslabs/aws-sdk-kotlin/pull/904)

chore: refactor environment settings and retry settings out of aws-sdk-kotlin into smithy-kotlin

---

.changes/a9e3a074-33fa-41da-8322-c83adc2e3637.json
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/StreamingRequestBody.kt
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/test/aws/smithy/kotlin/runtime/http/engine/okhttp/StreamingRequestBodyTest.kt

n/a
When OkHttp config has retry on connect failures enabled it will attempt to re-use the request body in some scenarios. The coroutine Job was setup to only be used once though and was completed when the original request fails. This causes the (internal okhttp) retry to fail with an obscure JobCompleted exception.

fix(rt): OkHttp request body retry failing due to Job completed

---

.changes/3cf671d8-1ec4-4e2f-a4ae-0f1f08f73fd1.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/waiters/KotlinJmespathExpressionVisitor.kt
tests/codegen/waiter-tests/model/waiter-operations.smithy
tests/codegen/waiter-tests/src/test/kotlin/com/test/WaiterTest.kt

Correct flat mapping codegen for waiters to correctly bubble up the inner visited expression.

fix: correct waiters with broken subfield projections

---

CHANGELOG.md

(none)
The **CHANGELOG** entry for the HTTP engine configuration change erroneously linked to https://github.com/awslabs/aws-sdk-kotlin/discussions/new?category=announcements instead of https://github.com/awslabs/aws-sdk-kotlin/discussions/919.
The [GitHub release notes](https://github.com/awslabs/smithy-kotlin/releases/tag/v0.20.0) have already been updated.

chore: fix erronerous CHANGELOG entry for HTTP configuration change

---

runtime/observability/telemetry-api/api/telemetry-api.api
runtime/observability/telemetry-api/common/src/aws/smithy/kotlin/runtime/telemetry/TelemetryProvider.kt
runtime/observability/telemetry-api/common/src/aws/smithy/kotlin/runtime/telemetry/TelemetryProviderContext.kt
runtime/observability/telemetry-api/common/src/aws/smithy/kotlin/runtime/telemetry/context/Context.kt
runtime/observability/telemetry-api/common/src/aws/smithy/kotlin/runtime/telemetry/context/ContextManager.kt
runtime/observability/telemetry-api/common/src/aws/smithy/kotlin/runtime/telemetry/context/Scope.kt
runtime/observability/telemetry-api/common/src/aws/smithy/kotlin/runtime/telemetry/context/TelemetryContextElement.kt
runtime/observability/telemetry-api/common/src/aws/smithy/kotlin/runtime/telemetry/logging/CoroutineContextLogExt.kt
runtime/observability/telemetry-api/common/src/aws/smithy/kotlin/runtime/telemetry/logging/LogRecordBuilder.kt
runtime/observability/telemetry-api/common/src/aws/smithy/kotlin/runtime/telemetry/logging/LoggerProvider.kt
runtime/observability/telemetry-api/common/src/aws/smithy/kotlin/runtime/telemetry/logging/NoOpLogger.kt
runtime/observability/telemetry-api/common/src/aws/smithy/kotlin/runtime/telemetry/trace/CoroutineContextTraceExt.kt
runtime/observability/telemetry-api/common/src/aws/smithy/kotlin/runtime/telemetry/trace/NoOpTracerProvider.kt
runtime/observability/telemetry-api/common/src/aws/smithy/kotlin/runtime/telemetry/trace/TraceSpan.kt
runtime/observability/telemetry-api/common/src/aws/smithy/kotlin/runtime/telemetry/trace/TraceSpanExt.kt
runtime/observability/telemetry-api/common/src/aws/smithy/kotlin/runtime/telemetry/trace/Tracer.kt
runtime/observability/telemetry-api/jvm/src/aws/smithy/kotlin/runtime/telemetry/context/TelemetryContextElementJVM.kt

N/A
This PR expands the telemetry API with coroutine extensions that the actual generated SDK clients and runtime will mostly use.
* Adds a new `ContextManager` interface. This is used to bridge the gap between the external calling code/observability backend and the SDK notion of context which relies on coroutine context for API boundary propagation. 
* Consider this experimental for now as we figure out the best way to deal with some of the rubber meets the road issues around actually plugging in an observability backend like OTeL
* Adds coroutine extensions for logging, trace span creation, and propagation of `Context`, `TelemetryProvider`, etc.
The following is a strawman example of what instrumenting an operation might look like. This will likely change and/or get abstracted to be …

feat: telemetry coroutine extensions

---

.changes/5F4A433D-A734-4A96-B15B-71D5146CE142.json
.changes/c641c1f7-0758-49d2-8dbd-e375853143c7.json
runtime/protocol/aws-json-protocols/common/src/aws/smithy/kotlin/runtime/awsprotocol/json/RestJsonErrorDeserializer.kt
runtime/protocol/aws-json-protocols/common/test/aws/smithy/kotlin/runtime/awsprotocol/json/RestJsonErrorDeserializerTest.kt

Fixed how restjson error codes are deserialized
https://github.com/awslabs/aws-sdk-kotlin/issues/828
It will fix the way restjson error codes are deserialized.
It will now check the following locations in order:
HTTP header x-amzn-errortype
top-level body field code
top-level body field __type

fix: correctly deserialize restjson error code

---

.changes/a646a910-2f13-4231-aa51-a5feb2e335a2.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinSymbolProvider.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinWriter.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/model/SymbolExt.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinWriterTest.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/core/SymbolProviderTest.kt

fixes #867 
Adds a way for symbol provide and writer to use a fully qualified name with more nuance than just `namespace` + `symbolName`. Collection shapes like map and list are generated with a symbol using the kotlin stdlib `Map`/`List` type. These are not the only types referenced in the resulting "Symbol" though (the generics need to be fully qualified as well).

fix(codegen): allow symbol provider to give a fully qualified name hint that takes precedence

---

.changes/c50a8d50-f66f-4598-8a58-f5c3dfc8302a.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/RuntimeTypes.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/util/ConfigPropertyType.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/util/RuntimeConfigProperty.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/waiters/WaiterGenerator.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ServiceClientConfigGeneratorTest.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ServiceClientGeneratorTest.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/waiters/ServiceWaitersGeneratorTest.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/waiters/WaiterGeneratorTest.kt
gradle.properties
runtime/protocol/http-client/common/test/aws/smithy/kotlin/runtime/http/middleware/RetryMiddlewareTest.kt
runtime/runtime-core/api/runtime-core.api
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/retries/RetryStrategy.kt
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/retries/StandardRetryStrategy.kt
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/retries/delay/DelayProvider.kt
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/retries/delay/ExponentialBackoffWithJitter.kt
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/retries/delay/InfiniteTokenBucket.kt
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/retries/delay/RetryTokenBucket.kt
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/retries/delay/StandardRetryTokenBucket.kt
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/util/DslBuilderProperty.kt
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/util/DslFactory.kt
runtime/runtime-core/common/test/aws/smithy/kotlin/runtime/retries/StandardRetryStrategyTest.kt
runtime/runtime-core/common/test/aws/smithy/kotlin/runtime/retries/delay/ExponentialBackoffWithJitterTest.kt
runtime/runtime-core/common/test/aws/smithy/kotlin/runtime/retries/delay/StandardRetryTokenBucketTest.kt
runtime/runtime-core/common/test/aws/smithy/kotlin/runtime/util/DslBuilderPropertyTest.kt
runtime/runtime-core/jvm/test/aws/smithy/kotlin/runtime/retries/impl/StandardRetryIntegrationTest.kt
runtime/smithy-client/api/smithy-client.api
runtime/smithy-client/common/src/aws/smithy/kotlin/runtime/client/RetryClientConfig.kt
runtime/smithy-client/common/src/aws/smithy/kotlin/runtime/client/SdkClientConfig.kt

Related to [aws-sdk-kotlin#701](https://github.com/awslabs/aws-sdk-kotlin/issues/701)
This change adds DSL builder methods for constructing retry strategies, making them easier to use during client initialization and re-initialization via `withConfig`. It also abstracts the core logic of DSL-style properties into a new `DslBuilderProperty` which should hopefully simplify future features like this.
**Companion PR**: [aws-sdk-kotlin#954](https://github.com/awslabs/aws-sdk-kotlin/pull/954)

feat!: simplify mechanisms for setting/updating retry strategies in client config

---

codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/RuntimeTypes.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpProtocolClientGenerator.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ServiceClientConfigGeneratorTest.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpProtocolClientGeneratorTest.kt
runtime/auth/aws-signing-tests/jvm/src/aws/smithy/kotlin/runtime/auth/awssigning/tests/SigningSuiteTestBaseJVM.kt
runtime/auth/http-auth-aws/common/test/aws/smithy/kotlin/runtime/http/auth/AwsHttpSignerTestBase.kt
runtime/observability/telemetry-api/api/telemetry-api.api
runtime/observability/telemetry-api/common/src/aws/smithy/kotlin/runtime/telemetry/logging/CoroutineContextLogExt.kt
runtime/observability/telemetry-api/common/test/aws/smithy/kotlin/runtime/telemetry/logging/TestLoggingContext.kt
runtime/protocol/aws-json-protocols/common/test/aws/smithy/kotlin/runtime/awsprotocol/json/AwsJsonProtocolTest.kt
runtime/protocol/http-client/api/http-client.api
runtime/protocol/http-client/common/src/aws/smithy/kotlin/runtime/http/engine/CoroutineUtils.kt
runtime/protocol/http-client/common/src/aws/smithy/kotlin/runtime/http/operation/HttpOperationContext.kt
runtime/protocol/http-client/common/src/aws/smithy/kotlin/runtime/http/operation/OperationTelemetry.kt
runtime/protocol/http-client/common/src/aws/smithy/kotlin/runtime/http/operation/SdkHttpOperation.kt
runtime/protocol/http-client/common/test/aws/smithy/kotlin/runtime/http/interceptors/FlexibleChecksumsResponseInterceptorTest.kt
runtime/protocol/http-client/common/test/aws/smithy/kotlin/runtime/http/operation/HttpInterceptorTest.kt
runtime/protocol/http-client/common/test/aws/smithy/kotlin/runtime/http/operation/HttpOperationContextTest.kt
runtime/protocol/http-client/common/test/aws/smithy/kotlin/runtime/http/operation/SdkHttpOperationTest.kt
runtime/protocol/http-client/common/test/aws/smithy/kotlin/runtime/http/operation/TestOperation.kt
runtime/smithy-client/api/smithy-client.api
runtime/smithy-client/common/src/aws/smithy/kotlin/runtime/client/SdkClientOption.kt

N/A
* Moves most of the instrumentation into the runtime
* Adds back `ServiceName` as required execution context (now we have the service and operation being invoked in the context which was what we had before and we removed/broke at some point).
* Adds a logging coroutine context element that defines default key/value pairs to include with all log records emitted through the `Coroutine.log*` APIs (which is what we should be using directly/indirectly everywhere in the runtime).
* This moves the handling of key/value pairs back to the underlying logger (e.g. log4j basically treats these as MDC for the individual log record). 
```
24 [main] TRACE aws.smithy.kotlin.runtime.http.operation.SerializeHandler - rpc=S3.ListBuckets sdkInvocationId=670894cb-7d9d-4d01-9d58-d0b7d08ca56c request …
```

refactor telemetry instrumentation

---

.changes/adfc6461-c39c-4dc2-bc55-ef00b16c13a5.json
codegen/smithy-kotlin-codegen-testutils/src/main/kotlin/software/amazon/smithy/kotlin/codegen/test/ModelTestUtils.kt

Fixed an issue with utility. SDK ID for `route 53` requires space but service name can't have space, i.e. `route53`
No Issue available (Will make one if required)
It solves the problem if the utility not working when it comes to route 53
<br>

fix: model test utils serviceName bug

---

.changes/a2c5037e-db65-45f5-8033-acbd3bf241ee.json
runtime/serde/serde-xml/common/src/aws/smithy/kotlin/runtime/serde/xml/XmlDeserializer.kt
runtime/serde/serde-xml/common/src/aws/smithy/kotlin/runtime/serde/xml/XmlStreamReader.kt
runtime/serde/serde-xml/common/test/aws/smithy/kotlin/runtime/serde/xml/XmlDeserializerMapTest.kt

This PR fixes a bug in the XML deserializer which fails to process consecutive flat maps properly. Before this change, the deserializer would seek forward until it found a matching map key. Consecutive flat maps sharing the same key names would be lumped together unintentionally. 
The fix is to seek using `XmlSerialName` as a comparator since this is the only thing distinguishing different flat maps. A new deserialize method `peekSeek` is added which seeks forward and only consumes tokens if they are a match.
https://github.com/awslabs/aws-sdk-kotlin/issues/962
This fixes a bug when deserializing consecutive flat maps. See the new "consecutive flat maps" test case for an example of an XML tree for which parsing previously failed. 
By submitting this pull request, I confirm that my …

fix: correctly deserialize consecutive XML flat maps 

---

runtime/observability/telemetry-api/common/src/aws/smithy/kotlin/runtime/telemetry/TelemetryProvider.kt
runtime/observability/telemetry-api/common/src/aws/smithy/kotlin/runtime/telemetry/logging/CoroutineContextLogExt.kt
runtime/observability/telemetry-api/common/src/aws/smithy/kotlin/runtime/telemetry/trace/CoroutineContextTraceExt.kt
runtime/observability/telemetry-defaults/common/src/aws/smithy/kotlin/runtime/telemetry/DefaultTelemetryProvider.kt
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/HttpEngineEventListener.kt
runtime/protocol/http-client/common/src/aws/smithy/kotlin/runtime/http/engine/internal/HttpClientMetrics.kt
runtime/protocol/http-client/common/src/aws/smithy/kotlin/runtime/http/interceptors/OperationTelemetryInterceptor.kt
runtime/protocol/http-client/common/src/aws/smithy/kotlin/runtime/http/operation/OperationMetrics.kt
runtime/protocol/http-client/common/src/aws/smithy/kotlin/runtime/http/operation/OperationTelemetry.kt

N/A
Mark the `TelemetryProvider` API as experimental and optin where necessary. This explicitly doesn't mark the `TelemetryProvider` interface or configuration types as experimental as that would make configuring the SDK itself experimental. Instead we mark every field/method on the interface as `Experimental`. As we stabilize each telemetry signal implementation we can start to remove the annotation (e.g. once we are happy with metrics and the set of metrics exported we might remove it from `meterProvider`). 

Mark TelemetryProvider API experimental

---

.changes/f8716e6a-24e2-41fb-96b9-3e9e5593867a.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/RuntimeTypes.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/endpoints/DefaultEndpointProviderGenerator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/endpoints/DefaultEndpointProviderTestGenerator.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/endpoints/DefaultEndpointProviderGeneratorTest.kt
runtime/runtime-core/api/runtime-core.api
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/net/Url.kt
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/net/UrlDecoding.kt
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/net/UrlParser.kt
runtime/runtime-core/common/test/aws/smithy/kotlin/runtime/net/UrlDecodingTest.kt
runtime/runtime-core/common/test/aws/smithy/kotlin/runtime/net/UrlParserTest.kt

Closes #888 
This change corrects a bug in URL encoding in endpoint resolution which caused parsing to URL-_decode_ strings which were already properly encoded.

fix: correct URL encoding in endpoint resolution

---

.changes/d50afb27-0e5c-46b3-9c9c-865a3c75dd21.json
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/OkHttpUtils.kt
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/test/aws/smithy/kotlin/runtime/http/engine/okhttp/OkHttpExceptionTest.kt

fixes aws-sdk-kotlin#905
https://github.com/awslabs/smithy-kotlin/pull/829 disabled the OkHttp engine setting `retryOnConnectionFailure`. The reason for this was sound, we don't want an "inner" retry loop running inside an HTTP engine as it will retry outside the scope of the retry strategy/policy (e.g. not respecting backoffs, etc). 
This increases the chance we hit a connection/network related error though. In particular S3 seems to aggressively reset connections under load. The logs show a connection is grabbed from the pool that was used previously for a successful request and fails on getting the response headers (it sends the request at which point S3 closes the connection). 
This manifest with an exception like the following:
```
java.io.IOException: unexpected end of stream on …
```

fix: make connection resets retryable in OkHttp engine

---

.changes/c5f04082-06d1-4425-b7b9-b1ac2b9b8edd.json
runtime/protocol/http-client-engines/http-client-engine-crt/common/src/aws/smithy/kotlin/runtime/http/engine/crt/CrtHttpEngine.kt
runtime/protocol/http-client-engines/http-client-engine-okhttp/api/http-client-engine-okhttp.api
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/OkHttpEngine.kt
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/OkHttpEngineConfig.kt
runtime/protocol/http-client/api/http-client.api
runtime/protocol/http-client/common/src/aws/smithy/kotlin/runtime/http/engine/HttpClientEngineConfig.kt

closes #898 
* Introduce new HTTP engine `maxConcurrency` setting which controls the maximum number of in-flight requests. Above this requests will suspend and wait for available capacity. 
* **breaking**: Rename OkHttp `maxConnectionsPerHost` to `maxConcurrencyPerHost` which is how it is actually used
* Remap the OkHttp `Dispatcher` settings to use the new `maxConcurrency` and `maxConcurrencyPerHost` settings. We ignore `maxConnections` all together for now in OkHttp engine.
* Add request limiter to CRT engine to respect the new `maxConcurrency` setting
* Increase the default `maxConnections` setting to closer align to Java v2 default (50). 

feat(rt)!:introduce maxConcurrency HTTP setting and rename OkHttp maxConnectionsPerHost

---

.changes/ee74d8c0-697e-4ca2-95c9-d0285876c71a.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/RuntimeTypes.kt
runtime/protocol/http-client/common/src/aws/smithy/kotlin/runtime/http/interceptors/ResponseLengthValidationInterceptor.kt
runtime/protocol/http-client/common/test/aws/smithy/kotlin/runtime/http/interceptors/ResponseLengthValidationInterceptorTest.kt

This PR adds an interceptor which validates the `Content-Length` response header against the response body. If the lengths don't match, an `IllegalStateException` is thrown.
This interceptor is currently only used for S3 `GetObject` responses.
https://github.com/awslabs/aws-sdk-kotlin/issues/745
This PR is required to support validating `Content-Length` response headers for S3 `GetObject` responses.

feat: add content length validation interceptor

---

.changes/493ccb85-b5ab-4a0b-89eb-c4ef45bfcf42.json
runtime/auth/aws-credentials/api/aws-credentials.api
runtime/auth/aws-credentials/common/src/aws/smithy/kotlin/runtime/auth/awscredentials/CredentialsProviderChain.kt
runtime/auth/aws-credentials/common/test/aws/smithy/kotlin/runtime/auth/awscredentials/CredentialsProviderChainTest.kt
runtime/auth/http-auth/api/http-auth.api
runtime/auth/http-auth/common/src/aws/smithy/kotlin/runtime/http/auth/BearerTokenProviderChain.kt
runtime/auth/http-auth/common/test/aws/smithy/kotlin/runtime/http/auth/BearerTokenProviderChainTest.kt

closes aws-sdk-kotlin#1001
For configuration-driven use-cases where a list of providers is created the acceptance of a list is convenient. These changes were made by adding an additional constructor

feat: make credentials provider chain accept list of credentials providers

---

runtime/protocol/http-client/common/src/aws/smithy/kotlin/runtime/http/operation/SdkOperationExecution.kt

[583](https://github.com/awslabs/aws-sdk-kotlin/issues/583) - Make user-supplied region available to config resolution providers
There are several places where config resolution providers require bootstrapping region, which is possibly present in user-supplied client config. This fixes this issue by making region available via attributes/execution context 
Also look at: https://github.com/awslabs/aws-sdk-kotlin/pull/997

feat: make user-supplied region available to credentials providers

---

.changes/589535ae-bf2d-4364-b428-1700846cd8d6.json
runtime/protocol/http-client/common/src/aws/smithy/kotlin/runtime/http/interceptors/ResponseLengthValidationInterceptor.kt
runtime/protocol/http-client/common/test/aws/smithy/kotlin/runtime/http/interceptors/ResponseLengthValidationInterceptorTest.kt

Closes https://github.com/awslabs/aws-sdk-kotlin/issues/1014
Correctly validates response length for empty bodies and byte array bodies.
**Companion PR**: https://github.com/awslabs/aws-sdk-kotlin/pull/1015

fix: correctly validate response length for empty and byte array bodies

---

codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/waiters/KotlinJmespathExpressionVisitor.kt
tests/codegen/waiter-tests/model/waiter-operations.smithy
tests/codegen/waiter-tests/src/test/kotlin/com/test/WaiterTest.kt

Implement full support for JMESPath expression types #596 
-The sub-expression function is now recursive and will be able to visit all expressions needed
-Visiting indexes is now available

feat: add support for sub-expressions and list indexing in JMESPath

---

.changes/3b0318b9-d379-4fb4-8bcc-8dd4de6029a0.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinSymbolProvider.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/core/SymbolProviderTest.kt

Closes https://github.com/awslabs/aws-sdk-kotlin/issues/1016
The SDK incorrectly serializes structure members' default values in requests regardless of the `@clientOptional` trait. As recently clarified in Smithy reference docs, `@clientOptional` supersedes `@default` and should cause serializers to skip recognizing/sending a default value.
This affected EC2's `DescribeVpcsRequest.MaxResults` and potentially many other structure members.

fix: stop serializing default values for @clientOptional members

---

runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/HttpEngineEventListener.kt

(none)
As [suggested by Matas](https://github.com/awslabs/smithy-kotlin/pull/908#discussion_r1287131797), this PR reorders the event handlers in `HttpEngineEventListener` to align with the OkHttp documentation and _generally_ be in order of sequential execution.
There are no functional changes in this PR, just reordering methods.

misc: reorder events in HttpEngineEventListener

---

codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/waiters/KotlinJmespathExpressionVisitor.kt
tests/codegen/waiter-tests/model/waiter-operations.smithy
tests/codegen/waiter-tests/src/test/kotlin/com/test/WaiterTest.kt

closes #922
-Added some tests for the boolean operators (and, or, not)
-Fixed a small typo in the OR visitor

feat: add tests for boolean operators in JMESPath

---

runtime/protocol/http-client-engines/test-suite/common/test/aws/smithy/kotlin/runtime/http/test/AsyncStressTest.kt

n/a
Lower the engine concurrency to closer to what it was when this test was written (16 for okhttp). This is a band aid to fix the flakiness of this test on windows CI since I haven't been able to reproduce it locally.

fix: lower engine concurrency to closer to what it was when test was written to fix windows issue

---

.changes/4cc18c3e-31f4-4f70-987d-36e1ddee4a57.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/auth/Sigv4AuthSchemeIntegration.kt
runtime/auth/http-auth-aws/common/src/aws/smithy/kotlin/runtime/http/auth/AwsHttpSigner.kt

fixes https://github.com/awslabs/aws-sdk-kotlin/issues/1029
* Adds a new middleware when sigv4 is present that conditionally enables setting the `SignedBodyHeader` execution context attribute when the operation has the unsigned payload trait or is an event stream input. When set the signer will add the `x-amz-content-sha256` header to the canonical request and set the header.
* Adds the `shouldSignHeader` predicate to the `AwsHttpSigner.Config`. This was missing and allows auth scheme overrides to augment the set of signed headers. This allowed me to narrow down the issue since we include a few more headers than AWS CLI did. This should have been possible previously and I was surprised it wasn't.
By submitting this pull request, I confirm that my contribution is made under the terms of …

fix: x-amz-content-sha256 header is expected for unsigned payload and event stream operations

---

codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/waiters/KotlinJmespathExpressionVisitor.kt
tests/codegen/waiter-tests/model/function-avg.smithy
tests/codegen/waiter-tests/model/function-ends-with.smithy
tests/codegen/waiter-tests/model/function-join.smithy
tests/codegen/waiter-tests/model/function-starts-with.smithy
tests/codegen/waiter-tests/model/function-sum.smithy
tests/codegen/waiter-tests/model/structures.smithy
tests/codegen/waiter-tests/model/waiter-operations.smithy
tests/codegen/waiter-tests/src/main/kotlin/com/test/DefaultWaitersTestClient.kt
tests/codegen/waiter-tests/src/test/kotlin/com/test/FunctionAvgTest.kt
tests/codegen/waiter-tests/src/test/kotlin/com/test/FunctionEndsWithTest.kt
tests/codegen/waiter-tests/src/test/kotlin/com/test/FunctionJoinTest.kt
tests/codegen/waiter-tests/src/test/kotlin/com/test/FunctionStartsWithTest.kt
tests/codegen/waiter-tests/src/test/kotlin/com/test/FunctionSumTest.kt

Added:
-Sum
-Avg
-Join
-Starts with
-Ends with
Refactored:
-Separated operations from structures in smithy file
-Wrote function to avoid code duplication in JMESPath visitor functions code

feat: add functions (sum, avg, join, starts_with, ends_with) to JMESPath visitor

---

runtime/protocol/http-client/common/test/aws/smithy/kotlin/runtime/http/engine/HttpClientEngineTest.kt

Explicitly joining coroutines in test due to failing windows CI test

fix: explicitly join coroutines in failing  http client engine test

---

.changes/855b179f-a977-459f-b7d7-fc0bccd208d7.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinSymbolProvider.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/core/SymbolProviderTest.kt

(none)
Enum shapes don't have correct defaults codegenned for them. For example, in a structure's builder class:
```kotlin
public var mode: aws.sdk.kotlin.services.neptunedata.model.GraphSummaryType? = "basic" // <-- compiler error
```
This change adds handling of defaults so that they're resolved correctly from the enum's members.

fix: correctly codegen defaults for enum shapes

---

.changes/9b8a79bf-8d89-481f-b671-4aba9c3b5250.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpBindingProtocolGenerator.kt

This PR finalizes fixing a bug (#935) by passing the entire `HttpCall` to the deserializer. The accompanying PR in **aws-sdk-kotlin** uses the call to launch a new coroutine within its scope.
#935 

fix: event streams deserialization using `HttpCall` scope

---

.changes/d47756d3-1127-4ed0-a71f-44ca2daebf9a.json
runtime/runtime-core/api/runtime-core.api
runtime/runtime-core/jvm/src/aws/smithy/kotlin/runtime/content/ByteStreamJVM.kt
runtime/runtime-core/jvm/src/aws/smithy/kotlin/runtime/io/SdkBufferedSourceJVM.kt
runtime/runtime-core/jvm/src/aws/smithy/kotlin/runtime/io/SdkByteReadChannelJVM.kt
runtime/runtime-core/jvm/test/aws/smithy/kotlin/runtime/content/ByteStreamInputStreamTest.kt
runtime/runtime-core/jvm/test/aws/smithy/kotlin/runtime/content/ByteStreamJVMTest.kt

closes https://github.com/awslabs/aws-sdk-kotlin/issues/617
Adds a conversion to go from `ByteStream` to `java.io.InputStream`

feat(rt): add InputStream adapter for ByteStream

---

runtime/protocol/http-test/common/src/aws/smithy/kotlin/runtime/httptest/CallAsserter.kt
runtime/protocol/http-test/common/src/aws/smithy/kotlin/runtime/httptest/TestConnection.kt
runtime/protocol/http-test/common/test/aws/smithy/kotlin/runtime/httptest/TestConnectionTest.kt

Related to https://github.com/awslabs/aws-sdk-kotlin/issues/1000
This change makes `TestConnection` more configurable in how it verifies `HttpRequest` instances. Specifically, it introduces a `CallAsserter` type, various implementations of which can be chosen when ready to verify an engine's inputs.

misc: make TestConnection request assertions more configurable

---

.changes/f82c0433-30f9-4246-8f18-91402c5ac0ab.json
runtime/runtime-core/api/runtime-core.api
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/content/ByteStream.kt
runtime/runtime-core/common/test/aws/smithy/kotlin/runtime/content/ByteStreamFactory.kt
runtime/runtime-core/common/test/aws/smithy/kotlin/runtime/content/ByteStreamFlowTest.kt
runtime/runtime-core/jvm/test/aws/smithy/kotlin/runtime/content/ByteStreamInputStreamTest.kt

closes https://github.com/awslabs/aws-sdk-kotlin/issues/612
* Adds a conversion from `ByteStream` to `Flow<ByteArray>`
* Adds a converstion from `Flow<ByteArray>` to `ByteStream`
1. Should `ByteStream.Buffer` try to respect the `bufferSizeHint` parameter? The easiest thing to do was to ignore it which is also the most performant (otherwise we'll be chunking it and making additional copies). 

feat(rt): add conversions to and from ByteStream and Flow<ByteArray>

---

.changes/b6288fbe-a409-473c-a6ac-12c3c310b963.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/KotlinSettings.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ExceptionBaseClassGenerator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ServiceClientGenerator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/StructureGenerator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/auth/AuthSchemeParametersGenerator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/auth/AuthSchemeProviderGenerator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/endpoints/DefaultEndpointProviderGenerator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/endpoints/EndpointDelegator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/endpoints/EndpointParametersGenerator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/endpoints/EndpointProviderGenerator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/endpoints/discovery/EndpointDiscovererGenerator.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/KotlinSettingsTest.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/endpoints/DefaultEndpointProviderGeneratorTest.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/endpoints/EndpointParametersGeneratorTest.kt

This PR updates build settings to allow configuring visibility for `serviceClient`, `structure`, and `error`. This corresponds to visibility on the generated service client, Smithy Structure shapes, and Smithy Error shapes, respectively. 
N/A
This change is required so we can generate internal-only SDK clients with the proper `internal` visibility, so they don't show up in the public API footprint.

misc: add `visibility` build setting

---

codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/RuntimeTypes.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/waiters/KotlinJmespathExpressionVisitor.kt
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/util/JMESPath.kt
tests/codegen/waiter-tests/model/function-type.smithy
tests/codegen/waiter-tests/model/utils/structures.smithy
tests/codegen/waiter-tests/model/utils/waiter-operations.smithy
tests/codegen/waiter-tests/src/main/kotlin/com/test/DefaultWaitersTestClient.kt
tests/codegen/waiter-tests/src/test/kotlin/com/test/FunctionTypeTest.kt

-Added `type` function to JMESPath visitor
NOTES: 
-Added flag to ignore null guards to `dotFunction` 
-Smithy's JMESPath parser won't allow string comparison so I had to get around that using the `Types` structure

feat: add type function to JMESPath visitor

---

.changes/598b7088-0032-4336-8aab-3c242876301c.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpProtocolClientGenerator.kt

Fixes a bug discovered during testing of our internal preview builds. If a service does not model operations, we should not try to import from the `transform.*` namespace, because it doesn't exist.
N/A -- internal only

fix: only import `transform` namespace if there are modeled operations

---

.github/workflows/continuous-integration.yml
build.gradle.kts
runtime/auth/aws-signing-tests/jvm/src/aws/smithy/kotlin/runtime/auth/awssigning/tests/SigningSuiteTestBaseJVM.kt
runtime/build.gradle.kts
settings.gradle.kts

n/a
Refactor CI to no longer need CRT builder (still used by codebuild jobs for now though). Restructures main PR workflow to test against a matrix of JVM versions and match upstream `aws-sdk-kotlin` https://github.com/awslabs/aws-sdk-kotlin/pull/1069

chore: refactor ci workflows

---

.changes/b31b8667-e931-49cf-8897-4e2ded2b7f14.json
.changes/c063605b-4702-4d8a-a841-2e0b7aa78e78.json
runtime/observability/logging-slf4j2/jvm/src/aws/smithy/kotlin/runtime/telemetry/logging/slf4j/Slf4j1xLoggerAdapter.kt
runtime/observability/logging-slf4j2/jvm/src/aws/smithy/kotlin/runtime/telemetry/logging/slf4j/Slf4j2xLoggerAdapter.kt
runtime/observability/telemetry-api/api/telemetry-api.api
runtime/observability/telemetry-api/common/src/aws/smithy/kotlin/runtime/telemetry/logging/CoroutineContextLogExt.kt
runtime/observability/telemetry-api/common/src/aws/smithy/kotlin/runtime/telemetry/logging/LogRecordBuilder.kt
runtime/observability/telemetry-api/common/src/aws/smithy/kotlin/runtime/telemetry/logging/NoOpLogger.kt
runtime/observability/telemetry-api/common/src/aws/smithy/kotlin/runtime/telemetry/trace/NoOpTracerProvider.kt
runtime/observability/telemetry-api/common/src/aws/smithy/kotlin/runtime/telemetry/trace/SpanContext.kt
runtime/observability/telemetry-api/common/src/aws/smithy/kotlin/runtime/telemetry/trace/TraceSpan.kt
runtime/observability/telemetry-provider-otel/jvm/src/aws/smithy/kotlin/runtime/telemetry/otel/OtelTracerProvider.kt
runtime/protocol/http-client/common/src/aws/smithy/kotlin/runtime/http/interceptors/OperationTelemetryInterceptor.kt
runtime/protocol/http-client/common/src/aws/smithy/kotlin/runtime/http/operation/OperationMetrics.kt

n/a
* **refactor!**: remove `smithy.client.request.size`, `smithy.client.response.size`, and `smithy.client.retries` metrics
* **refactor!**: rename `smithy.client.*` metrics to `smithy.client.call.*` 
* **refactor**: Add `SpanContext` to `TraceSpan`
* **refactor!**: Remove `setContext` from fluent log builder in-favor of explicitly setting span context K/V pairs

refactor!: rename metrics and remove redundant metrics

---

runtime/serde/serde-xml/common/src/aws/smithy/kotlin/runtime/serde/xml/XmlSerializer.kt

closes #957 
-Removed xmlns from entry tag when serializing maps 

fix: remove namespace from xml map entry serialization

---

.changes/0645c929-bdfe-4d07-a131-b0b447422fff.json
runtime/protocol/http-client-engines/http-client-engine-crt/common/src/aws/smithy/kotlin/runtime/http/engine/crt/RequestUtil.kt
runtime/protocol/http-client-engines/http-client-engine-crt/common/test/aws/smithy/kotlin/runtime/http/engine/crt/RequestUtilTest.kt
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/OkHttpUtils.kt
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/test/aws/smithy/kotlin/runtime/http/engine/okhttp/OkHttpExceptionTest.kt

(none)
This change enables retrying on:
* all `IOException` errors in the default OkHttp engine
* many IO and IO-like errors in the CRT engine
This will enable transient problems like socket errors, DNS lookup failues, etc. to be retried the same as other retryable errors.

fix: treat IO exceptions as retryable in HTTP engines

---

.github/workflows/continuous-integration.yml
build.gradle.kts

Run `test` and `jvmTest` tasks in the downstream CI. `publishToMavenLocal` does not run a full build, so currently the unit tests are not run as part of this CI

fix: run `test` and `jvmTest` in downstream CI

---

codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/model/ShapeExt.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpBindingProtocolGenerator.kt

-The part of the code that renders the xml content type header is made overridable

refactor: xml content type header renderer to be overridable

---

.changes/e8825e61-8155-4da0-a9c9-eae9a0d786d4.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/utils/CaseUtils.kt

n/a
First pass at optimizing `splitOnWordBoundaries` which was refactored in #975.  Avoids re-computation of "is start of word" when we already know it isn't the start of a word.
Follows after the similar Rust PR: https://github.com/smithy-lang/smithy-rs/pull/3140
Timings before and after for camel casing everything in `all-names-test-output.csv`:
```
// BEFORE
took 2634 milliseconds
took 1990 milliseconds
took 2211 milliseconds
took 1822 milliseconds
took 2038 milliseconds
// AFTER
took 487 milliseconds
took 392 milliseconds
took 353 milliseconds
took 352 milliseconds
took 346 milliseconds
```

fix: optimize splitOnWordBoundaries

---

.changes/6467a679-d9c3-4741-8219-28d7d32abf5f.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/integration/SectionWriter.kt
gradle.properties
gradle/libs.versions.toml
runtime/auth/aws-credentials/api/aws-credentials.api
runtime/auth/aws-credentials/common/src/aws/smithy/kotlin/runtime/auth/awscredentials/CachedCredentialsProvider.kt
runtime/auth/aws-credentials/common/src/aws/smithy/kotlin/runtime/auth/awscredentials/Credentials.kt
runtime/runtime-core/api/runtime-core.api
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/util/Attributes.kt

n/a
downstream: https://github.com/awslabs/aws-sdk-kotlin/pull/1111
Refactors `Credentials` to be an interface. 
Miscellaneous support for upstream account ID based routing PR.

account id routing and credentials interface

---

codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/endpoints/DefaultEndpointProviderGenerator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/endpoints/DefaultEndpointProviderTestGenerator.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/endpoints/DefaultEndpointProviderGeneratorTest.kt
runtime/runtime-core/api/runtime-core.api
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/collections/Attributes.kt

Usage of `AttributeKey` in endpoints  code generation fails with `Not enough information to infer type variable T`.
Example usage:
```kt
return Endpoint(
Url.parse("${url?.scheme}://${url?.authority}/${uriEncodedBucket}${url?.path}"),
attributes = attributesOf {
AttributeKey("backend") to "FOOBAR" // Not enough information to infer type variable T
SigningContextAttributeKey to listOf(
sigV4(
serviceName = "s3",
disableDoubleUriEncode = true,
signingRegion = "${params.region}",
),
)
},
)
```
The fix is to provide the type for `AttributeKey<T>`.  New codegen will look like:
```kt
AttributeKey.create("backend", "FOOBAR") to "FOOBAR"
```
This is done to avoid type-parsing at codegen and just let the Kotlin compiler work it out.
By submitting this pull request, I confirm that my contribution …

fix: `AttributeKey` code generation

---

.github/workflows/continuous-integration.yml
runtime/protocol/http-client/common/test/aws/smithy/kotlin/runtime/http/interceptors/FlexibleChecksumsRequestInterceptorTest.kt

n/a
Fix CI issue on windows where test runner is running out of memory. 
I didn't spend a ton of time debugging this but we are allocating 128M string and then immediately converting it to a `ByteArray` of same size. With a 256M total allocation it's possible the test runner is just running closer to it's limit on windows and toppling over.
Also added the OS name to the test report artifact to disambiguate if there are failures on more than one platform. This was just a miss in the original workflow definition.

fix: windows ci flakey test

---

.changes/57a9f297-a562-4d70-a0f1-1821816a54eb.json
runtime/auth/aws-signing-default/common/src/aws/smithy/kotlin/runtime/auth/awssigning/Canonicalizer.kt
runtime/auth/aws-signing-default/common/test/aws/smithy/kotlin/runtime/auth/awssigning/DefaultCanonicalizerTest.kt
runtime/auth/aws-signing-tests/jvm/src/aws/smithy/kotlin/runtime/auth/awssigning/tests/SigningSuiteTestBaseJVM.kt
runtime/runtime-core/api/runtime-core.api
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/text/encoding/Encodable.kt
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/text/encoding/PercentEncoding.kt
runtime/runtime-core/common/test/aws/smithy/kotlin/runtime/net/url/QueryParametersTest.kt
runtime/serde/serde-form-url/common/src/aws/smithy/kotlin/runtime/serde/formurl/FormUrlSerializer.kt
runtime/serde/serde-form-url/common/test/aws/smithy/kotlin/runtime/serde/formurl/FormUrlSerializerTest.kt
runtime/smithy-client/common/src/aws/smithy/kotlin/runtime/client/endpoints/functions/Functions.kt

Closes #1008 
This update fixes encoding and signing problems around special characters in URL paths and query parameters. The root of the problem is that some characters (e.g., `@`) are valid in paths and queries according to [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986) but are [required to be escaped for the purposes of URL signing](https://docs.aws.amazon.com/IAM/latest/UserGuide/create-signed-request.html#create-canonical-request). Prior code didn't properly differentiate the character sets that must be escaped in both situations and instead treated them as identical.

fix: correctly sign special characters (e.g., "@") in URL paths

---

.changes/295410ec-cc32-4a9c-a30a-aaeda9996c0f.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ShapeValueGenerator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpProtocolUnitTestRequestGenerator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpProtocolUnitTestResponseGenerator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/samples/KDocSamplesGenerator.kt
codegen/smithy-kotlin-codegen/src/main/resources/META-INF/services/software.amazon.smithy.kotlin.codegen.integration.KotlinIntegration
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ShapeValueGeneratorTest.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/samples/KDocSamplesGeneratorTest.kt
docs/dokka-presets/css/aws-styles.css

https://github.com/awslabs/aws-sdk-kotlin/issues/239
downstream: https://github.com/awslabs/aws-sdk-kotlin/pull/1143
* Implements support for generating samples from the [examples trait](https://smithy.io/2.0/spec/documentation-traits.html#smithy-api-examples-trait).
* Cleans up `ShapeValueGenerator` a bit to make the output formatting nicer (we previously only used it for generating protocol tests so minor formatting issues weren't a big deal but they should be cleaner for docs).
1. Code is output to `src/samples` directory. Samples are not automatically included by dokka, you have to update the configuration to get them included.
2. We decided to omit doing anything with the `output` of the examples trait and to omit error examples. It isn't clear what customer benefit there is to …

feat: generate operation samples

---

bom/build.gradle.kts
build.gradle.kts
gradle/libs.versions.toml
settings.gradle.kts
tests/benchmarks/serde-benchmarks/build.gradle.kts
tests/benchmarks/serde-benchmarks/smithy-build.json
tests/codegen/nullability-tests/build.gradle.kts
tests/codegen/nullability-tests/smithy-build.json
tests/codegen/paginator-tests/build.gradle.kts
tests/codegen/paginator-tests/smithy-build.json
tests/codegen/waiter-tests/build.gradle.kts
tests/codegen/waiter-tests/smithy-build.json

Refactors the build to use our [new codegen plugin](https://github.com/awslabs/aws-kotlin-repo-tools/pull/29) based on the newer smithy gradle base plugin.

chore: refactor build to use custom smithy build plugin

---

.changes/80e3c346-9a4a-4d47-84f1-1655742f9711.json
runtime/auth/aws-signing-common/build.gradle.kts
runtime/auth/aws-signing-common/common/src/aws/smithy/kotlin/runtime/auth/awssigning/Presigner.kt
runtime/auth/aws-signing-common/common/test/aws/smithy/kotlin/runtime/auth/awssigning/PresignerTest.kt
runtime/protocol/http-client/common/src/aws/smithy/kotlin/runtime/http/operation/OperationEndpoint.kt

https://github.com/awslabs/aws-sdk-kotlin/issues/1173
This change ensures that the resolved endpoint is fully applied to an unsigned request before presigning, ensuring that any non-standard rules are applied (e.g., S3's `forcePathStyle`).
**Companion PR**: https://github.com/awslabs/aws-sdk-kotlin/pull/1174

fix: correctly apply resolved endpoint to presigned requests

---

.changes/8127023a-192a-4cf7-a979-62987a2f40dd.json
runtime/auth/aws-signing-default/common/src/aws/smithy/kotlin/runtime/auth/awssigning/Canonicalizer.kt
runtime/auth/aws-signing-default/common/test/aws/smithy/kotlin/runtime/auth/awssigning/DefaultCanonicalizerTest.kt
runtime/protocol/http-client/common/src/aws/smithy/kotlin/runtime/http/operation/OperationEndpoint.kt
runtime/protocol/http-client/common/test/aws/smithy/kotlin/runtime/http/operation/OperationEndpointTest.kt
runtime/runtime-core/api/runtime-core.api
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/net/url/Url.kt

https://github.com/awslabs/aws-sdk-kotlin/issues/1177
This change adds handling of non-standard ports during signing and presigning by including them in the `Host` header and also the canonical string used in signature calculation.

fix: correctly include custom ports in signing/presigning

---

.brazil.json

**refactor**: Add a new `.brazil.json` file with the transform logic for just `aws-sdk-kotlin`. **NOTE**: This will not take effect until we release a new version of `kat` and update the release pipeline to use it. Until then the "global" transform config from repo tools is still the one being used. I tested this locally already the runtime and diffed the transform output using the one from repo tools and this new localized copy

chore: relocate brazil transform

---

.changes/581b0e21-e59b-427c-a959-276f09276b88.json
runtime/serde/common/src/aws/smithy/kotlin/runtime/serde/Serializer.kt
runtime/serde/serde-form-url/common/src/aws/smithy/kotlin/runtime/serde/formurl/FormUrlSerializer.kt
runtime/serde/serde-json/common/src/aws/smithy/kotlin/runtime/serde/json/JsonSerializer.kt
runtime/serde/serde-json/common/test/aws/smithy/kotlin/runtime/serde/json/JsonDeserializerTest.kt
runtime/serde/serde-json/common/test/aws/smithy/kotlin/runtime/serde/json/JsonSerializerTest.kt
runtime/serde/serde-xml/common/src/aws/smithy/kotlin/runtime/serde/xml/XmlSerializer.kt

(none)
This adds a missed overload in the JSON serializer which handles serializing map values which are `Document` instances.

fix: correctly serialize maps which use the Document type as a value

---

.github/workflows/api-compat-verification.yml
build.gradle.kts
runtime/auth/aws-signing-common/api/aws-signing-common.api
runtime/auth/http-auth-aws/api/http-auth-aws.api
runtime/auth/identity-api/api/identity-api.api
runtime/crt-util/api/crt-util.api
runtime/observability/telemetry-api/api/telemetry-api.api
runtime/protocol/aws-event-stream/api/aws-event-stream.api
runtime/protocol/aws-json-protocols/api/aws-json-protocols.api
runtime/protocol/aws-protocol-core/api/aws-protocol-core.api
runtime/protocol/aws-xml-protocols/api/aws-xml-protocols.api
runtime/protocol/http-client-engines/http-client-engine-default/api/http-client-engine-default.api
runtime/protocol/http-client/api/http-client.api
runtime/protocol/http/api/http.api
runtime/runtime-core/api/runtime-core.api
runtime/serde/api/serde.api
runtime/serde/serde-form-url/api/serde-form-url.api
runtime/serde/serde-json/api/serde-json.api
runtime/serde/serde-xml/api/serde-xml.api
runtime/smithy-client/api/smithy-client.api

https://github.com/awslabs/aws-sdk-kotlin/issues/1191
This change tightens backwards compatibility guarantees by:
* Removing `@InternalApi` from the exemptions for the backwards compatibility verifier
* Also updates the API dumps because a lot of previously-exempted APIs are now in scope
* Adds a PR check which verifies that either no API dump lines have been deleted _or_ the **acknowledge-api-break** label is applied to the PR
* [Example run with no breaking changes](https://github.com/awslabs/smithy-kotlin/actions/runs/7791179880/job/21246672755) (succeeded)
* [Example run with breaking changes, no label](https://github.com/awslabs/smithy-kotlin/actions/runs/7791240677/job/21246879734) (failed)
* [Example run with breaking changes, **acknowledge-api-break** …

chore: add @InternalApi to binary compatibility checks; introduce new PR check to verify no API-breaking changes

---

.changes/ed8a74dd-01a4-46c3-96eb-8ac9356bead6.json
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/net/url/Url.kt
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/text/Scanner.kt
runtime/runtime-core/common/test/aws/smithy/kotlin/runtime/net/url/UrlParsingTest.kt

Resolves #1031 
Fixes parsing logic to correctly handle the `@` symbol outside of the userinfo segment.

fix: correctly parse URLs with '@' symbol

---

.changes/00960dac-40d8-4b6d-a3a7-12eb944d5753.json
.changes/4ecf93e9-b11e-43b8-9c7c-ed7753916c64.json
runtime/protocol/http/common/src/aws/smithy/kotlin/runtime/http/request/HttpRequestBuilder.kt
runtime/protocol/http/common/test/aws/smithy/kotlin/runtime/http/HttpRequestBuilderTest.kt
runtime/smithy-client/common/src/aws/smithy/kotlin/runtime/client/LogMode.kt
runtime/smithy-client/common/test/aws/smithy/kotlin/runtime/client/LogModeTest.kt

fixes https://github.com/awslabs/aws-sdk-kotlin/issues/1198
* **fix**: Preserve the original `HttpBody` properties like content length from the original `HttpBody` when duplicating it. The issue in awslabs/aws-sdk-kotlin#1198 seems to have been caused by the fact that the original body was an `AwsChunked` body with a `transfer-encoding: chunked` header. When we replace the body during the trace call it was replaced with a non-equivalent in-memory byte array body which always has a content length.
* **fix**: `LogRequestWithBody` and `LogResponseWithBody` should imply `LogRequest` and `LogResponse` respectively. I discovered this trying to debug this issue and seeing the incorrect behaviors for dumping the canonical request from S3
By submitting this pull request, I confirm that my …

fix: http trace interceptor not keeping original HttpBody properties and LogMode not behaving as expected

---

runtime/auth/aws-signing-common/api/aws-signing-common.api
runtime/auth/aws-signing-common/common/src/aws/smithy/kotlin/runtime/auth/awssigning/AwsSigningExceptions.kt

N/A
-Added the cause constructor parameter to the `UnsupportedSigningAlgorithmException`. 
-Fixed outdated documentation.

misc: added cause to unsupported signing algorithm exception

---

.changes/fb91506d-98b4-4344-bf8b-c1527afe002c.json
runtime/auth/aws-signing-common/api/aws-signing-common.api
runtime/auth/aws-signing-common/common/src/aws/smithy/kotlin/runtime/auth/awssigning/AwsSigningAttributes.kt
runtime/auth/http-auth-aws/common/src/aws/smithy/kotlin/runtime/http/auth/AwsHttpSigner.kt
runtime/auth/http-auth-aws/common/test/aws/smithy/kotlin/runtime/http/auth/AwsHttpSignerTestBase.kt

Related to downstream PR: https://github.com/awslabs/aws-sdk-kotlin/pull/1224
This PR updates the logic enabling `aws-chunked` to also consider the new `EnableAwsChunked` signing attribute

feat: add `EnableAwsChunked` signing attribute

---

.changes/f274caeb-9450-45b1-935c-5f61905de53b.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/StructureGenerator.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ExceptionGeneratorTest.kt
runtime/runtime-core/api/runtime-core.api
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/Exceptions.kt

n/a
Refactor exception codegen to pass the `message` field to the exception base class constructor rather than overriding it wholesale. This will allow the base class to augment the message (or fill it in from other sources like `sdkErrorMetadata` which may have more information from protocol parsing logic).

refactor: delegate exception error messages to exception base class logic

---

.changes/8571dd20-b6a8-4cab-9e2a-567e273a016f.json
.changes/de403702-531d-4f43-bc33-aa5bc2fc000f.json
runtime/protocol/http/common/src/aws/smithy/kotlin/runtime/http/response/HttpResponse.kt
runtime/runtime-core/api/runtime-core.api
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/Exceptions.kt
runtime/runtime-core/common/test/aws/smithy/kotlin/runtime/ExceptionsTest.kt

https://github.com/awslabs/aws-sdk-kotlin/issues/1212
This change modifies how `ServiceException` messages are formed. Request IDs are added when available. Additionally, subclasses can add more metadata by overriding the `displayMetadata` property. Finally, when a service-provided exception message is unavailable, a message will be formed by a combination of error code, error type, and protocol response.
**Companion PR**: https://github.com/awslabs/aws-sdk-kotlin/pull/1240

feat: enhance exception messages with request IDs and metadata

---

codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/DeserializeStructGenerator.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/DeserializeStructGeneratorTest.kt

Missed in #1052 which addresses #1045 
Correctly handle nested maps in codegen. (e.g., `Map<OuterEnumType, Map<InnerEnumType, String>>`) and add a unit test to verify.

fix: correctly codegen maps which use nested maps that contain enum keys

---

.changes/c855db56-72aa-4f1e-9200-46122fdaec75.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/PaginatorGenerator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/waiters/ServiceWaitersGenerator.kt

Operations with the paginated trait or waiter trait that come from resources are not considered as part of the integration enable checks. In general we should almost never be iterating `model.operationShapes` directly. Especially since a "model" can technically contain multiple services and we always want to be working with some defined service shape closure.
```smithy
$version: "2"
namespace example.weather
service Weather {
version: "2006-03-01"
resources: [City]
operations: [GetCurrentTime]
}
resource City {
identifiers: { cityId: CityId }
read: GetCity
list: ListCities
}
@paginated(...)
operation ListCities { ... }
...
```

fix(codegen): resource operations not generating paginators or waiters

---

.changes/6ffd0a2b-9801-4814-a6d1-9d84196ff130.json
runtime/protocol/http-client-engines/http-client-engine-default/jvm/test/aws/smithy/kotlin/runtime/http/engine/HttpEngineConfigImplTest.kt
runtime/protocol/http-client/api/http-client.api
runtime/protocol/http-client/common/src/aws/smithy/kotlin/runtime/http/engine/EnvironmentProxySelector.kt
runtime/protocol/http-client/common/test/aws/smithy/kotlin/runtime/http/engine/EnvironmentProxySelectorTest.kt

This PR updates the `EnvironmentProxySelector` to lazily resolve environment variables rather than immediately parsing them during initialization
Resolves https://github.com/awslabs/aws-sdk-kotlin/issues/1281

fix: lazily resolve proxy environment variables

---

.changes/19208b1c-8c36-452b-a6e3-e0bef345776a.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/RuntimeTypes.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/StructureGenerator.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/StructureGeneratorTest.kt
runtime/runtime-core/api/runtime-core.api
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/Annotations.kt

Resolves #428 
Calls within nested DSL functions will resolve an implicit receiver from anywhere up the hierarchy, enabling bad calls like this one:
```kotlin
CreateBucketRequest {
bucket = "foo"
grantRead = "bar"
createBucketConfiguration {
grantRead = "baz" // Should be prohibited
}
}
```
In the above example, setting `grantRead` from within `createBucketConfiguration` should be prohibited because `grantRead` is a member of `CreateBucketRequest.Builder`, not `CreateBucketConfiguration.Builder`.
This change introduces a new DSL marker annotation `@SdkDsl` which is applied to every codegenned structure builder. Code like the above example now fails to compile.

feat: add DSL markers to codegenned structure builders

---

.changes/e26e1980-ee66-4d9d-99b5-6ee0f1f3901d.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/PaginatorGenerator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/waiters/ServiceWaitersGenerator.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/PaginatorGeneratorTest.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/waiters/ServiceWaitersGeneratorTest.kt
codegen/smithy-kotlin-codegen/src/test/resources/software/amazon/smithy/kotlin/codegen/simple-service-with-operation-waiter.smithy
codegen/smithy-kotlin-codegen/src/test/resources/software/amazon/smithy/kotlin/codegen/simple-service-with-resource-waiter.smithy

Addresses https://github.com/awslabs/aws-sdk-kotlin/issues/900
Various parts of codegen tried to get all the operations a service supports via `ServiceShape.allOperations` which, despite the name, _does not_ return all operations of the service, merely the ones listed in the service shape. Other operations available through resources were not considered.
This change uses the `TopDownIndex`'s `getContainedOperations` method to find directly-attached operations _and_ resource operations, ensuring that waiters and paginators are correctly codegenned for resource operations.

fix: correctly codegen waiters and paginators for resource operations

---

.changes/5498a35b-f57f-4c0c-bbf7-43e07830be01.json
codegen/smithy-aws-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/aws/middleware/ClockSkew.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/RuntimeTypes.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ServiceClientGenerator.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ServiceClientGeneratorTest.kt
runtime/smithy-client/api/smithy-client.api
runtime/smithy-client/common/src/aws/smithy/kotlin/runtime/client/AbstractSdkClientFactory.kt

Addresses https://github.com/awslabs/aws-sdk-kotlin/issues/1211
This change supports adding the clock skew interceptor to clients created via `invoke` (as opposed to via `fromEnvironment`) by creating a new `AbstractSdkClientFactory` superclass with a _non-_`suspend` `finalizeConfig` method and adjusting codegen accordingly.
**Companion PR**: https://github.com/awslabs/aws-sdk-kotlin/pull/1284

fix: apply clock skew interceptor to clients created via `invoke`

---

.changes/56a90e2f-014b-4abd-8baa-5ce12dc60320.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/ClientErrorCorrection.kt
tests/codegen/nullability-tests/model/nullability.smithy
tests/codegen/nullability-tests/src/test/kotlin/smithy/kotlin/nullability/ErrorCorrectionTest.kt

Int enums will have an `SdkUnknown` generated with a String value of `"no value provided"`, which fails to compile. This PR separates the logic handling string enums and int enums.
Internal issue

fix: differentiate between string enum and int enum in client correction

---

.changes/e43c0830-b8d0-43d0-a8bb-1e2c93b8ac7c.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/PaginatorGenerator.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/PaginatorGeneratorTest.kt

No direct issue but related to https://github.com/awslabs/aws-sdk-kotlin/issues/900 and https://github.com/smithy-lang/smithy-kotlin/pull/1064
The recent codegen change to generate paginators for resource operations uncovered a previously-unknown bug: responses that contain items in a sparse list were being generated as `Flow<Item>` (non-nullable) instead of `Flow<Item?>` (nullable). This change fixes that and adds a new test.

fix: correctly codegen paginators for items in sparse lists

---

codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinWriter.kt
runtime/protocol/http/api/http.api
runtime/protocol/http/common/src/aws/smithy/kotlin/runtime/http/response/HttpResponse.kt
runtime/protocol/http/common/src/aws/smithy/kotlin/runtime/http/response/HttpResponseBuilder.kt

- Updates deprecation message generation to use the messaged configured on `DeprecatedTrait` if it exists.
- Adds `HttpResponseBuilder` to match `HttpRequestBuilder`
- Useful when writing interceptors that need to mutate an HTTP response (i.e `modifyBeforeDeserialization`) 

misc: Add `HttpResponseBuilder` and use message from `DeprecatedTrait` if set

---

.changes/8e87c6dd-5138-4b79-a0c2-255ecf31898b.json
breaking-change-discussion-draft.md
gradle/libs.versions.toml
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/OkHttpEngine.kt
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/test/aws/smithy/kotlin/runtime/http/engine/okhttp/StreamingRequestBodyTest.kt

Upgrade to the latest versions of OkHttp, Okio, and Kotlin.
Changes include needing to opt-in to `ExperimentalCoroutinesApi` for the `executeAsync` call and no longer being able to implement `BufferedSink` because it's now a `sealed interface`. 
We can only use `Buffer` in our tests now, [which is hardcoded to always open](https://github.com/square/okio/blob/e2ac4c05093e166bcb2e56fb8f834fc4f03d299b/okio/src/jvmMain/kotlin/okio/Buffer.kt#L504), so the `isClosed` checks are no longer possible to perform.
Related to https://github.com/smithy-lang/smithy-kotlin/issues/1068

misc: upgrade to OkHttp 5.0.0-alpha.14, Okio 3.9.0, Kotlin 1.9.23

---

.changes/e3e20544-5633-4722-8923-106117678325.json
runtime/protocol/aws-protocol-core/common/src/aws/smithy/kotlin/runtime/awsprotocol/ClockSkewInterceptor.kt
runtime/protocol/aws-protocol-core/common/test/ClockSkewInterceptorTest.kt

Resolves https://github.com/awslabs/aws-sdk-kotlin/issues/1293
The `ClockSkewInterceptor` cannot currently handle receiving out-of-spec HTTP `Date` header values and throws an exception, even if the response would've been successful. This change wraps the date parsing logic and logs a warning if an error occurs, which no longer interrupts response processing.

fix: handle bad time formats in clock skew interceptor

---

.changes/040b1587-ec85-4601-9eec-a5158cb0edac.json
runtime/protocol/http-client/common/src/aws/smithy/kotlin/runtime/http/engine/EnvironmentProxySelector.kt
runtime/protocol/http-client/common/src/aws/smithy/kotlin/runtime/http/engine/HttpClientEngineConfig.kt
runtime/protocol/http-client/common/test/aws/smithy/kotlin/runtime/http/engine/EnvironmentProxySelectorTest.kt
runtime/protocol/http-client/common/test/aws/smithy/kotlin/runtime/http/engine/NoProxyHostTest.kt

This PR adds support for `http.nonProxyHosts` JVM system property. Previously we [incorrectly supported](https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html) `http.noProxyHosts`.
`http.noProxyHosts` is still supported, but `http.nonProxyHosts` is prioritized when both system properties are present.
Closes https://github.com/smithy-lang/smithy-kotlin/issues/1081

fix: support `http.nonProxyHost` JVM system property

---

build.gradle.kts
gradle/libs.versions.toml
runtime/protocol/http-client-engines/test-suite/build.gradle.kts
runtime/protocol/http-client-engines/test-suite/jvm/test/aws/smithy/kotlin/runtime/http/test/MitmContainer.kt
runtime/protocol/http-client-engines/test-suite/jvm/test/aws/smithy/kotlin/runtime/http/test/ProxyTest.kt
runtime/protocol/http-client-engines/test-suite/jvm/test/aws/smithy/kotlin/runtime/http/test/util/Docker.kt
runtime/protocol/http-client-engines/test-suite/jvm/test/aws/smithy/kotlin/runtime/http/test/util/Poller.kt
runtime/runtime-core/api/runtime-core.api
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/time/Instant.kt
runtime/runtime-core/jvm/src/aws/smithy/kotlin/runtime/time/InstantJVM.kt
runtime/runtime-core/native/src/aws/smithy/kotlin/runtime/time/InstantNative.kt

https://github.com/smithy-lang/smithy-kotlin/security/dependabot/9
The Testcontainers utility we use for proxy testing has a dependency on a vulnerable version of Apache Commons Compress (see https://github.com/testcontainers/testcontainers-java/issues/8338, [CVE-2024-25710](https://www.cve.org/CVERecord?id=CVE-2024-25710), and [CVE-2024-26308](https://www.cve.org/CVERecord?id=CVE-2024-26308)). The library maintainers [refuse to upgrade to a safe version because of API compatibility](https://github.com/testcontainers/testcontainers-java/pull/8354#issuecomment-1957345903), which indicates their maintenance policy isn't robust enough for our usage.
This PR replaces Testcontainers with the [Docker Java client](https://github.com/docker-java/docker-java) and adds utility classes …

chore: address testcontainers vulnerability by replacing with docker-java

---

codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/SerializeStructGenerator.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/SerializeStructGeneratorTest.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/SerializeUnionGeneratorTest.kt

N/A
Fix rendering of sparse structure serializers

fix: sparse struct serializer

---

.changes/cbfc3f67-c8b3-49ad-8e06-0e9bdece01e9.json
runtime/protocol/http-client/common/src/aws/smithy/kotlin/runtime/http/engine/EnvironmentProxySelector.kt
runtime/protocol/http-client/common/test/aws/smithy/kotlin/runtime/http/engine/EnvironmentProxySelectorTest.kt

#1092
We currently support the `*` wildcard in `http.nonProxyHosts` _only_ in the global case (i.e., `http.nonProxyHosts=*`) but not when used as a prefix/suffix (e.g., `http.nonProxyHosts=amazon.com*`). This change adds the necessary support and tests.

fix: respect prefix/suffix wildcards in nonProxyHosts

---

.changes/ecbd7021-83e8-47c7-857a-8f77949adc72.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpBindingProtocolGenerator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpStringValuesMapSerializer.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpBindingProtocolGeneratorTest.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpStringValuesMapSerializerTest.kt
codegen/smithy-kotlin-codegen/src/test/resources/software/amazon/smithy/kotlin/codegen/http-binding-protocol-generator-test.smithy

Addresses https://github.com/awslabs/aws-sdk-kotlin/issues/1314
We are currently serializing enums parameters with their _name_ as opposed to their _value_ in URI paths, leading to invalid requests. This change fixes several small codegen bugs related to path and parameter serialization in HTTP bindings.

fix: correctly serialize enum parameters in URIs

---

.changes/7c1e4ec8-d975-498d-affa-ce470d268785.json
runtime/observability/logging-slf4j2/jvm/src/aws/smithy/kotlin/runtime/telemetry/logging/slf4j/Slf4j1xLoggerAdapter.kt
runtime/protocol/http-client/common/src/aws/smithy/kotlin/runtime/http/engine/EnvironmentProxySelector.kt
runtime/protocol/http-client/common/test/aws/smithy/kotlin/runtime/http/engine/EnvironmentProxySelectorTest.kt

Closes #1098 
This changes adds handling for empty/blank proxy host values sourced from environment variables and system properties. The previous behavior was to throw an exception because blank strings couldn't be parsed into hosts.

fix: silently ignore empty proxy host values

---

gradle/libs.versions.toml
runtime/protocol/http-client-engines/test-suite/build.gradle.kts

Updates various dependencies to address vulnerabilities reported by Dependabot, especially from [docker-java, since they have many vulnerable dependencies.](https://github.com/docker-java/docker-java/issues/1974)

fix: address various Dependabot warnings

---

.changes/56c3bdfe-3416-46c4-a9e4-7d87918ee94b.json
codegen/smithy-aws-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/aws/protocols/core/AwsHttpBindingProtocolGenerator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinSymbolProvider.kt
gradle/libs.versions.toml

(none)
This change upgrades Smithy to [**1.50.0**](https://github.com/smithy-lang/smithy/releases/tag/1.50.0), the latest version available.
**Companion PR**: https://github.com/awslabs/aws-sdk-kotlin/pull/1349

chore: upgrade Smithy to 1.50.0

---

docs/dokka-presets/scripts/accessibility.js

**Round 2!**
- Ensure only one toggle-content button is inserted
- I was sometimes seeing two toggle-content buttons 
- Insert a skip-to-main-content link on the first `sideMenuPart`
- Clicking a `sideMenuPart` would throws the tab index back to the top, meaning you have to tab all the way through to your current `sideMenuPart` before you will reach the skip-to-main-content link. This change adds a skip-link to the first `sideMenuPart` and the `data-active` `sideMenuPart` to ensure this case is covered.
- Update invocation of `ensureNavButtonInteractable` function
- I wasn't seeing this function's effects on the prod docs, hopefully updating the way its invoked will fix this 

misc: docs accessibility fixes

---

.changes/30110eeb-0708-45b6-973f-960dc6062ce6.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/StructureGenerator.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/StructureGeneratorTest.kt

Kotlin variant of https://github.com/smithy-lang/smithy-rs/issues/3757
This change widens the criteria for considering a structure field sensitive to now include lists with members marked as sensitive and maps with either keys or values marked as sensitive.

fix: correctly redact sensitive data in lists/maps

---

.changes/22c07786-9168-425a-960b-e03378ee3ce3.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/model/knowledge/EndpointParameterIndex.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/endpoints/EndpointResolverAdapterGenerator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/waiters/KotlinJmespathExpressionVisitor.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/endpoints/EndpointResolverAdapterTest.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/endpoints/OperationContextParamsTest.kt

Add support for the [operationContextParams](https://smithy.io/2.0/additional-specs/rules-engine/parameters.html#smithy-rules-operationcontextparams-trait) trait

feat: add support for operationContextParams trait

---

.changes/22c07786-9168-425a-960b-e03378ee3ce3.json
.changes/f1afb4d6-fa61-4eba-8695-b9a8bc59418a.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/model/RulesEngineExt.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/model/knowledge/EndpointParameterIndex.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/endpoints/DefaultEndpointProviderTestGenerator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/endpoints/EndpointResolverAdapterGenerator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/waiters/KotlinJmespathExpressionVisitor.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/endpoints/EndpointParametersGeneratorTest.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/endpoints/EndpointResolverAdapterTest.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/endpoints/OperationContextParamsTest.kt

Add support for string arrays in [rules engine parameters](https://smithy.io/2.0/additional-specs/rules-engine/specification.html#parameter-object)

feat: add support for string arrays in rules engine parameters & support for operationContextParams trait

---

docs/dokka-presets/scripts/accessibility.js

misc(docs): handle case where sideMenu is already expanded on page load

---

.changes/1ab4f8b7-5721-4024-a4dc-d0c595495bd2.json
docs/dokka-presets/scripts/accessibility.js
runtime/protocol/http-client-engines/http-client-engine-crt/jvm/src/aws/smithy/kotlin/runtime/http/engine/crt/CrtHttpEngine.kt
runtime/protocol/http-client-engines/http-client-engine-crt/jvm/src/aws/smithy/kotlin/runtime/http/engine/crt/SdkStreamResponseHandler.kt

`HttpStream` returned from `makeRequest` ["must be closed by the user thread making this request when it's done"](https://github.com/awslabs/aws-crt-java/blob/main/src/main/java/software/amazon/awssdk/crt/http/HttpClientConnection.java#L39-L40)

fix: Close CRT HttpStream on call completion

---

.changes/29e93882-7346-4a2f-bbcd-1cdf478a3b10.json
runtime/runtime-core/api/runtime-core.api
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/time/TimestampFormat.kt
runtime/runtime-core/common/test/aws/smithy/kotlin/runtime/time/InstantTest.kt
runtime/runtime-core/jvm/src/aws/smithy/kotlin/runtime/time/InstantJVM.kt
runtime/serde/common/src/aws/smithy/kotlin/runtime/serde/Parsers.kt
runtime/serde/serde-json/common/src/aws/smithy/kotlin/runtime/serde/json/JsonSerializer.kt

Related to https://github.com/awslabs/aws-sdk-kotlin/issues/472
This change adds a new `ISO_8601_FULL` member to the `TimestampFormat` enum. The new value enables formatting of timestamps with untruncated precision in contrast to `ISO_8601` which truncates at microsecond precision. This is primarily to facilitate lossless precision in roundtrips through [DynamoDB Mapper](https://github.com/awslabs/aws-sdk-kotlin/issues/472) but may be useful in other circumstances as well.

feat: add ISO_8601_FULL timestamp format for untruncated precision

---

.changes/6a37ba36-d945-422c-a4ba-811ef498ca71.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/XmlParserGenerator.kt
tests/compile/build.gradle.kts
tests/compile/src/test/kotlin/software/amazon/smithy/kotlin/codegen/SmithySdkTest.kt
tests/compile/src/test/kotlin/software/amazon/smithy/kotlin/codegen/util/CodegenTestIntegration.kt

We were not distinguishing between strings and string-based enums when generating the parser for XML protocols. This PR updates the codegen to treat string shapes with the `EnumTrait` as enums.  
Closes https://github.com/smithy-lang/smithy-kotlin/issues/1125

fix: correctly deserialize string-based enums in XML protocols

---

.brazil.json

(none)
This change temporarily adds **telemetry-provider-micrometer** to the ignorelist for Brazil.

chore: temporarily omit Micrometer telemetry provider from Brazil

---

.changes/1d38a75d-17ac-4e03-b287-f937356bd525.json
runtime/protocol/http-client-engines/http-client-engine-crt/jvm/src/aws/smithy/kotlin/runtime/http/engine/crt/ConnectionManager.kt
runtime/protocol/http-client-engines/http-client-engine-crt/jvm/src/aws/smithy/kotlin/runtime/http/engine/crt/RequestUtil.kt
runtime/protocol/http-client-engines/http-client-engine-crt/jvm/src/aws/smithy/kotlin/runtime/http/engine/crt/SdkStreamResponseHandler.kt

(none)
Some of the places CRT exceptions are thrown don't correctly set the `ErrorMetadata.Retryable` attribute. This change updates some of those exceptions in the **smithy-kotlin** HTTP engine layer.

fix: correctly mark more CRT exceptions as retriable

---

runtime/protocol/aws-protocol-core/common/src/aws/smithy/kotlin/runtime/awsprotocol/ClockSkewInterceptor.kt

misc: Downgrade clock skew exception stack trace to `debug` level

---

.changes/b786851c-9427-40cd-b3fa-ee375011d931.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/DeserializeStructGenerator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/DeserializeUnionGenerator.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/DeserializeUnionGeneratorTest.kt

Resolves #1126 
This change corrects some faulty deserializer logic around union members and nested maps/lists. Specifically, it no longer tries to deserialize nested map/list types into an instance of a union member, only top-level maps/lists. This bug was quite apparent when looking at the codegen unit tests.

fix: correct deserialization of nested map/list types in unions

---

dokka-smithy/src/main/kotlin/aws/smithy/kotlin/dokka/DisablePlaygroundIntegration.kt
dokka-smithy/src/main/kotlin/aws/smithy/kotlin/dokka/FilterInternalApis.kt
dokka-smithy/src/main/kotlin/aws/smithy/kotlin/dokka/SmithyDokkaPlugin.kt

(none)
This change fixes two Dokka problems:
* Stop including **playground.js** in generated HTML pages
* Correctly filter for internal-only APIs which shouldn't get Dokka pages

fix: stop including playground.js in Dokka pages and correctly filter for internal APIs

---

.brazil.json
.changes/347d905e-25a5-49be-9d32-4fbf9305e85d.json
gradle/libs.versions.toml
runtime/runtime-core/common/test/aws/smithy/kotlin/runtime/retries/delay/StandardRetryTokenBucketTest.kt
runtime/runtime-core/common/test/aws/smithy/kotlin/runtime/retries/delay/TimingUtils.kt
runtime/runtime-core/jvm/test/aws/smithy/kotlin/runtime/retries/impl/AdaptiveRetryIntegrationTest.kt

misc: upgrade to kotlinx.coroutines 1.9.0

---

.changes/f71f083b-6e5f-4a3c-9069-464b1f9f6d36.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinSymbolProvider.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/PaginatorGenerator.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/PaginatorGeneratorTest.kt

The paginator generator is not code-generating nullable literals for item paginators of lists that have values that are nullable. It will only code-generate nullability if the list is marked as [sparse](https://smithy.io/2.0/spec/type-refinement-traits.html#sparse-trait) and not check if the list has values that are nullable.
Lists are not supposed to contain nullable items unless marked as `sparse`, so this is non-modeled behavior that we were not looking for but is necessary because [documents](https://smithy.io/2.0/spec/simple-types.html#document) are always nullable in smithy kotlin.
The paginator generator now checks if the collection is made of nullable symbols and code generates nullability
By submitting this pull request, I confirm that my contribution is made under the terms of …

fix: paginator generator nullability bug caused by documents

---

codegen/smithy-kotlin-codegen/src/main/resources/META-INF/services/software.amazon.smithy.kotlin.codegen.integration.KotlinIntegration

(internal)
Smoke test codegen is broken for some services. Disabling the integration until the underlying codegen issues are fixed.

fix: disable smoke tests temporarily until other codegen issues are fixed

---

.changes/cda907f0-b704-42de-a50f-dad204dacbfb.json
runtime/runtime-core/api/runtime-core.api
runtime/runtime-core/jvm/src/aws/smithy/kotlin/runtime/content/ByteStreamJVM.kt
runtime/runtime-core/jvm/test/aws/smithy/kotlin/runtime/content/ByteStreamJVMTest.kt

Closes https://github.com/awslabs/aws-sdk-kotlin/issues/1444

misc: Update docs for `ByteStream.writeToOutputStream`, add `ByteStream.appendToOutputStream`

---

.changes/386353e6-e3cc-4561-bfd6-9763d3ac033b.json
.github/workflows/continuous-integration.yml
gradle/libs.versions.toml
runtime/protocol/http-client-engines/http-client-engine-okhttp/api/http-client-engine-okhttp.api
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/ConnectionIdleMonitor.kt
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/OkHttpEngine.kt
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/OkHttpEngineConfig.kt
runtime/protocol/http-client-engines/test-suite/build.gradle.kts
runtime/protocol/http-client-engines/test-suite/jvm/src/aws/smithy/kotlin/runtime/http/test/suite/Connections.kt
runtime/protocol/http-client-engines/test-suite/jvm/src/aws/smithy/kotlin/runtime/http/test/util/TestServers.kt
runtime/protocol/http-client-engines/test-suite/jvm/test/aws/smithy/kotlin/runtime/http/test/ConnectionTest.kt

Resolves https://github.com/awslabs/aws-sdk-kotlin/issues/1214
This PR adds a new opt-in idle connection monitor for OkHttp, configurable by the engine parameter `connectionIdlePollingInterval`. This setting is opt-in for now to preserve existing behavior but will be switched to opt-out (or replaced) in a future minor release.

fix: add support for idle connection monitoring (opt-in for now)

---

codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/lang/DocumentationPreprocessor.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/lang/DocumentationPreprocessorTest.kt

- Graceful handling of empty list items in documentation trait 

fix: documentation trait handling empty list items

---

runtime/protocol/http-client-engines/http-client-engine-okhttp/build.gradle.kts
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/ConnectionIdleMonitor.kt
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/OkHttpEngine.kt
runtime/protocol/http-client-engines/http-client-engine-okhttp4/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp4/OkHttp4Engine.kt

Original issue that sparked idle connection monitoring: https://github.com/awslabs/aws-sdk-kotlin/issues/1214
OkHttp4 was broken by idle connection monitoring: https://github.com/smithy-lang/smithy-kotlin/issues/1176
- Launching the connection monitors using the call context was causing the call to wait on the connection monitor coroutines. This fix creates a coroutine scope dedicated to connection monitors. This new scope will be cancelled/joined when the HTTP engine being used is closed.
- Noticed `shutdown` was missing from `OkHttp4Engine` so added it.
- The refactoring of `OkHttpEngineConfig.buildClient` fixes https://github.com/smithy-lang/smithy-kotlin/issues/1176 by not including `connectionListener` as part of `OkHttp4Engine`
Calling `S3` `getObject` twice went from taking ~6 sec …

fix: http call waiting for idle connection monitor to finish

---

.changes/51a98f59-4a7f-4d14-8f26-4eb70a3eb1dc.json
codegen/smithy-aws-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/aws/protocols/RpcV2Cbor.kt
codegen/smithy-aws-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/aws/protocols/eventstream/EventStreamParserGenerator.kt
codegen/smithy-aws-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/aws/protocols/RpcV2CborTest.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpBindingProtocolGenerator.kt

fix: `rpcv2Cbor` event stream requests sending incorrect `:content-type`

---

codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ShapeValueGenerator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/smoketests/SmokeTestsRunnerGenerator.kt
codegen/smithy-kotlin-codegen/src/main/resources/META-INF/services/software.amazon.smithy.kotlin.codegen.integration.KotlinIntegration
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/smoketests/SmokeTestsRunnerGeneratorTest.kt

(none)
This change replaces the codegen for smoke test input params with the `ShapeValueGenerator` and also makes small changes to use imported symbols rather than fully qualified ones.

fix: correctly deserialize/render input values for smoke tests

---

CHANGELOG.md
CONTRIBUTING.md
codegen/smithy-aws-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/aws/protocols/RestJson1.kt
codegen/smithy-aws-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/aws/protocols/xml/RestXmlSerdeDescriptorGenerator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/CodegenVisitor.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/integration/SectionWriter.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/XmlSerdeDescriptorGenerator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/utils/CaseUtils.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpBindingProtocolGeneratorTest.kt
docs/design/binary-streaming.md
docs/design/flexible-checksums.md
docs/design/interceptors.md
docs/design/kotlin-smithy-sdk.md
docs/design/modeled-errors.md
docs/design/structured-concurrency.md
docs/design/waiters.md
runtime/auth/aws-signing-default/common/test/aws/smithy/kotlin/runtime/auth/awssigning/DefaultCanonicalizerTest.kt
runtime/auth/aws-signing-default/common/test/aws/smithy/kotlin/runtime/auth/awssigning/DefaultSignatureCalculatorTest.kt
runtime/auth/aws-signing-tests/jvm/src/aws/smithy/kotlin/runtime/auth/awssigning/tests/SigningSuiteTestBaseJVM.kt
runtime/protocol/aws-json-protocols/common/test/aws/smithy/kotlin/runtime/awsprotocol/json/AwsJsonProtocolTest.kt
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/OkHttpUtils.kt
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/test/aws/smithy/kotlin/runtime/http/engine/okhttp/OkHttpRequestTest.kt
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/test/aws/smithy/kotlin/runtime/http/engine/okhttp/StreamingRequestBodyTest.kt
runtime/protocol/http-client-engines/test-suite/common/test/aws/smithy/kotlin/runtime/http/test/UploadTest.kt
runtime/protocol/http-client-engines/test-suite/jvm/test/aws/smithy/kotlin/runtime/http/test/FileUploadDownloadTest.kt
runtime/runtime-core/common/test/aws/smithy/kotlin/runtime/time/ParseRfc5322Test.kt
runtime/serde/serde-form-url/common/src/aws/smithy/kotlin/runtime/serde/formurl/FormUrlSerializer.kt
runtime/serde/serde-xml/common/test/aws/smithy/kotlin/runtime/serde/xml/XmlStreamWriterTest.kt
tests/codegen/serde-tests/src/test/kotlin/aws/smithy/kotlin/tests/serde/XmlMapTest.kt
tests/codegen/serde-tests/src/test/kotlin/aws/smithy/kotlin/tests/serde/XmlUnionTest.kt

docs: rename `awslabs/smithy-kotlin` to `smithy-lang/smithy-kotlin`

---

.changes/68aac1d5-64f9-4569-bf95-db8d5712a2df.json
runtime/runtime-core/jvm/src/aws/smithy/kotlin/runtime/content/ByteStreamJVM.kt
runtime/runtime-core/jvm/test/aws/smithy/kotlin/runtime/content/ByteStreamJVMTest.kt

fix: Check if an `InputStream` is replayable when setting `isOneShot`

---

.changes/0857b6f0-0444-479f-be6b-06ef71d482a0.json
.changes/1c6d0436-16c3-46d6-9fb5-d9af6c119ba5.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/waiters/WaiterGenerator.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/waiters/ServiceWaitersGeneratorTest.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/waiters/WaiterGeneratorTest.kt

Add optional configuration for waiters' `RetryStrategy`
Closes https://github.com/awslabs/aws-sdk-kotlin/issues/1431 and closes https://github.com/smithy-lang/smithy-kotlin/issues/839

feat: add `retryStrategy` configuration option for waiters

---

runtime/runtime-core/api/runtime-core.api
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/businessmetrics/BusinessMetricsUtils.kt
runtime/runtime-core/common/test/aws/smithy/kotlin/runtime/businessmetrics/BusinessMetricsUtilsTest.kt

These changes are related to malformed business metrics we are seeing in the `User-Agent` header.
Also see: https://github.com/awslabs/aws-sdk-kotlin/pull/1474

misc: override toString in business metrics

---

.changes/2de8162f-e5a0-4618-b00d-8da3cfdbc6a2.json
runtime/runtime-core/jvm/src/aws/smithy/kotlin/runtime/content/ByteStreamJVM.kt
runtime/runtime-core/jvm/test/aws/smithy/kotlin/runtime/content/ByteStreamJVMTest.kt

misc: enhance support for replayable instances of `InputStream`

---

.changes/1021e75a-45f3-4f3a-820c-700d9ec6e782.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpProtocolUnitTestRequestGenerator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/SerializeStructGenerator.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/SerializeStructGeneratorTest.kt
runtime/serde/serde-xml/common/src/aws/smithy/kotlin/runtime/serde/xml/XmlSerializer.kt

fix: CBOR protocol test assertions / blob serialization

---

codegen/smithy-aws-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/aws/protocols/core/QueryHttpBindingProtocolGenerator.kt
codegen/smithy-aws-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/aws/protocols/RpcV2CborTest.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/CborSerializerGenerator.kt

fix: correctly serialize subset of shape's members when configured

---

codegen/protocol-tests/model/error-correction-tests.smithy
codegen/smithy-aws-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/aws/protocols/core/AwsHttpBindingProtocolGenerator.kt
gradle/libs.versions.toml

chore: smithy version bump

---

runtime/auth/aws-signing-common/api/aws-signing-common.api
runtime/auth/aws-signing-common/common/src/aws/smithy/kotlin/runtime/auth/awssigning/AuthTokenGenerator.kt
runtime/auth/aws-signing-common/common/test/aws/smithy/kotlin/runtime/auth/awssigning/AuthTokenGeneratorTest.kt

feat: add `AuthTokenGenerator`

---

gradle.properties
gradle/libs.versions.toml
runtime/build.gradle.kts
runtime/runtime-core/api/runtime-core.api
runtime/runtime-core/build.gradle.kts
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/content/BigDecimal.kt
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/content/BigInteger.kt
runtime/runtime-core/common/test/aws/smithy/kotlin/runtime/content/BigIntegerTest.kt
runtime/runtime-core/jvm/src/aws/smithy/kotlin/runtime/content/BigDecimalJVM.kt
runtime/runtime-core/jvm/src/aws/smithy/kotlin/runtime/content/BigIntegerJVM.kt
runtime/runtime-core/native/src/aws/smithy/kotlin/runtime/content/BigDecimalNative.kt
runtime/runtime-core/native/src/aws/smithy/kotlin/runtime/content/BigIntegerNative.kt

(none)
This change implements Kotlin/Native support for `BigInteger`/`BigDecimal` by way of the [IonSpin **kotlin-multiplatform-bignum**](https://github.com/ionspin/kotlin-multiplatform-bignum) library. This change adds a workaround for building **smithy-kotlin** on Amazon Linux 2 because of linking issues with zlib (see **[runtime/build.gradle.kts](https://github.com/smithy-lang/smithy-kotlin/compare/kn-main...kn-bignums?expand=1#diff-23f01691d6dba0dd32c4e07f9490975ea4bfe9c0a29a6a004fd8b51c7a952c1a)**).

feat: Kotlin/Native implementation of BigDecimal and BigInteger

---

.github/workflows/continuous-integration.yml
gradle/libs.versions.toml
runtime/auth/aws-signing-common/common/src/aws/smithy/kotlin/runtime/auth/awssigning/AuthTokenGenerator.kt
runtime/auth/aws-signing-common/common/test/aws/smithy/kotlin/runtime/auth/awssigning/AuthTokenGeneratorTest.kt

fix: Ensure `Host` header is included when signing auth tokens

---

codegen/protocol-tests/model/error-correction-tests.smithy
codegen/smithy-aws-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/aws/protocols/core/AwsHttpBindingProtocolGenerator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinSymbolProvider.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/StructureGenerator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpStringValuesMapSerializer.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/core/SymbolProviderTest.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpBindingProtocolGeneratorTest.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpStringValuesMapSerializerTest.kt
gradle/libs.versions.toml
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/text/encoding/Base64.kt
runtime/runtime-core/common/test/aws/smithy/kotlin/runtime/text/encoding/Base64Test.kt

- Fixes a failing protocol test by allowing serialization of empty headers. Related to https://github.com/smithy-lang/smithy/pull/2433 and https://github.com/smithy-lang/smithy/pull/2403.
- Fixes a few failing protocol tests by updating our handling of default blob values to decode the Base64 string
- Address another failing protocol test by ~~merging an upstream fix to make Base64 string length a multiple of 4 (aka padded)~~ adding support for unpadded Base64 inputs
This change is required to comply with Smithy protocol tests which assert that empty header values are sent.

fix: address various failing protocol tests

---

.changes/b0646077-397d-48a8-94f2-ea2db40b1dea.json
gradle/libs.versions.toml
runtime/auth/aws-signing-default/common/src/aws/smithy/kotlin/runtime/auth/awssigning/Canonicalizer.kt
runtime/auth/aws-signing-default/common/test/aws/smithy/kotlin/runtime/auth/awssigning/DefaultCanonicalizerTest.kt
runtime/auth/http-auth-aws/common/test/aws/smithy/kotlin/runtime/http/auth/AwsHttpSignerTestBase.kt

(none)
This change adds headers defined by [RFC 2616 § 13.5.1](https://datatracker.ietf.org/doc/html/rfc2616#section-13.5.1) as "hop-by-hop" headers to the ignore list for signing. This prevents signatures from becoming invalid if intervening proxies/caches alter the headers.

fix: ignore hop-by-hop headers when signing requests

---

.changes/c0040355-ffdc-4813-80e9-baf859ef02b9.json
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/collections/CaseInsensitiveMap.kt
runtime/runtime-core/common/test/aws/smithy/kotlin/runtime/collections/CaseInsensitiveMapTest.kt

(none)
This change fixes a small bug in hashcode calculation for `CaseInsensitiveMap` entries, namely that the hashcode calculation does not match the one used by JVM and Kotlin/Native's standard implementations.

Fix caseinsensitivemap entry hashcode

---

.changes/e7d8178c-4211-443d-b4d9-44d7019aefd1.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/endpoints/discovery/EndpointDiscovererGenerator.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/endpoints/discovery/EndpointDiscovererGeneratorTest.kt

Partially addresses https://github.com/awslabs/aws-sdk-kotlin/issues/1413
This change updates endpoint resolution to favor `endpointUrl` over endpoint discovery when both are provided/enabled. This allows callers to bypass endpoint discovery when using a custom endpoint.
This change is backported from https://github.com/smithy-lang/smithy-kotlin/pull/1221 (slated for **v1.5**) but only includes non-breaking changes in codegen.

fix: favor endpointUrl over endpoint discovery when provided

---

tests/compile/src/test/kotlin/software/amazon/smithy/kotlin/codegen/SmithySdkTest.kt
tests/compile/src/test/resources/kitchen-sink-model.smithy

closes https://github.com/smithy-lang/smithy-kotlin/issues/1129
Adds a test to make sure we don't regress.
See: https://github.com/awslabs/aws-sdk-kotlin/pull/1526

misc: test union member name same as union

---

codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinSymbolProvider.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/core/SymbolProviderTest.kt
tests/compile/src/test/kotlin/software/amazon/smithy/kotlin/codegen/SmithySdkTest.kt

https://github.com/smithy-lang/smithy-kotlin/issues/1127
Lists and Maps were the only offenders of this type of bug. Adding a fully qualified name to the symbol fixes the naming conflicts like the ones shown in https://github.com/smithy-lang/smithy-kotlin/issues/1127

fix: unions with member names matching auto-imported Kotlin symbols

---

.changes/ba71e47f-d546-45f2-bf44-aedaab74a966.json
runtime/protocol/aws-event-stream/common/src/aws/smithy/kotlin/runtime/awsprotocol/eventstream/Message.kt

Event streams spec was updated to say:
```
Additionally, services MUST validate, and clients MUST NOT validate, that:
The payload of a message may not exceed 25,165,824 bytes (24 MB).
The headers_length of a message may not exceed 131,072 bytes (128 kB). Note
that the in-memory representation of the headers, once decoded, may legally
exceed this value.
```
Some services are returning messages >16kB, which would currently fail. 

fix: bump maximum event stream message length to 24MB

---

codegen/smithy-kotlin-codegen/src/test/resources/sdk-ids-test-output.csv
codegen/smithy-kotlin-codegen/src/test/resources/sdk-ids.csv

N/A
Removes Elastic Inference from SDK ID tests

misc: Remove Elastic Inference SDK ID test

---

codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/waiters/KotlinJmespathExpressionVisitor.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/endpoints/OperationContextParamsTest.kt
tests/codegen/waiter-tests/model/function-keys.smithy
tests/codegen/waiter-tests/src/test/kotlin/com/test/FunctionKeysTest.kt

N/A
Adds support for Kotlin maps as JMESPath objects to the [`keys` function](https://jmespath.org/specification.html#keys)

fix: account ID based endpoints

---

.brazil.json
.changes/ec884c41-7bda-4033-a80b-5da20836a64b.json
gradle/libs.versions.toml
runtime/observability/telemetry-api/api/telemetry-api.api
runtime/observability/telemetry-api/common/src/aws/smithy/kotlin/runtime/telemetry/trace/AbstractTraceSpan.kt
runtime/observability/telemetry-api/common/src/aws/smithy/kotlin/runtime/telemetry/trace/CoroutineContextTraceExt.kt
runtime/observability/telemetry-api/common/src/aws/smithy/kotlin/runtime/telemetry/trace/TraceSpan.kt
runtime/observability/telemetry-provider-otel/build.gradle.kts
runtime/observability/telemetry-provider-otel/jvm/src/aws/smithy/kotlin/runtime/telemetry/otel/OtelTracerProvider.kt

fix: replace `Span.makeCurrent()` with `Span.asContextElement()`

---

.changes/13a47747-197a-4b88-bc3b-393af5f5127a.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/PaginatorGenerator.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/PaginatorGeneratorTest.kt
gradle/libs.versions.toml

(none)
The codegen for paginators does not correctly handle the case of item types whose names collide with other types. Specifically, the function signature for the items paginator is formed without taking into account existing imports. This was discovered in a test model in which the pagination items were of type `Flow` which caused a paginator like this:
```kotlin
public fun Flow<FooResponse>.flows(): Flow<Flow> = ...
```
This PR improves the logic which forms item descriptors in paginator generators and will fully qualify type names which collide with existing imports, leading to this:
```kotlin
public fun Flow<FooResponse>.flows(): Flow<com.foo.Flow> = ...
```

fix: correctly codegen paginators for types which require fully-qualified names

---

runtime/smithy-client/common/src/aws/smithy/kotlin/runtime/client/SdkClientOption.kt

`ExecutionContext` and the keys of `SdkClientOption` are both fully public. Let's make these convenience extension functions public too.

misc: remove `@InternalApi` from `SdkClientOption` extension functions

---

codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/RuntimeTypes.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/lang/KotlinTypes.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/smoketests/SmokeTestsRunnerGenerator.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/smoketests/SmokeTestsRunnerGeneratorTest.kt
runtime/runtime-core/api/runtime-core.api
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/smoketests/SmokeTestsFunctions.kt

(none)
This change modularizes smoke test runners to improve their testability so that the E2E smoke tests can be refactored in **aws-sdk-kotlin** to run inside the top-level Gradle build.
**Companion PR**: https://github.com/awslabs/aws-sdk-kotlin/pull/1558

chore: reintegrate E2E smoke tests into the top-level Gradle build; modularize smoke test runners to improve testability

---

settings.gradle.kts

Pulling this in from kn-main: https://github.com/smithy-lang/smithy-kotlin/blob/kn-main/settings.gradle.kts#L29

misc: include `aws-crt-kotlin` as a composite build

---

.brazil.json
codegen/smithy-aws-kotlin-codegen/build.gradle.kts
gradle.properties
gradle/libs.versions.toml

misc: prepare codegen packages for internal import

---

gradle/libs.versions.toml

(none)
Upgrade **aws-kotlin-repo-tools** to **0.4.22** to pick up [fix for compiler warning](https://github.com/awslabs/aws-kotlin-repo-tools/pull/82).

chore: upgrade aws-kotlin-repo-tools

---

.changes/6795f037-bb98-434b-8b87-1bbe59b2edb2.json
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/ConnectionIdleMonitor.kt

https://github.com/awslabs/aws-sdk-kotlin/issues/1214
This change widens the socket exceptions caught by `ConnectionIdleMonitor` when a connection has been closed remotely to account for new behavior reported in https://github.com/awslabs/aws-sdk-kotlin/issues/1214.

fix: improve handling of expected socket exceptions when using connection poller

---

.changes/14965afd-c9f4-48b0-a053-de860b81ecd2.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/GradleGenerator.kt

This changes add new lines between sections in the `gradle` file, and also properly indents the dependencies.
**Before**
```
plugins {
kotlin("jvm") version "2.1.0"
}
repositories {
mavenLocal()
mavenCentral()
}
dependencies {
implementation(kotlin("stdlib"))
implementation("aws.smithy.kotlin:aws-credentials:1.4.17-SNAPSHOT")
implementation("aws.smithy.kotlin:aws-json-protocols:1.4.17-SNAPSHOT")
implementation("aws.smithy.kotlin:aws-protocol-core:1.4.17-SNAPSHOT")
implementation("aws.smithy.kotlin:aws-signing-common:1.4.17-SNAPSHOT")
implementation("aws.smithy.kotlin:aws-signing-default:1.4.17-SNAPSHOT")
implementation("aws.smithy.kotlin:http:1.4.17-SNAPSHOT")
implementation("aws.smithy.kotlin:http-auth:1.4.17-SNAPSHOT")
implementation("aws.smithy.kotlin:http-auth-aws:1.4.17-SNAPSHOT") …
```

style: properly indent the dependencies in the gradle file

---

.changes/bbe2e7de-79d3-4aea-97d1-d5c244ede433.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinSymbolProvider.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ShapeValueGenerator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/SerializeStructGenerator.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/core/SymbolProviderTest.kt

https://github.com/smithy-lang/smithy-kotlin/issues/1287
This change imports the symbol references to add them to the resulting Kotlin file. Without this the codegen for protocol tests with the latest Smithy model complains about missing symbols such as 
* `decodeBase64`
* `fromEpochMilliseconds`
Some of the references were added but not imported. Some others needed being added and imported.

fix: add import references when needed

---

.changes/bdcf7bc9-094c-4434-aa34-1df7f4f4c936.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ShapeValueGenerator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpProtocolUnitTestRequestGenerator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpProtocolUnitTestResponseGenerator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/smoketests/SmokeTestsRunnerGenerator.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ShapeValueGeneratorTest.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/smoketests/SmokeTestsRunnerGeneratorTest.kt

Addresses issues with name clashes in generated smoke tests by adding and using an `explicitReceiver` parameter, which prefixes shape member names with `this.`

fix: add `explicitReceiver` parameter to `ShapeValueGenerator`

---

.changes/2ec4ad9a-f964-4cf1-be58-d0229493bb81.json
bom/build.gradle.kts
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinDependency.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/GradleGenerator.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/KotlinSettingsTest.kt
gradle/libs.versions.toml
runtime/auth/aws-credentials/api/aws-credentials.api
runtime/auth/aws-signing-tests/build.gradle.kts
runtime/auth/http-auth-api/api/http-auth-api.api
runtime/auth/http-auth-aws/api/http-auth-aws.api
runtime/auth/http-auth/api/http-auth.api
runtime/auth/identity-api/api/identity-api.api
runtime/build.gradle.kts
runtime/observability/telemetry-api/api/telemetry-api.api
runtime/protocol/aws-json-protocols/api/aws-json-protocols.api
runtime/protocol/aws-protocol-core/api/aws-protocol-core.api
runtime/protocol/http-client-engines/http-client-engine-okhttp/api/http-client-engine-okhttp.api
runtime/protocol/http-client/api/http-client.api
runtime/protocol/http/api/http.api
runtime/protocol/smithy-rpcv2-protocols/api/smithy-rpcv2-protocols.api
runtime/runtime-core/api/runtime-core.api
runtime/serde/serde-xml/api/serde-xml.api
runtime/smithy-client/api/smithy-client.api
tests/codegen/waiter-tests/build.gradle.kts

(none)
Upgrade to Kotlin 2.2.0.

feat: upgrade to Kotlin 2.2.0

---

.changes/d4f09e32-8bcc-406e-96e0-2743280c13d9.json
codegen/smithy-kotlin-codegen-testutils/src/main/kotlin/software/amazon/smithy/kotlin/codegen/test/ModelTestUtils.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/KotlinSettings.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinDependency.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpStringValuesMapSerializerTest.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/SerializeStructGeneratorTest.kt

Resolves https://github.com/awslabs/aws-sdk-kotlin/issues/1608
This change is identical to #1302 but has been rebased onto **v1.5-main** since it is a behavioral breaking change.
This change switches the default serialization mode from `WHEN_DIFFERENT` (meaning only if the value has been changed from the default) to `ALWAYS` (meaning...well, always). This is the current [recommendation from Smithy](https://smithy.io/2.0/spec/type-refinement-traits.html#default-value-serialization) and will offer more deterministic communication with services.

fix: always serialize defaults

---

.github/workflows/artifact-size-metrics.yml
.github/workflows/changelog-verification.yml
.github/workflows/kat-transform.yml

(none)
As described by [this FAQ entry](https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-852541544), this PR enables Depenabot PRs to successfully run workflows which require GH token permissions (e.g., to fetch AWS credentials).

chore: migrate to pull_request_target for some workflows that require GH token permissions

---

.github/workflows/changelog-verification.yml

(none)
Dependabot version upgrade PRs don't include changelog entries and that's just fine.

chore: skip changelog verification for Dependabot PRs

---

runtime/auth/http-auth/api/http-auth.api
runtime/auth/http-auth/common/src/aws/smithy/kotlin/runtime/http/auth/EnvironmentBearerTokenProvider.kt
runtime/auth/http-auth/common/test/aws/smithy/kotlin/runtime/http/auth/EnvironmentBearerTokenProviderTest.kt
runtime/runtime-core/api/runtime-core.api
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/businessmetrics/BusinessMetricsUtils.kt

feat: emit bearer business metric
