smithy-lang/smithy-kotlin

gradle.properties

(none)
Presetting version number for future release.

chore: preparation for future release

---

.github/workflows/continuous-integration.yml
build.gradle.kts
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/GradleGenerator.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/GradleGeneratorTest.kt

N/A
* Add windows target to CI
* Removes unnecessary tokens that were required to checkout dependencies when repos were private

chore(ci): remove tokens and add windows to ci

---

docs/design/domain-class-types-in-kotlin-sdk.md

I used the `client-generator` example module to generate the code samples to ensure validity. 
https://github.com/awslabs/smithy-kotlin/issues/471
* Fix type names to be consistent based on feedback in https://github.com/awslabs/smithy-kotlin/issues/471
* Update samples to use current codegen.
* Misc cleaup

Update entity type design doc samples w/ consistent code

---

gradle.properties

chore: release 0.4.1-alpha

---

gradle.properties

N/A
Bump snapshot version for next release

chore: bump snapshot version

---

CHANGELOG.md
gradle.properties

N/A
Prepare `0.6.0-alpha` release

chore: release 0.6.0-alpha

---

gradle.properties

* Retry of https://github.com/awslabs/smithy-kotlin/pull/514 with matching branch names to appease CI

Version bump to snapshot

---

.github/pull_request_template.md

N/A
Remove scope from PR template

chore: remove scope section from pr template

---

CHANGELOG.md
gradle.properties

(none)
Version bump and changelog for **0.7.1-alpha** release.

chore: v0.7.1-alpha release

---

gradle.properties

None
Set version to **0.7.2-SNAPSHOT** post-release.

chore: version bump to 0.7.2-SNAPSHOT

---

CHANGELOG.md
gradle.properties

(none)
* Version bump and changelog for 0.7.2-alpha release.

0.7.2-alpha release

---

gradle.properties

(none)
* Set version to 0.7.3-SNAPSHOT post-release

Set version to 0.7.3-SNAPSHOT post-release

---

CHANGELOG.md
gradle.properties

(none)
* Manually merge changelog entry from beta release
* Apply standard steps to version bump

Chore release version bump

---

gradle.properties

(none)
* Update to next snapshot version

Update to SNAPSHOT version

---

CHANGELOG.md
gradle.properties

chore: release 0.7.5

---

gradle.properties

(none)
Prepare for **0.7.6** release.

chore: prepare for 0.7.6 release

---

gradle.properties

bump version to 0.7.7-SNAPSHOT

chore: prepare 0.7.7 snapshot

---

CHANGELOG.md
gradle.properties

(none)
Merge changelog and version bump from **release** branch.

chore: prepare for 0.7.9 release

---

build.gradle.kts
docs/dokka-presets/README.md
docs/dokka-presets/css/aws-styles.css
docs/dokka-presets/css/logo-styles.css

N/A
Fixes dokka styling (applies the same changes we made in https://github.com/awslabs/aws-sdk-kotlin/pull/592)

chore: fix dokka styles

---

.changes/1fba0d71-4b78-4be7-af2a-e9a47d060d6d.json
gradle.properties
runtime/protocol/http-client-engines/http-client-engine-crt/jvm/test/aws/smithy/kotlin/runtime/http/engine/crt/AsyncStressTest.kt

aws-sdk-kotlin#473
Upgrade CRT to latest

fix: upgrade CRT to latest including M1 support and Sigv4a fixes

---

.github/workflows/changelog-verification.yml
CONTRIBUTING.md

chore: add changelog howto in CONTRIBUTING

---

.changes/fb66b9e0-8137-45c3-a61a-5d4236ea577c.json
gradle.properties

chore: bump crt version

---

.changes/95acd8ef-0ab9-4ebc-9a14-1479fdc7f9e1.json
.github/workflows/lint.yml
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/EnumGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpStringValuesMapSerializer.kt

(none)
Some ktlint-non-compliant code made it into the repo because the ktlint action wasn't running on all pull requests. Adding the necessary configuration and fixing the lint.

chore: fix ktlint issues and enable CI check on fork pull requests

---

.changes/83024e02-aefa-4457-94a3-bd9c3eecf396.json
CONTRIBUTING.md

[aws-sdk-kotlin#683](https://github.com/awslabs/aws-sdk-kotlin/issues/683)
Makes it easier for PR submitters to understand what checks are required and how to run them locally.

docs: add section on PR checks to CONTRIBUTING.md

---

docs/design/endpoints.md

misc: add design document for endpoints2 implementation

---

.changes/8455f4eb-e07a-4e22-a612-c2c4d4da9d60.json
CONTRIBUTING.md

(none)
Update and clarify the contributing guidelines to more explicitly detail:
* Expected format for changelog entries
* Optionality of subject and footer for commit messages

chore: update/clarify changelog and commit instructions in CONTRIBUTING.md

---

gradle.properties

(none)
Update to the latest published version of **aws-crt-kotlin** in preparation for release.

chore: bump aws-crt-kotlin version

---

.changes/f01f5a37-e7ca-4786-a0a9-fd1ed6adf127.json

chore: fix changelog entry for release

---

gradle.properties

(none)
Bump version of **aws-crt-kotlin** in preparation for release.

chore: bump aws-crt-kotlin to latest version

---

.github/workflows/continuous-integration.yml
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/test/aws/smithy/kotlin/runtime/http/engine/okhttp/ByteChannelRequestBodyTest.kt

#739 
**IGNORE**: This PR isn't ready for review. 🙅‍♂️

fix: update CI test timeout to accomodate MacOS runners

---

.changes/51ec552f-1a2f-49d2-8e87-a421ad1dec27.json
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/StructureGenerator.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/UnionGenerator.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/StructureGeneratorTest.kt
smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/UnionGeneratorTest.kt

fixes https://github.com/awslabs/smithy-kotlin/issues/763

fix(codegen): respect sensitive trait when applied to container shape

---

.changes/770693e4-ae47-4620-b1d3-22cc01254bb6.json
docs/design/per-op-config.md

misc: add design doc for per-op config

---

gradle.properties
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/RuntimeTypes.kt
smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpProtocolClientGenerator.kt

misc: fix RuntimeTypes typo

---

docs/design/README.md
docs/design/flexible-checksums.md

Adds the design doc for flexible checksums, which was implemented in #772 and https://github.com/awslabs/aws-sdk-kotlin/pull/799
N/A
This is required to add user-friendly documentation about the new feature. 

misc: flexible checksums design

---

gradle.properties

Bump version of **aws-crt-kotlin** for release

chore: bump version of aws-crt-kotlin for release

---

.changes/3ac31858-0e36-434b-a46f-c35de6bab62c.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinDependency.kt
gradle.properties

chore: upgrade kotlin to 1.8.10

---

codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/RuntimeTypes.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/util/ConfigProperty.kt

Supports https://github.com/awslabs/aws-sdk-kotlin/pull/869

misc: add runtime symbol and symbol builder convenience method

---

.changes/ce8cc156-ee47-40ce-8ef7-7c3fca2e9536.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ServiceClientConfigGenerator.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ServiceClientConfigGeneratorTest.kt
tests/codegen/paginator-tests/src/main/kotlin/com/test/endpoints/EndpointParameters.kt
tests/codegen/paginator-tests/src/main/kotlin/com/test/endpoints/EndpointProvider.kt
tests/codegen/waiter-tests/src/main/kotlin/com/test/endpoints/EndpointParameters.kt
tests/codegen/waiter-tests/src/main/kotlin/com/test/endpoints/EndpointProvider.kt

misc: add clarifying docs for endpointProvider

---

codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/RuntimeTypes.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/auth/Sigv4AuthSchemeIntegration.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/util/RuntimeConfigProperty.kt
runtime/auth/aws-credentials/common/src/aws/smithy/kotlin/runtime/auth/awscredentials/CredentialsProviderConfig.kt
runtime/auth/http-auth-api/common/src/aws/smithy/kotlin/runtime/http/auth/HttpAuthConfig.kt

N/A
* Adds a base class for credentials config and http auth schemes config

add base class for credentials config and http auth schemes

---

CHANGELOG.md

Update changelog to note that 0.17.3 is identical to 0.17.2
N/A

misc: update changelog (#838) 

---

gradle.properties

bump sdk version for breaking http engine changes

---

CONTRIBUTING.md

(none)
Same as [aws-sdk-kotlin#990](https://github.com/awslabs/aws-sdk-kotlin/pull/990)

chore: update CONTRIBUTING guidelines to talk about more PR criteria

---

gradle.properties

(none)
Bump the version of CRT to the latest release.

chore: upgrade CRT version

---

codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/waiters/KotlinJmespathExpressionVisitor.kt
tests/codegen/waiter-tests/model/waiter-operations.smithy
tests/codegen/waiter-tests/src/test/kotlin/com/test/WaiterTest.kt

closes #920
Slicing is now supported via updates to the projection, subexpression and new slicing function
[JMESPath playground](https://jmespath.org/) might be a good site to manually verify tests if needed.

feat: add support for slicing in JMESPath

---

.changes/d477286c-f799-426b-947c-7cc6982fbcfe.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ServiceClientGenerator.kt

misc: add support for downstream endpoint url config feature

---

.changes/af596973-0dfa-4906-b26f-f55a5f3ec60e.json
gradle/libs.versions.toml

chore: bump aws-crt-kotlin to 0.7.1

---

runtime/runtime-core/common/test/aws/smithy/kotlin/runtime/content/ByteStreamFlowTest.kt

N/A
Temporarily disable flaky tests

test: disable flaky tests for release

---

.changes/1aed8534-646f-4f57-8e4a-c95abf1c79d3.json
gradle/libs.versions.toml

chore: bump crt kotlin version

---

.changes/666fa825-d13b-458c-af63-354434bfc2ed.json
bom/build.gradle.kts
settings.gradle.kts

n/a
Publish a BOM and version catalog.

feat: publish a BOM and version catalog

---

.changes/2bc24fcf-8a56-4fac-bfbf-83fd0c7fd9f0.json
gradle/libs.versions.toml

Upgrade to the latest version of aws-crt-kotlin.

misc: upgrade aws-crt-kotlin version

---

bom/build.gradle.kts

fix: add descriptions to `bom` and `version-catalog` publications

---

build.gradle.kts

misc: bump build plugin

---

.changes/cf638060-f5d7-48f2-9e68-651a11e4c033.json
.github/workflows/continuous-integration.yml
codegen/smithy-kotlin-codegen-testutils/build.gradle.kts
codegen/smithy-kotlin-codegen/build.gradle.kts
gradle.properties

misc: separate codegen version

---

.changes/1bedae98-109c-4b86-8f45-bf71b676bca0.json
.changes/41390c52-e57d-4a1d-a261-465ae2f43d70.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinSymbolProvider.kt
codegen/smithy-kotlin-codegen/src/test/kotlin/software/amazon/smithy/kotlin/codegen/core/SymbolProviderTest.kt
gradle.properties
gradle/libs.versions.toml
runtime/auth/aws-signing-tests/jvm/src/aws/smithy/kotlin/runtime/auth/awssigning/tests/SigningSuiteTestBaseJVM.kt
runtime/observability/telemetry-api/common/src/aws/smithy/kotlin/runtime/telemetry/metrics/Histogram.kt
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/HttpEngineEventListener.kt
runtime/protocol/http-client/common/src/aws/smithy/kotlin/runtime/http/interceptors/OperationTelemetryInterceptor.kt
runtime/protocol/http-client/common/src/aws/smithy/kotlin/runtime/http/operation/OperationTelemetry.kt
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/retries/delay/AdaptiveRateLimiter.kt
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/retries/delay/StandardRetryTokenBucket.kt
runtime/runtime-core/common/test/aws/smithy/kotlin/runtime/retries/delay/StandardRetryTokenBucketTest.kt

Bump dependencies to their latest available versions

misc: bump dependency versions

---

codegen/smithy-kotlin-codegen/build.gradle.kts

fix: versioning issue

---

runtime/runtime-core/api/runtime-core.api
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/util/Filesystem.kt
runtime/runtime-core/jvm/src/aws/smithy/kotlin/runtime/util/PlatformJVM.kt
runtime/runtime-core/jvm/test/aws/smithy/kotlin/runtime/util/PlatformJVMTest.kt
runtime/runtime-core/native/src/aws/smithy/kotlin/runtime/util/PlatformNative.kt

Add `fileExists` API for internal usage. 

misc: add `fileExists` API

---

build.gradle.kts

*Issue #, if available:*
*Description of changes:*
Fix signing publication dependencies. See https://github.com/awslabs/aws-kotlin-repo-tools/pull/28 for context.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

chore: fix signing task dependencies

---

.changes/38511aca-afd8-4387-b397-7b45479c2c69.json
gradle/libs.versions.toml

Bump to latest version of smithy

misc: bump to smithy 1.42.0

---

build.gradle.kts
gradle/libs.versions.toml
settings.gradle.kts

Upgrades the build to move away from source dependencies and use published version from our own "private" maven repository.

chore: upgrade to published version

---

build.gradle.kts
gradle/libs.versions.toml
runtime/build.gradle.kts
tests/benchmarks/aws-signing-benchmarks/build.gradle.kts
tests/benchmarks/channel-benchmarks/build.gradle.kts
tests/benchmarks/http-benchmarks/build.gradle.kts
tests/benchmarks/serde-benchmarks/build.gradle.kts
tests/codegen/nullability-tests/build.gradle.kts
tests/codegen/paginator-tests/build.gradle.kts
tests/codegen/waiter-tests/build.gradle.kts

upstream https://github.com/awslabs/aws-kotlin-repo-tools/pull/32

refactor: upstream plugin changes

---

.changes/01ea7858-c080-447f-9bd1-93bdec3f0161.json
runtime/smithy-client/common/src/aws/smithy/kotlin/runtime/client/LogMode.kt
runtime/smithy-client/common/test/aws/smithy/kotlin/runtime/client/LogModeTest.kt

fix: a bug in LogMode `isEnabled`

---

.changes/cbd05818-cbc1-4b22-8ed1-25cba6d4b769.json
gradle/libs.versions.toml

misc: bump to smithy 1.45.0

---

CODEOWNERS

(none)
Fix unmigrated CODEOWNERS file.

chore: update CODEOWNERS to reflect new GH org

---

.brazil.json

fix: update transformation JSON to include non-JVM okhttp-coroutines and okhttp

---

gradle/libs.versions.toml

This PR upgrades the repo tools version 
N/A

misc: version bump repo tools

---

.changes/1669a4b4-4b10-4ca6-b11a-43bf5413de19.json
codegen/smithy-aws-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/aws/protocols/Ec2Query.kt
codegen/smithy-aws-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/aws/protocols/core/QueryHttpBindingProtocolGenerator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/model/RulesEngineExt.kt
gradle/libs.versions.toml

Upgrade to Smithy 1.49.0 which involves customizing the ec2Query protocol due to an upstream protocol test change: https://github.com/smithy-lang/smithy/pull/2269

misc: upgrade to Smithy 1.49.0

---

runtime/runtime-core/api/runtime-core.api
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/businessmetrics/BusinessMetricsUtils.kt

A new metric ID from the spec overrode one that we were emitting but is not in the spec yet

fix: business metrics ids

---

build.gradle.kts
runtime/build.gradle.kts

Fixes a Dependabot vulnerability [coming from Dokka](https://github.com/Kotlin/dokka/issues/3194)

misc: update vulnerable dependency pulled in transitively from Dokka

---

build.gradle.kts

This reverts commit 86e012c2d24345db5ac7d5248be1f60a3d0a09d7.

misc: Revert "misc: update vulnerable dependency pulled in transitively from Dokka (#1109)"

---

.changes/73d67571-b9ff-4c49-be67-12d771d30459.json
gradle/libs.versions.toml

misc: bump aws-crt-kotlin version

---

docs/dokka-presets/scripts/accessibility.js

misc(docs): only run accessibility scripts after the sidebar has fully loaded

---

runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/businessmetrics/BusinessMetricsUtils.kt

misc: update sigv4a business metric id

---

docs/dokka-presets/scripts/accessibility.js

docs: only register event listeners once

---

docs/dokka-presets/css/aws-styles.css
docs/dokka-presets/scripts/accessibility.js
docs/dokka-presets/templates/base.ftl

misc: fix docs accessibility

---

.changes/8fb6b646-598a-4d12-bb92-cda145ce943c.json
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/core/KotlinDependency.kt
gradle/libs.versions.toml

misc: upgrade to Kotlin 2.0.10

---

.brazil.json

fix: Add OkHttp 4.x to transformation configuration

---

.brazil.json

fix: add resolves-conflict-dependency for OkHttp 4.x

---

.brazil.json

misc: add temporary resolves-conflict-dependencies to facilitate import

---

.changes/c75f1745-f836-4900-8b42-7bb90433ac94.json
.changes/db40be47-f4a0-4085-81f3-2dbfa7b7fe94.json
codegen/smithy-aws-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/aws/protocols/core/AwsHttpBindingProtocolGenerator.kt
gradle/libs.versions.toml

misc: bump Smithy version

---

.github/workflows/kat-transform.yml

feat: `kat` in CI

---

codegen/smithy-kotlin-codegen/src/test/resources/sdk-ids-test-output.csv
codegen/smithy-kotlin-codegen/src/test/resources/sdk-ids.csv

misc: remove nimble service

---

gradle.properties

(n/a)
This updates the snapshot version because of a failed partial release.

chore: manually bump snapshot version because of incomplete release

---

codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/smoketests/SmokeTestsIntegration.kt

misc: disable smoke test runner code generation

---

.github/workflows/api-compat-verification.yml
.github/workflows/artifact-size-metrics.yml
.github/workflows/changelog-verification.yml
.github/workflows/continuous-integration.yml
.github/workflows/dependabot.yml
.github/workflows/kat-transform.yml
.github/workflows/lint.yml

(none)
Add the standard **main** workflows to ***-main** branches.

chore: add *-main to branch workflows

---

.brazil.json

fix: add 0.9.x aws-crt-kotlin transform

---

.github/workflows/continuous-integration.yml
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/MetricsInterceptor.kt
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/OkHttpEngine.kt
runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/OkHttpUtils.kt
runtime/protocol/http-client-engines/http-client-engine-okhttp4/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp4/OkHttp4Engine.kt
runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/util/JMESPath.kt

misc: re-enable `kotlinWarningsAsErrors=true`

---

gradle/wrapper/gradle-wrapper.properties

misc: gradle version bump

---

gradle/libs.versions.toml

misc: bump build plugin version

---

.github/workflows/merge-main.yml

N/A
Adds a workflow that attempts to merge main into feature branches every work day at midnight (PST)

feat: main to feature branches merge

---

.github/workflows/sync-mirror.yml

N/A
Syncs mirror's main branch on pushes to main

feat: sync mirror

---

.github/workflows/artifact-size-metrics.yml

misc: use aws-kotlin-repo-tools show-results action

---

.github/workflows/merge-main.yml

fix: merge main workflow credentials

---

docs/dokka-presets/templates/base.ftl
dokka-smithy/build.gradle.kts
dokka-smithy/src/test/kotlin/aws/smithy/kotlin/dokka/DokkaSmithyTest.kt

kotlin sdk change for reference: https://github.com/awslabs/aws-sdk-kotlin/pull/1587/files

feat: add analytic to smithy kotlin api ref docs

---

runtime/protocol/http-client/common/src/aws/smithy/kotlin/runtime/http/interceptors/FlexibleChecksumsResponseInterceptor.kt

misc: Downgrade "response headers didn't contain a valid checksum" to INFO

---

codegen/smithy-kotlin-codegen/src/test/resources/sdk-ids-test-output.csv
codegen/smithy-kotlin-codegen/src/test/resources/sdk-ids.csv

misc: deprecate private networks service

---

.github/workflows/release-readiness.yml
CONTRIBUTING.md

misc: add release readiness to contributing.md

---

gradle/libs.versions.toml

misc: repo tools version bump

---

gradle/libs.versions.toml

(none)
Bump repo tools to **0.4.32**.

chore: bump aws-kotlin-repo-tools version

---

.github/workflows/continuous-integration.yml
gradle/libs.versions.toml
runtime/build.gradle.kts

kn: upgrade to latest version of aws-kotlin-repo-tools

---

runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/OkHttpEngine.kt

(none)
Merge **main** to **v1.5-main** in preparation for **v1.5** release.

chore: v1.5-main merge

---

.changes/3ba693b2-e45f-4343-bd4e-883ab42acfe7.json
runtime/protocol/http-client-engines/http-client-engine-okhttp4/README.md

Closes https://github.com/smithy-lang/smithy-kotlin/issues/1339

misc: add documentation for OkHttp4Engine when using Android with R8 / ProGuard

---

runtime/protocol/http-client-engines/http-client-engine-okhttp4/README.md

fix typo: OkHttpEngine4 -> OkHttp4Engine

---

.changes/47e8421b-f037-4968-9592-13cc3e237448.json
codegen/protocol-tests/build.gradle.kts
gradle/libs.versions.toml
gradle/wrapper/gradle-wrapper.properties

misc: upgrade to Gradle 9.0.0

---

gradle/libs.versions.toml

misc: bump aws-kotlin-repo-tools

---

gradle/libs.versions.toml

misc: upgrade to latest aws-kotlin-repo-tools version

---

codegen/smithy-aws-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/aws/protocols/core/AwsHttpBindingProtocolGenerator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/model/knowledge/SerdeIndex.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/ExceptionBaseClassGenerator.kt
codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/protocol/HttpBindingProtocolGenerator.kt
gradle/libs.versions.toml

chore: smithy version bump

---

gradle.properties
gradle/libs.versions.toml

fix: upgrade to latest version of aws-kotlin-repo-tools, skip 1.5.13
